### ISSUE TITLE
Gather Auth and ADE metrics for NASA/ESA telecon

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#100]
Collect all information so far that we have for the ADE and Auth to present to ESA.

**Comment by bsatoriu** [comment]
Auth metrics from May and June provided on Wednesday, June 24, along with three weeks of ADE metrics. Attached are the files.
[CAS May June 2020.xlsx](https://github.com/MAAP-Project/ZenHub/files/4839986/CAS.May.June.2020.xlsx)
![Screen Shot 2020-06-24 at 10 45 12 AM](https://user-images.githubusercontent.com/27687558/85915049-f9445980-b7f8-11ea-873b-0d429cca7ba9.png)
