### ISSUE TITLE
Submitting jobs & algorithms failing DIT

### ISSUE THREAD

**Issue by grallewellyn** [MAAP-Project/ZenHub#1003]
Submitting jobs gives a 500 error and registering an algorithm is returning an undefined response. The jupyter server extension get example endpoint is returning successfully. Sujen thinks it might be related to the deployment of reading settings from env variables

**Comment by sujen1412** [comment]
Updated the CI variables correctly to fill in the missing values which was preventing the API from committing to register job. 

Algorithm registration is working again, but the api is unable to fetch build information, checking....

**Comment by sujen1412** [comment]
The service should be back up now. Please re-open this issue in case of any issue.

**Comment by grallewellyn** [comment]
Now in DIT I can't view my jobs or see the list of algorithms for submitting a job
jupyter-server-extension/listAlgorithms returns a 500 error and jupyter-server-extension/listUserJobs is successful, but doesn't return anything

**Comment by sujen1412** [comment]
Let me check whats going on...

Using `mas.dit.maap-project.org/root/maap-workspaces/jupyterlab3/vanilla:develop` I am able to view my jobs and list algorithms in the Submit Job page. 
![Screenshot 2024-05-23 at 2 22 20 PM](https://github.com/MAAP-Project/Community/assets/6220682/5f53c8e7-145c-49ae-b9cb-c17a40c48863)

**Comment by sujen1412** [comment]
I am not able to submit a job and thats due to another CI variable missing. I just added redeploying now.

**Comment by grallewellyn** [comment]
Viewing jobs and algorithms is working for me now
