### ISSUE TITLE
Update Instances in OPS to at least Ubuntu 20.04

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#1004]
The following instances in OPS are on 18.04. They either need to be updated to 20.04+ or terminated.

maap-1-ade-monitoring-parent
metrics-netdata
maap-1-prometheus
ops-gitlab-runner-2
ops-gitlab-runner-1 (maybe, ami info not shown)
ops-ade-4 (operator)

**Comment by bsatoriu** [comment]
@gchang all of the listed images have been upgraded to Ubuntu 20.04.

**Comment by gchang** [comment]
I checked a few and I saw that they have been upgraded to 20.04, but MCP admins want us to replace the entire base AMI because they have security services installed that weren't configured in the 18.04 images. An in-place upgrade to 20.04 from distribution wouldn't add those services. Sorry about the confusion.

**Comment by bsatoriu** [comment]
@gchang I upgraded all the AMIs for these instances to MCP CSET Ubuntu 20.04 and terminated the old 18.04 instances.
