### ISSUE TITLE
Jobs not cancelling in DIT 

### ISSUE THREAD

**Issue by grallewellyn** [MAAP-Project/ZenHub#1006]
Potentially related to the recent MAAP API changes 
Should also change the DPS toast notification when you try to cancel the job to say "request for job cancellation was successfully submitted". There is a bunch of stuff that happens in hysds before the job is actually cancelled. 
Figaro is not showing the job being revoked, this could be cause of a delay in the update to the elasticsearch job status field.

**Comment by marjo-luc** [comment]
Resolved in DIT: https://github.com/MAAP-Project/maap-api-nasa/pull/122
