### ISSUE TITLE
EIS Needs a Larger Queue Instance (RAM and DiskSpace)

### ISSUE THREAD

**Issue by ranchodeluxe** [MAAP-Project/ZenHub#1012]
**Is your feature request related to a problem? Please describe.**
Yes, the current EIS queue `maap-dps-eis-worker-64gb` is for 64GB with 8CPUs and has max disk space size of 100GB. We've been running out of space when writing locally before the job is done 

**Describe the solution you'd like**
1. could we increase the disk space for `maap-dps-eis-worker-64gb` to ~250GB please?
2. could we get a new queue with a 128GB machine with 14 CPUs and max disk space ~500GB please?

**Describe alternatives you've considered**
None 😉 Please advise

**Additional context**
Thanks for fielding our annoying questions

**Comment by sujen1412** [comment]
- [x] Increased disk size to 250GB for maap-dps-eis-worker-64gb
- [x] set up new queue with a 128GB machine with 14 CPUs and max disk space ~500GB. Use name `maap-dps-eis-worker-128gb`

How many maximum parallel instances do you envision running for the new 128gb queue ?

**Comment by ranchodeluxe** [comment]
> How many maximum parallel instances do you envision running for the new 128gb queue ?

10 parallel workers @sujen1412

**Comment by sujen1412** [comment]
Could you please test out the new queue and let me know how its working out for you. Thanks

**Comment by sujen1412** [comment]
@ranchodeluxe - did the new queue work out for you ? It's been set per your specifications.

**Comment by ranchodeluxe** [comment]
Let me move the jobs over later today @sujen1412 and try it out

**Comment by ranchodeluxe** [comment]
okay, everything seems to be working thank @sujen1412
