### ISSUE TITLE
Show users the available instance types for given queue 

### ISSUE THREAD

**Issue by sujen1412** [MAAP-Project/ZenHub#1016]
**Is your feature request related to a problem? Please describe.**
Currently as user does not know what is the exact instance type backing a particular resource queue. Useful when the algorithm is not just memory optimized and needs more cpus.

**Describe the solution you'd like**
Having a page/description of what are the ec2 instance types behind each queue would help address this issue. 

**Additional context**
Ideas on implementation, we should query the AWS api to get what are the instances configured for a particular auto scaling group and show them to the user. 
- This can be pulled from an api endpoint to describe the queue
- Shown to the user in jupyter via an extension or on the submit job and algorithm registration page as an information pop up.

**Comment by rtapella** [comment]
Can this be built-in contextual help (i.e, in the Submit Job UI and potentially via a maap.py call?)? The AWS API can find this info on-the-fly?

**Comment by sujen1412** [comment]
TODO: 
For now, document the current available resources on the discussion board. 
Next steps would be to make it dynamically query the AWS api.

**Comment by rtapella** [comment]
do we have this list somewhere?

**Comment by rtapella** [comment]
- "what are queues" "what's possible with them"
- also need a dynamic listing per-user
- should be able to match up the name of the queue in get_queues(), jobs submit UI, algo registration UI to the info in the documentation

**Comment by rtapella** [comment]
- put built-in help in the UI to match up the name w. metadata in the jobs submit UI & algo registration UI

**Comment by sujen1412** [comment]
First pass at the queues page. 

# Resource Queues on MAAP Data Processing Service

Resource Queues are machines on the cloud that will be processing users jobs. These are [EC2](https://aws.amazon.com/ec2/) machines on AWS and are managed by [auto scaling groups](https://docs.aws.amazon.com/autoscaling/ec2/userguide/auto-scaling-groups.html). 

When a user submits a job, a message is sent to the AWS Auto Scaling Group which provisions the appropriate machine for processing (takes about 2min). The name of the queue provides an indication of what resources the machine will have. 

For example:
- `maap-dps-worker-8gb` will spin a machine that has at max 8gb of RAM, like t3.large
- `maap-dps-worker-16vcpu-32gb` will spin a machine that has 16 cores and 32gb RAM, like c5.4xlarge.

### Public Queues
Public queues are queues that are available to all MAAP users irrespective of their association with any organization (i.e guest accounts). Users who belong to an organization and have access to private queues are recommended to use the private queues. 
Currently available public queues on the MAAP platform are: 

- `maap-dps-sandbox`: This is a new queue introduced in v4.1.0 to allow users to quickly test their algorithm in DPS. This has a max job runtime of 10mins and max RAM of 8gb.
- `maap-dps-worker-8gb`
- `maap-dps-worker-16gb`
- `maap-dps-worker-32gb`

`Note: Platform team will soon start throttling users ability to submit a batch of jobs on public queues to about 10 jobs per hour.`

### Private Organization Queues

Users and user groups doing science on the MAAP are requested to reach out to the platform team to enable organizational queues for them. Features of private queues are: 

- 24 hr time limit on individual jobs (can be increased upon request).
- No job throttling.
- Custom resources can be requested on the queue, like higher CPU, GPU, etc.
- Dedicated queue, i.e not shared with other users on the MAAP reducing the amount of time spent waiting in the `queued` state.

**Comment by rtapella** [comment]
note to self: 
- link machine instance types: https://aws.amazon.com/ec2/instance-types/
- other attributes of queue? cpu, gpu, memory?

**Comment by chuckwondo** [comment]
Indication of GPU would be good too, if present.

**Comment by rtapella** [comment]
![dps-queue-table](https://github.com/user-attachments/assets/2292c632-9294-4367-b912-37f1b18a5e6d)

**Comment by chuckwondo** [comment]
@rtapella, another bad image link:

```
https://camo.githubusercontent.com/190ecff3644a96cd623a66f588b21779658588616df9381a396053e425206a5e/68747470733a2f2f6170692e7a656e6875622e636f6d2f617474616368656446696c65732f65794a66636d467062484d694f6e73696257567a6332466e5a534936496b4a42614842424f574e33516e633950534973496d563463434936626e56736243776963485679496a6f69596d7876596c39705a434a3966513d3d2d2d323836643463306437616661303939313830643239666364643639633766346665656234326134632f696d6167652e706e67
```

**Comment by rtapella** [comment]
fixed the link @chuckwondo 
sorry, zenhub has its own media store I guess, so I uploaded it straight in github instead

**Comment by chuckwondo** [comment]
> note to self:
> 
> * link machine instance types: https://aws.amazon.com/ec2/instance-types/
> * other attributes of queue? cpu, gpu, memory?

Yes, memory, cpu, and gpu.

**Comment by rtapella** [comment]
posted:
https://docs.maap-project.org/en/develop/system_reference_guide/dps_queues.html

**Comment by rtapella** [comment]
- @chuckwondo the public queues do not offer GPUs. 
- we have now referenced the AWS instance types to cross-ref the other details.
- this is all still open to feedback of course

**Comment by rtapella** [comment]
https://github.com/MAAP-Project/maap-documentation/pull/438
