### ISSUE TITLE
Update Metrics endpoint response to reflect job status

### ISSUE THREAD

**Issue by NamrataM** [MAAP-Project/ZenHub#102]
Currently if the metrics for a failed job is requested we get the following:
```
<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/2.0" xmlns:schemaLocation="http://schemas.opengis.net/wps/2.0/wps.xsd" xmlns:wps="http://www.opengis.net/wps/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ows:Exception exceptionCode="FailedGetMetrics" locator="GetMetrics">
    <ows:ExceptionText>Failed to get metrics of job c6bcfa30-e9e6-4f8b-98c7dae39185cd32. No job information found for c6bcfa30-e9e6-4f8b-98c7dae39185cd32. Maybe the job is currently queued or you entered theincorrect Job ID.. please contact administrator of DPS</ows:ExceptionText>
  </ows:Exception>
</ows:ExceptionReport>
```
This is not a correct reflection of the state of the job. Update the Exception Text to appropriately handle all job statuses other than job-completed.

**Comment by NamrataM** [comment]
Updated error to reflect the job status (if not completed) as follows:
`<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/2.0" xmlns:schemaLocation="http://schemas.opengis.net/wps/2.0/wps.xsd" xmlns:wps="http://www.opengis.net/wps/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ows:Exception exceptionCode="FailedGetMetrics" locator="GetMetrics">
    <ows:ExceptionText>Failed to get job metrics. Failed to get job information found for dcde72b2-c78f-40fd-8e8b-dc272454e350. Reason: Aborting retrieving information of job because status is job-failed. Please contact administrator of DPS for clarification if needed</ows:ExceptionText>
  </ows:Exception>
</ows:ExceptionReport>`

**Comment by NamrataM** [comment]
To test:
- Make a GET request to: https://api.maap.xyz/api/dps/job/<job_id>/metrics
- In case of a completed job you should see:
`<metrics>
  <machine_type>c5.4xlarge</machine_type>
  <architecture>x86_64</architecture>
  <machine_memory_size>30.48 GB</machine_memory_size>
  <directory_size>49152</directory_size>
  <operating_system>CentOS</operating_system>
  <job_start_time>2020-07-08T20:49:51.179378Z</job_start_time>
  <job_end_time>2020-07-08T20:49:53.194761Z</job_end_time>
  <job_duration_seconds>2.015383</job_duration_seconds>
</metrics>`
- In case of jobs of failed/queued/started jobs, you should see the following response format:
`<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/2.0" xmlns:schemaLocation="http://schemas.opengis.net/wps/2.0/wps.xsd" xmlns:wps="http://www.opengis.net/wps/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"> <ows:Exception exceptionCode="FailedGetMetrics" locator="GetMetrics"> <ows:ExceptionText>Failed to get job metrics. Failed to get job information found for dcde72b2-c78f-40fd-8e8b-dc272454e350. Reason: Aborting retrieving information of job because status is job-failed. Please contact administrator of DPS for clarification if needed</ows:ExceptionText> </ows:Exception> </ows:ExceptionReport>`

**Comment by oddes** [comment]
Still working on it. Namrata to provide reference Document for the expected fields for PASS/FAIL/Running/Queue.

**Comment by NamrataM** [comment]
@oddes Created a new ticket for documentation of all MAS and DPS API endpoints: https://app.zenhub.com/workspaces/maap-platform-5ee7f0d1f440de0024cd359b/issues/maap-project/zenhub/135

**Comment by oddes** [comment]
@NamrataM 
Would u able to post a job on DPS? can u please provide request that works? so that I can test this end-end for the following JobID statuses:

PASS
FAIL
QUEUE
DELETE [is this possible?]
RUNNING

API works for the PASS and FAIL scenarios but I dont have a way to map the api response to confirm that we are getting right fields. Need an accepting criteria.

**Comment by NamrataM** [comment]
@oddes On a successful Job you should see the metrics return with the following fields:
`<metrics>
  <machine_type>c5.4xlarge</machine_type>
  <architecture>x86_64</architecture>
  <machine_memory_size>30.48 GB</machine_memory_size>
  <directory_size>49152</directory_size>
  <operating_system>CentOS</operating_system>
  <job_start_time>2020-07-08T20:49:51.179378Z</job_start_time>
  <job_end_time>2020-07-08T20:49:53.194761Z</job_end_time>
  <job_duration_seconds>2.015383</job_duration_seconds>
  <cpu_usage>760399093</cpu_usage>
  <cache_usage>344064</cache_usage>
  <mem_usage>2433024</mem_usage>
  <max_mem_usage>39071744</max_mem_usage>
  <swap_usage>0</swap_usage>
  <read_io_stats>0</read_io_stats>
  <write_io_stats>445952</write_io_stats>
  <sync_io_stats>445952</sync_io_stats>
  <async_io_stats>0</async_io_stats>
  <total_io_stats>445952</total_io_stats>
</metrics>`

For a Failed/ Queued/ Running job:
`<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/2.0" xmlns:schemaLocation="http://schemas.opengis.net/wps/2.0/wps.xsd" xmlns:wps="http://www.opengis.net/wps/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"> <ows:Exception exceptionCode="FailedGetMetrics" locator="GetMetrics"> <ows:ExceptionText>Failed to get job metrics. Failed to get job information found for dcde72b2-c78f-40fd-8e8b-dc272454e350. Reason: Aborting retrieving information of job because status is job-failed. Please contact administrator of DPS for clarification if needed</ows:ExceptionText> </ows:Exception> </ows:ExceptionReport>`


For a Deleted / Invalid Job ID:
`<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/2.0" xmlns:schemaLocation="http://schemas.opengis.net/wps/2.0/wps.xsd" xmlns:wps="http://www.opengis.net/wps/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ows:Exception exceptionCode="FailedGetMetrics" locator="GetMetrics">
    <ows:ExceptionText>Failed to get job metrics. Failed to get job information found for d39fcb6d-52f6-4fa8-a67-14c42ee229f0. Reason: Aborting retrieving information of job because status is None. Please contact administrator of DPS for clarification if needed</ows:ExceptionText>
  </ows:Exception>
</ows:ExceptionReport>`

**Comment by oddes** [comment]
@NamrataM 
1. All the fields that were mentioned in your examples are showing as expected for PASS/FAIL scenrios.
2. For the success scenario, I have verified metrics with following jobId, looks the same output/response, just want to ensure are we hard coded response or all of these jobs are identical. These is the response I am getting for all of these job id's

<metrics>
   <machine_type>c5.4xlarge</machine_type>
   <architecture>x86_64</architecture>
   <machine_memory_size>30.48 GB</machine_memory_size>
   <directory_size>49152</directory_size>
   <operating_system>CentOS</operating_system>
   <job_start_time>2020-07-08T20:49:51.179378Z</job_start_time>
   <job_end_time>2020-07-08T20:49:53.194761Z</job_end_time>
   <job_duration_seconds>2.015383</job_duration_seconds>
   <cpu_usage>760399093</cpu_usage>
   <cache_usage>344064</cache_usage>
   <mem_usage>2433024</mem_usage>
   <max_mem_usage>39071744</max_mem_usage>
   <swap_usage>0</swap_usage>
   <read_io_stats>0</read_io_stats>
   <write_io_stats>445952</write_io_stats>
   <sync_io_stats>445952</sync_io_stats>
   <async_io_stats>0</async_io_stats>
   <total_io_stats>445952</total_io_stats>
</metrics>

**JobId's**
42dfcd01-1d17-4185-926d-8854a5a6e6ef
e6c2e5f1-ea3f-4832-9b81-061e3ba827b0
e38f0c96-1a8a-4ef8-a06f-d50a40fab9e4
e1fd451b-b567-4b84-8754-a3f1ec29fb1e
df8da3a2-1ff8-49c5-b364-186398bf0c3f
d39fcb6d-52f6-4fa8-a637-14c42ee229f0

**Comment by oddes** [comment]
Its working as expected for all the scenarios. Closing this issue.
