### ISSUE TITLE
Allow users to pass secrets to DPS job

### ISSUE THREAD

**Issue by sujen1412** [MAAP-Project/ZenHub#1023]
**Is your feature request related to a problem? Please describe.**
There currently is no clean way for users to pass secrets to their jobs running on DPS. 

**Describe alternatives you've considered**
Users have tried to store them on files in s3 and download them within jobs to access credentials.

TODO: 
Investigate approaches to enabling this for the users

**Comment by rtapella** [comment]
is this done @bsatoriu ?

**Comment by bsatoriu** [comment]
Yes, thanks @rtapella. Closed.
