### ISSUE TITLE
Rebrand Eclipse Che to just MAAP ADE

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#104]
Apparently having Eclipse Che in there causes some users to be confused about what they're using so let's just remove all mention of Eclipse Che and refer to it as the MAAP ADE, completely with our colors.

- [x] Look through the Eclipse Che source to find the HTML templates and stylesheets to update.
- [x] Update dashboard screen
- [x] Update workspaces screen
- [x] Update new workspaces screen

**Comment by gchang** [comment]
- [ ] Load up Eclipse Che and identify all the visual elements that need to be updated/removed/replaced. This includes not only text, but also colors as well.
- [ ] Look through the Eclipse Che source to find the HTML templates and stylesheets to update.
- [ ] Recompile Che and deploy to dev to verify.

**Comment by bsatoriu** [comment]
@marjo-luc here's a good place to start: https://mas.maap-project.org/root/che/tree/6.19.6-maap/dashboard/src/app

This is the Angular app that contains all of the Che front end code, including styles and branding elements.

**Comment by gchang** [comment]
![Screen Shot 2020-09-17 at 1.22.42 PM.png](https://images.zenhubusercontent.com/5ee7da582a6c07a5f569db2e/1aea2337-5d93-4608-b94b-d246c7884c16)
![Screen Shot 2020-09-17 at 1.23.09 PM.png](https://images.zenhubusercontent.com/5ee7da582a6c07a5f569db2e/86c3a8f9-436b-4ce0-bf55-8985ff576ff8)
![Screen Shot 2020-09-17 at 1.26.50 PM.png](https://images.zenhubusercontent.com/5ee7da582a6c07a5f569db2e/65b52c39-cc22-42e6-8936-13a0207346bb)
![Screen Shot 2020-09-17 at 1.36.13 PM.png](https://images.zenhubusercontent.com/5ee7da582a6c07a5f569db2e/77dca6dd-88e7-4e05-b75b-498bd72d7311)

**Comment by marjo-luc** [comment]
Built version 6 che with all updates except workspace changes. Workspace updates should be completed by tomorrow.

**Comment by marjo-luc** [comment]
Changes have been applied to the [dev machine](https://che-k8s.maap.xyz/) and are ready for review.

Please note you may need to clear your cache or view incognito.

**Comment by marjo-luc** [comment]
Changes have been merged to 6.19.6-maap and deployed to the development and production server.
