### ISSUE TITLE
Implement secret management in MAAP

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#1048]
Add support for creating and retrieving user secrets within MAAP for use inside algorithms. Example use case:

```python
maap.secrets.get_secrets()
    [
        {
            "secret_name": "GEE_user"
        }
    ]

maap.secrets.get_secret('GEE_token')
    "GEE_token_value"

maap.secrets.add_secret('new_token', 'new_token_value')
maap.secrets.delete_secret('new_token')
```

Secret values will be stored using symmetric encryption in the MAAP database using the [cryptography](https://pypi.org/project/cryptography) library.

### TODO

- [x] Create MAAP API secrets endpoints.
- [x] Create a new maap-py `secrets` class similar to the `profile` and `aws` classes containing the new methods above.

**Comment by sujen1412** [comment]
Links to https://github.com/MAAP-Project/maap-py/issues/102

**Comment by bsatoriu** [comment]
@marjo-luc the new secrets endpoints are available in DIT. See the four new `/members/self/secrets` operations: https://api.dit.maap-project.org/api/.
