### ISSUE TITLE
Migrate Jupyter extension functionality to MAAP py

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#105]
Generalize and standardize all calls from Jupyter extensions to MAAP py

**Comment by gchang** [comment]
Would be a nice to have.

**Comment by echyam** [comment]
previously already had these implemented:
- Register Algorithm
- Get Job Status
- Get Job Result
- Submit (Execute) Job

added:
- List Algorithms
- Delete Algorithm
- Describe Algorithm
- Get Job Metrics
- Dismiss Job
- Delete Job
- List Jobs

**Comment by echyam** [comment]
I need to set the library to automatically populate the username from profile where needed to avoid accessing other users' job information.

New issue to use the updated library for use in Jupyter extension, to make requests in a uniform way.

**Comment by echyam** [comment]
The `maap-py` library is currently hardcoded to the DEV API domain.  Do we have a way to have it switch for OPS?
