### ISSUE TITLE
EDSC not working in standalone Jupyter

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#108]
From #64

EDSC also not working for me since it needs service to connect to maap cmr, I am not sure we can do it.

**Comment by gchang** [comment]
This is because of the EDSC proxy not being configured to allow iframes from outside of the maap-project.org domain.

**Comment by gchang** [comment]
Look at the edsc url, possibly in the html rewriting.

**Comment by oddes** [comment]
1. Maya pushed the new changes to handle EDSC proxy config. I have tried with the new changes but I still can not open EDSC from standalone Jupyter, it just opens empty new window, no error notification on UI or cmd.

**Comment by oddes** [comment]
I am able to open EDSC from standalone Jupyter. Search parameters not copying to jupyter is part of other tickets so I am closing this:
