### ISSUE TITLE
Integrate GCC Gitlab into GCC Authentication

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#110]
Configure CAS to support the GCC Gitlab

**Comment by bsatoriu** [comment]
I updated the GCC Gitlab and GCC CAS server configuration to support a working GitLab MAAP login integration: https://repo.uat.maap-project.org

I also removed the `Register` tab from the GitLab login page.

**Comment by oddes** [comment]
Works, as expected.
