### ISSUE TITLE
Update Gitlab runner to build Che repo

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#112]
The Che project (https://mas.maap-project.org/root/che) used to build successfully, but now is generating errors related to missing "go" libraries. Here is the error from the runner:

```
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (build-go-sources) on project go-agents: Command execution failed. Cannot run program "go" (in directory "/home/gitlab-runner/builds/x2Ur991q/0/root/che/agents/go-agents/target/go-workspace/src/github.com/eclipse/che/agents/go-agents"): error=2, No such file or directory -> [Help 1]
```

**Comment by bsatoriu** [comment]
I made a few config changes to the JPL Ops GitLab runner to fix the Che CI:

1. Installed Go and added its binaries to the `gitlab-runner` user .profile
2. Installed Java
3. Installed JDK

**Comment by oddes** [comment]
Che Repo is build with no issues.
