### ISSUE TITLE
Unable to submit jobs in DIT

### ISSUE THREAD

**Issue by grallewellyn** [MAAP-Project/ZenHub#1137]
Error message in docker logs:
'/home/ubuntu/repo/register-job'...
remote: HTTP Basic: Access denied. The provided password or token is incorrect or your account has 2FA enabled and you must use a personal access token instead of a password. See https://repo.dit.maap-project.org/help/topics/git/troubleshooting_git#error-on-git-fetch-http-basic-access-denied
fatal: Authentication failed for 'https://repo.dit.maap-project.org/root/register-job.git/'

**Comment by bsatoriu** [comment]
The DIT GitLab settings were updated with the new token values. Jobs and registrations are now confirmed working
