### ISSUE TITLE
Investigate Prometheus for Logging

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#117]
Extension from #73

**Comment by sujen1412** [comment]
So based on reading a few articles and understanding what Prometheus is used for and Logstash is used for, the one line summary is:

"Prometheus is for system and service metrics, monitoring and alerting. Logstash is for Log management."

So using Prometheus for logging may not be the ideal choice, but we could rather use that for monitoring our cluster/ADE for memory free, disk available, etc. 



```
Logstash can be classified as a tool in the "Log Management" category, while Prometheus is grouped under "Monitoring Tools".

Some of the features offered by Logstash are:

Centralize data processing of all types
Normalize varying schema and formats
Quickly extend to custom log formats
On the other hand, Prometheus provides the following key features:

a multi-dimensional data model (timeseries defined by metric name and set of key/value dimensions)
a flexible query language to leverage this dimensionality
no dependency on distributed storage
```
