### ISSUE TITLE
Add Developer" feature is not working in DEV.

### ISSUE THREAD

**Issue by oddes** [MAAP-Project/ZenHub#121]
Users are not populating to add. Please see the attached screenshot.![Screen Shot 2020-07-14 at 5.46.14 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/e344fead-00e0-488e-9c10-0bed280de41b)

**Comment by gchang** [comment]
I'll update this tix so Sri can confirm. I think it's fixed.

**Comment by oddes** [comment]
@gchang , it is working fine now, I am able to add users.

Minor enhancement: 
When I add a single user "Share" button is not enabled until enter a space or comma.
