### ISSUE TITLE
Update handling of username during Job Execution in the API

### ISSUE THREAD

**Issue by NamrataM** [MAAP-Project/ZenHub#122]
Right now the username is passed in as parameter from ADE. But it's not a param for the registered algo. So the username must be removed from the job params submitted and added to the job payload only.

**Comment by NamrataM** [comment]
Removed `username` from the algorithm registration. 
https://github.com/MAAP-Project/maap-api-nasa/commit/f6c6e2f6216132697cb77be0ba882d8cdec67ba6

Updated Job Submission code to add `username` to `job_payload` but not include it in the algorithm's parameters.
https://github.com/MAAP-Project/maap-api-nasa/blob/f6c6e2f6216132697cb77be0ba882d8cdec67ba6/api/utils/hysds_util.py#L308-L312

**Comment by NamrataM** [comment]
To Test:
For Algorithm Registration (notice that `username is not an algorithm param`):
POST https://api.maap.xyz/api/mas/algorithm
```{
	"script_command" : "python3 d3_agb_plant/agb_jaxa.py",
	"repo_url": "https://repo.nasa.maap.xyz/root/d3_agb_plant.git",
	"algorithm_name" : "agb_jaxa_demo_metrics",
	"code_version": "jaxa_analysis",
	"algorithm_description" : "AGB Plant Analysis",
	"environment_name": "ubuntu",
	"docker_container_url": "mas.maap-project.org:5000/root/ade_base_images/plant",
	"algorithm_params" : [
		{
			"field": "granule",
			"download": true
		},
		{
			"field": "clip_upper_bound",
			"download": false
		}
	]
}
```

For Job Submission (notice that `username` is provided as an input to the job.):
POST https://api.maap.xyz/api/dps/job
```<wps:Execute
    xmlns:wps="http://www.opengis.net/wps/2.0"
    xmlns:ows="http://www.opengis.net/ows/2.0"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.opengis.net/wps/2.0 ../wps.xsd" service="WPS"
       version="2.0.0" response="document" mode="sync">
    <ows:Identifier>job-agb_jaxa_demo_metrics_ubuntu:jaxa_analysis</ows:Identifier>
    <wps:Input id="job_type">
        <wps:Data>
            <wps:LiteralValue>
                job-agb_jaxa_demo_metrics_ubuntu:jaxa_analysis
            </wps:LiteralValue>
        </wps:Data>
    </wps:Input>
   <wps:Input id="granule">
        <wps:Data>
            <wps:LiteralValue>https://cumulus-map-internal.s3.amazonaws.com/file-staging/nasa-map/Global_PALSAR2_PALSAR_Mosiac___1/N25E030_17_MOS_F02DAR.tar.gz</wps:LiteralValue>
        </wps:Data>
    </wps:Input>
    <wps:Input id="clip_upper_bound">
        <wps:Data>
            <wps:LiteralValue>-15</wps:LiteralValue>
        </wps:Data>
    </wps:Input>
    <wps:Input id="username">
        <wps:Data>
            <wps:LiteralValue>malarout</wps:LiteralValue>
        </wps:Data>
    </wps:Input>
    <wps:Output id="result" transmission="value"/>
</wps:Execute>
```

For confirmation that job was associated with username and algorithm parameters don't include username:
https://api.maap.xyz/api/dps/job/malarout/list

```
{
  "code": 200,
  "jobs": [
    "['c75c0e43-8a4d-47df-aec5-4fa17c3b6cb2', 'job-completed', 'job-agb_jaxa_demo_metrics_ubuntu:jaxa_analysis', [{'name': 'granule', 'destination': 'localize', 'value': 'https://cumulus-map-internal.s3.amazonaws.com/file-staging/nasa-map/Global_PALSAR2_PALSAR_Mosiac___1/N25E030_17_MOS_F02DAR.tar.gz'}, {'name': 'clip_upper_bound', 'destination': 'positional', 'value': -15}]]"
  ],
  "message": "success"
}
```

**Comment by oddes** [comment]
@NamrataM 
Post DPS job throwing 500 Error: is this working for u?
<html>
   <head>
      <meta content="HTML Tidy for Java (vers. 26 Sep 2004), see www.w3.org" name="generator"/>
      <title>500 Internal Server Error</title>
   </head>
   <body>
      <h1>Internal Server Error</h1>
      <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
   </body>
</html>

**Comment by NamrataM** [comment]
@oddes There was a slight typo while rendering the markdown. Try to copy past that again. I checked and it works.

**Comment by oddes** [comment]
it working as expected.

{
   "code": 200,
   "jobs":    [
      "\"['1fff6051-4c23-487f-b111-99650f6a785c', 'job-completed', 'job-agb_jaxa_demo_metrics_ubuntu:jaxa_analysis', [{'name': 'granule', 'destination': 'localize', 'value': 'https://cumulus-map-internal.s3.amazonaws.com/file-staging/nasa-map/Global_PALSAR2_PALSAR_Mosiac___1/N25E030_17_MOS_F02DAR.tar.gz'}, {'name': 'clip_upper_bound', 'destination': 'positional', 'value': -15}]]\"",
      "\"['fcd57171-5a97-4e2c-a89b-6b2ec9ef511a', 'job-completed', 'job-agb_jaxa_demo_metrics_ubuntu:jaxa_analysis', [{'name': 'granule', 'destination': 'localize', 'value': 'https://cumulus-map-internal.s3.amazonaws.com/file-staging/nasa-map/Global_PALSAR2_PALSAR_Mosiac___1/N25E030_17_MOS_F02DAR.tar.gz'}, {'name': 'clip_upper_bound', 'destination': 'positional', 'value': -15}]]\""
   ],
   "message": "success"
}
