### ISSUE TITLE
Propagate CMR errors to maap-py client

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#131]
When a maap-py CMR function call, such as `searchGranule`, generates an error within CMR, that error needs to be returned within the output of the call, rather than the generic Python exception returned currently.

**Comment by bsatoriu** [comment]
Changing this from 5 to 3 points since it turned out to be a minor fix.

**Comment by oddes** [comment]
Currently, its throwing an error. Looks like the latest version of the maap-py library is not getting to the stack.
Traceback (most recent call last):

  File "/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-2-1e90e4c7aa0c>", line 1, in <module>
    maap.searchGranule(temporal='2018-10-13T00:00:00Z,2018-10-19T23:59:59Z,30,60', collection_concept_id="C1200116818-NASA_MAAP")

  File "/opt/conda/lib/python3.7/site-packages/maapPy-0.2.0-py3.7.egg/maap/maap.py", line 100, in searchGranule
    results = self._CMR.get_search_results(url=self._SEARCH_GRANULE_URL, limit=limit, **kwargs)

  File "/opt/conda/lib/python3.7/site-packages/maapPy-0.2.0-py3.7.egg/maap/utils/CMR.py", line 39, in get_search_results
    page = ET.XML(unparsed_page)

  File "/opt/conda/lib/python3.7/xml/etree/ElementTree.py", line 1315, in XML
    parser.feed(text)

  File "<string>", line unknown
ParseError: syntax error: line 1, column 0

**Comment by bsatoriu** [comment]
@oddes the reason for this generic error is the workspace image you were using is a few months old. In order to test this story please use the `master` version of one of the MAAP images. For example, to use the latest plant image, perform the following steps:

1. Open the Workspaces page, and click on the settings button for the workspace you want to test.
2. Stop the workspace if it is running.
3. In the "Config" tab, set the "image" value to the plant:master version as shown here: `image: 'mas.maap-project.org:5000/root/jupyter_image/plant:master`
4. Open the workspace. 
5. Note the output seen in the attached screenshot. At the bottom of the error message from an invalid `searchGranule` call, you should see a CMR message like "ValueError: Bad search response: <?xml version="1.0" encoding="UTF-8"?><errors><error>Collection-concept-id [C1] is not valid.</error></errors>"

![Screen Shot 2020-08-25 at 1 16 25 PM](https://user-images.githubusercontent.com/27687558/91223457-7dba3800-e6d5-11ea-835a-48d3efa53af5.png)

**Comment by oddes** [comment]
@bsatoriu @gchang 
I have noted couple of issues when I was testing. not sure we can go ahead and accept this? Please advise:

1. It does not works for the collection search. When I specify the wrong collection_concept id
  eg:  maap.searchCollection(concept_id="C1200115768-NASA_", instrument_h="LIDAR", limit=10)
whereas it works fine and propagates error when concept_id="C1", which means we are not looking for the exact lookup.

2. Similarly, not works for the Granule Search.

eg: maap.searchGranule(concept_id="C1200115768-NASA", limit=10)
whereas it works fine and propagates error when concept_id="C1" in the above scenario.

**Comment by bsatoriu** [comment]
Here is the CMR response from the call in your first example:

```xml
'<?xml version="1.0" encoding="UTF-8"?><results><hits>0</hits><took>3</took></results>'
```

Given that the CMR is returning a status code of 200, I think the maap-py library is correct in returning an empty array here. Using your "C1" input for concept_id, I think CMR returns an error because the format is invalid. I propose we consider this a CMR behavior and not a bug in maap-py.

Here is another example of error propagation using a different violation:

`searchCollection(concept_id="C1200115768-NASA_", brian="LIDAR", limit=10)`

Yields:

`ValueError: Bad search response: <?xml version="1.0" encoding="UTF-8"?><errors><error>Parameter [brian] was not recognized.</error></errors>`

**Comment by oddes** [comment]
@bsatoriu 
Based on your comment. since its not an issue with maap-py, closing it.
