### ISSUE TITLE
Fix maap-py imports to support CLI invocation

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#132]
When running the maap-py library from the CLI using `python maap/maap.py`, a ModuleNotFound error is generated. Fix the file imports and to prevent this error. 

Testing notes:
- Ensure that importing the maap-py package and executing maap.searchGranule() still works without errors.
- Verify that the `python maap/maap.py` command can be run successfully.

**Comment by gchang** [comment]
Look to see this can be closed. We can use MAAP py in DPS jobs, so that may show that we can run it via CLI.

**Comment by gchang** [comment]
This is still valid and open.

**Comment by gchang** [comment]
Not certain about context, will create a new tix if error occurs again.
