### ISSUE TITLE
MAS & DPS API endpoints documentation

### ISSUE THREAD

**Issue by NamrataM** [MAAP-Project/ZenHub#135]
Create documentation of expected request body and responses on pass / fail for the MAS and DPS endpoints of the MAAP API.

**Comment by NamrataM** [comment]
https://docs.google.com/document/d/11rNnaQ2N2GEipjTAG66qhE2shaFCuM5iS0RVG_JZrM8/edit?usp=sharing

**Comment by oddes** [comment]
Thanks for the Update.
