### ISSUE TITLE
Provide support for user to configure disk space and memory requirements for a job 

### ISSUE THREAD

**Issue by sujen1412** [MAAP-Project/ZenHub#136]
Currently, the user has a fixed template for a job in terms of resources. 
5gb disk space and ~5GB RAM. This can be limiting in large image processing jobs performing terrain corrections for eg. 

We should allow the user to specify something in the algorithm config like 
```
# Provide value in GB
disk_space: 
  - 10
# Choose an upper limit from 7, 15, 30 (GB)
memory: 
  - 15
```

These should be optional and if none are specified the current defaults should be used.

**Comment by NamrataM** [comment]
Based on https://hysds-core.atlassian.net/wiki/spaces/HYS/pages/199787836/Job+and+HySDS+IO+Specifications I can facilitate specifying the disk space. In other projects we have been dealing with memory requirements by choosing the instance type the job should run on. So for memory specification we may need to discuss a solution that involves the user choosing what instance type to use.

**Comment by NamrataM** [comment]
Should we also expose the soft and hard time limits? The creators of the algorithm would know how long these jobs should run.

**Comment by NamrataM** [comment]
Added support for specifying disk space usage: https://github.com/MAAP-Project/maap-api-nasa/commit/0f00e94b0ba6006a5874b49b22c48bb90decea85

**Comment by NamrataM** [comment]
For supporting memory specifications, we will be leveraging the list of available workers (name includes available memory of worker e.g. maap-worker-8gb). Added an endpoint `/mas/algorithm/resource` to the MAAP API . It queries the `/queue/list` endpoint of the Mozart API to get the list of registered queues that algorithms can run on.

The output of the `/mas/algorithm/resource` is:
`{
  "code": 200,
  "message": "success",
  "queues": [
    "maap-worker-8gb"
  ]
}
`
The plan is to make the GET request to `/mas/algorithm/resource` and let the user chose one at the algorithm registration step. This would not be in the algorithm config file as suggested in the description. Instead the pre-populated algorithm registration form(screen shot) will have a drop down with the resources options.![Screen Shot 2020-08-31 at 10.57.34 AM.png](https://images.zenhubusercontent.com/5eebbe7ef0b8f079c923d734/3c677797-3551-4f7d-92d9-7f7e843c12fa)

**Comment by gchang** [comment]
@echyam @NamrataM Need to add testing procedure

**Comment by echyam** [comment]
I added the queue options in a branch.  Is disk space flexible yet? or just a proposal? @NamrataM

**Comment by echyam** [comment]
Added new dropdown within registration modal to select DPS queue (specifies memory):
![image](https://user-images.githubusercontent.com/11476825/93942809-0385cf00-fce6-11ea-9d31-5b75c9385a19.png)

**Comment by oddes** [comment]
Currently, it shows only one option but m![Screen Shot 2020-09-22 at 5.08.04 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/e7c3e9d2-2d3b-4cd9-8170-047b552ec047)emory Drop-down field is showing as expected
