### ISSUE TITLE
Release new image/stacks to users

### ISSUE THREAD

**Issue by mayadebellis** [MAAP-Project/ZenHub#145]
We have a lot of stored up changes that would be good to roll out! Using our new deployment pipeline w tagging the repo and creating a change log. Will be hopefully quick in the future but I think for the first one Liz and I should both be involved so we are in agreement and both know how to do it (and document it)

**Comment by gchang** [comment]
@bsatoriu To create new proxy for new EDSC on 30052. @mayadebellis to update stack to point to new 30052 port.
