### ISSUE TITLE
Integrate 3D Tiles into Common Mapping Client

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#147]
MSFC is creating derivative products/ARDS in the 3D tiles format. The Cesium client within CMC should be able to render those natively. Need to verify the capability to add 3D tiles and possibly update our CMC widgets, such as the layer viewer, to show 3D tiles "layers."

**Comment by gchang** [comment]
While we're waiting for the endpoints and API calls, can look at using public 3D tiles datasets to envision on that could be done.

**Comment by bsatoriu** [comment]
@mayadebellis the new 3d tile endpoint is ready now on the dev api--see the "3d tiles" section with example API calls:

https://api.maap.xyz/api/

**Comment by abarciauskas-bgse** [comment]
I have created a new deployment which required a change to the MAAP API configuration, opened a PR https://github.com/MAAP-Project/maap-api-nasa/pull/14 cc @mayadebellis @bsatoriu

**Comment by oddes** [comment]
@mayadebellis 
When u get a chance could u please update the instructions to test.

**Comment by mayadebellis** [comment]
@oddes 
Here are the steps:
- On ade.maap-project.org open a stable workspace
- Launch a python notebook
- Click the MAAP Button to import the default packages, specifically ipycmc
- Run the cell
- Run `w.load_layer_config("https://cmr.maap-project.org/search/concepts/G1200354094-NASA_MAAP.json", "json", {"handleAs": "vector-3d-tile"})`
- In ipycmc switch to the 3D map view.
- You will see the layer load over peru

![image.png](https://images.zenhubusercontent.com/5ee967d942152fe068604fa1/5261d6d8-2337-4591-85b4-f1b1f7e1fb00)

**Comment by oddes** [comment]
Thanks Maya. works as expected.
