### ISSUE TITLE
Implement 3D tiles capability into MAAP API

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#148]
Need to update the MAAP API to support the 3D tiles endpoints. Will need to work with @abarciauskas-bgse to understand what needs to be done.

**Comment by gchang** [comment]
I envision this to be another passthrough to CMR

**Comment by abarciauskas-bgse** [comment]
Thanks for tagging @gchang - we are still working through the automated API gateway deployment and integration with MAAP API but here's some intermediate progress that could help:

* Example endpoint response: https://jtovpjptc7.execute-api.us-east-1.amazonaws.com/dev/3d-tiles/cumulus/ATL08_ARD-peru___003/ept/ept-tileset/tileset.json
* Example metadata record: https://cmr.maap-project.org/search/concepts/G1200235888-NASA_MAAP.json. Note the `(GET 3DTILES)` and `(GET WFS CAPABILITIES)` are not intended to be operational yet. The endpoints there will "pass thru" to our automated API gateway deployment of services.

Will update this ticket once we have our API gateway deployment operational.

**Comment by abarciauskas-bgse** [comment]
There are 2 endpoints currently deployed which need to go behind a parameterized http://api.maap-project.org/3d-tiles:

* https://jnz40d89g6.execute-api.us-east-1.amazonaws.com/test/file-staging/nasa-map/ATL08_ARD-beta___001/afrisar/ept/ept-tileset/tileset.json and
* https://jnz40d89g6.execute-api.us-east-1.amazonaws.com/test/file-staging/nasa-map/ATL08_ARD-beta___001/peru/ept/ept-tileset/tileset.json

My current thinking is that the API will accept requests of the form:

* https://api.maap-project.org/3d-tiles/ATL08_ARD-beta___001/afrisar/ept-tiles/tileset.json
* https://api.maap-project.org/3d-tiles/ATL08_ARD-beta___001/peru/ept-tiles/tileset.json

so we probably want configuration options for the api gateway
```
maap_data_system_services_api_base=https://jnz40d89g6.execute-api.us-east-1.amazonaws.com/test
maap_data_system_files_path=file-staging/nasa-map
```
And the api code could be a simple pass through using those configuration values - does that make sense @bsatoriu ?

**Comment by bsatoriu** [comment]
@abarciauskas-bgse this new endpoint is now up and running on our dev server:

https://api.maap.xyz/api/3d-tiles/ATL08_ARD-beta___001/afrisar/ept/ept-tileset/tileset.json
https://api.maap.xyz/api/3d-tiles/ATL08_ARD-beta___001/peru/ept/ept-tileset/tileset.json

**Comment by abarciauskas-bgse** [comment]
Thanks @bsatoriu that's awesome!

A few follow up questions:

* I usually check this is working using cesium, but when making a request to http://cesium.entwine.io/?url=https://api.maap.xyz/api/3d-tiles/ATL08_ARD-beta___001/afrisar/ept/ept-tileset/tileset.json

I'm getting the following error:
```
Access to XMLHttpRequest at 'https://api.maap.xyz/api/3d-tiles/ATL08_ARD-beta___001/afrisar/ept/ept-tileset/tileset.json' from origin 'http://cesium.entwine.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

This is a working example: 
http://cesium.entwine.io/?url=https://jnz40d89g6.execute-api.us-east-1.amazonaws.com/test/file-staging/nasa-map/ATL08_ARD-beta___001/afrisar/ept/ept-tileset/tileset.json

Is it possible to change the CORS policy / header for the API?

* @gchang do you know how we can check the 3d integration with CMC?

**Comment by gchang** [comment]
@mayadebellis is looking at the 3d tiles integration with CMC. Having the example will help!

**Comment by bsatoriu** [comment]
@abarciauskas-bgse I opened up the CORS policy for the new endpoint. Looks like we have tiles now: http://cesium.entwine.io/?url=https://api.maap.xyz/api/3d-tiles/ATL08_ARD-beta___001/afrisar/ept/ept-tileset/tileset.json

**Comment by abarciauskas-bgse** [comment]
Super updates thanks @bsatoriu @gchang @mayadebellis !

**Comment by oddes** [comment]
Tiles are loading as expected.
