### ISSUE TITLE
Tutorial notebooks to introduce users to ADE functionality

### ISSUE THREAD

**Issue by echyam** [MAAP-Project/ZenHub#151]

**Comment by echyam** [comment]
Some tutorial notebooks written for MAS, DPS, Remote Access, Notebook Magics. 
Notebooks are currently stored in my s3-backed folder in the dev environment `s3://maap-dev-dataset/eyam/tutorials`.  Maybe we should move them to a public repo on the OPS GitLab.

**Comment by echyam** [comment]
notebooks moved to public repo on GitLab at:
https://repo.nasa.maap.xyz/maap-devs/maap-tutorials

**Comment by oddes** [comment]
@echyam  Notebooks looks nice. When I am following exact steps mentioned in notebooks, I am getting some errors.

eg: List Jobs fails with the following error: whereas same works fine when I use the menu links. Looks like some command issues. I want to go over the list of issues with you tomorrow so we can resolve and close the issue.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-a61a76679b15> in <module>
----> 1 response = maap.listJobs('sodde')
      2 json_response = json.loads(response.text)
      3 json_response

AttributeError: 'MAAP' object has no attribute 'listJobs'

**Comment by oddes** [comment]
Looks good now after updating maap-py library.
