### ISSUE TITLE
Fix 403 error when some users call protected maap api endpoints

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#153]
Liz reported receiving a 403 error when making the following maap-py call from the ADE:

```python
r = requests.get(
    url="https://api.maap.xyz/api/members/self",
    headers=maap._get_api_header()
)
```

However, I am able to make the same call successfully. Furthermore, I'm getting disparate results with the following MAAP images:

1. mas.maap-project.org:5000/root/jupyter_image/vanilla:develop (403 error)
2. mas.maap-project.org:5000/root/jupyter_image/plant:latest (200 success)

**Comment by oddes** [comment]
I have tried this in OPS environment. I am getting success response (200).

import requests
r = requests.get(
    url="https://api.ops.maap-project.org/api/members/self",
    headers=maap._get_api_header()
)
r

Please see attached.

![Screen Shot 2021-05-31 at 10.04.24 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/c8e135bb-c9cf-4ed8-9c2f-7c79ac392fcc)
