### ISSUE TITLE
Add support for proxy tickets in shared ADE workspaces

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#154]
**Is your feature request related to a problem? Please describe.**
When making MAAP API calls from an ADE workspace, the Jupyterlab stacks rely on an env variable containing the MAAP proxy token. This is problematic for shared workspaces, where users can make MAAP API requests using the original workspace creator's identity.

**Describe the solution you'd like**
Replace the proxy token env variable with the keycloak attributes endpoint, so that the ADE will pickup the correct proxy ticket assigned to the user initiating MAAP API calls, rather than the ticket first instantiated during workspace startup.

**Additional context**
This change will require a small modification to the Jupyterlab MAAP extension, as well as a change to the maap-py library, to make a Keycloak request, rather than simply referencing the env variable containing the proxy ticket. Consider adding a new UserAttributes class to maap-py that is responsible for retrieving user info from the parent context, whether that be ADE or a local jupyterlab server outside of ADE.

**Comment by gchang** [comment]
@bsatoriu will comment. Issue seems to be closed.

**Comment by oddes** [comment]
working as expected. Please see the proxy token.
![Screen Shot 2021-05-25 at 12.47.25 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/ff531cae-75d2-4e1e-8a3b-13f9f432b4e0)
