### ISSUE TITLE
Add `demo-${username}` to tutorial algo name

### ISSUE THREAD

**Issue by echyam** [MAAP-Project/ZenHub#159]
automatically a demo-username prefix to tutorial algos to avoid clobbering and for easy delete

**Comment by oddes** [comment]
Add demo to username is not happening. Please see the attached screenshot:
![Screen Shot 2020-09-22 at 5.08.04 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/6e62ef6a-5f1f-48dd-a523-f1ed5c89494f)

**Comment by echyam** [comment]
updated regex to allow URL to include git auth key
![image](https://user-images.githubusercontent.com/11476825/94615529-ca58dc00-025c-11eb-8fe8-43fd3962f8ea.png)

**Comment by oddes** [comment]
Working fine. Please see attached screenshot.

 ![Screen Shot 2020-09-30 at 5.43.10 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/f1b9c2ad-cb11-412a-8431-d399bf2cd20e)
