### ISSUE TITLE
Investigate signed s3 urls in the GCC ADE environment

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#161]
Options for supporting signed s3 urls in GCC include requesting a permanent access key for s3 only, or figure out another alternative given the GCC environment doesn't currently use access keys.

**Comment by gchang** [comment]
@bsatoriu I think this is done, right?

**Comment by bsatoriu** [comment]
@gchang yes, I moved the signed s3 url logic from the ADE to the MAAP API, and it's working now in GCC and JPL environments. These are the primary changes:

API: https://github.com/MAAP-Project/maap-api-nasa/commit/0366788cb0c2d409f742ed9ab967d5fe3d9ed622
ADE: https://github.com/MAAP-Project/maap-jupyter-ide/commit/363756ae297134e79b910e7e5caee1a3fe1a33fe
