### ISSUE TITLE
algorithms list is not showing from DPS Jobs UI 

### ISSUE THREAD

**Issue by oddes** [MAAP-Project/ZenHub#165]
Steps to Reproduce:
1. Open the workspace
2. Select DPS Jobs UI from "DPS UI Menu", you will notice the algorithms list is not showing from DPS Jobs UI, as shown in attached screen shot.

![Screen Shot 2020-09-03 at 1.53.09 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/8634eb8d-7d74-4118-be6b-6b6c951eb900)
When u select the DPS Jobs UI from "DPS UI Menu" second time it is showing.

**Comment by gchang** [comment]
@oddes  The algorithm list is available in the DPS/MAS Operations -> List Algorithms. Were you expecting something different?

**Comment by oddes** [comment]
@gchang 
It is working fine now. Earlier it used to be loaded only when open twice: closing the issue:

Steps:
1. Select the DPS Jobs UI from "DPS UI Menu", you will not see any algorithms list 
2. Try again the same step 1, second time it is showing.

**Comment by oddes** [comment]
Looks like it is intermittent. Please see the screen shot. Here are the steps to reproduce the issue in DEV Environment:

 Steps:
1. Select the DPS Jobs UI from "DPS UI Menu", you will not see any algorithms list [As shown in the attached screen shot]
2. Try again the same step 1, you will notice the algorithms list.

![Screen Shot 2020-11-01 at 10.02.16 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/b217f68e-c33e-448b-9eaa-ba90070ab87e)

**Comment by gchang** [comment]
@mayadebellis Determine whether this plugin is still working and what needs to be fixed.

**Comment by mayadebellis** [comment]
I think what is happening is that there is a request that isn't being waited for somewhere but never got the chance to figure out which one. I think one of the funcs that makes the calls to get all this info on application start needs to be awaited/in a promise. It works the second time because that info has already been cached
