### ISSUE TITLE
Add MAAP proxy ticket to all ADE -> API calls

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#166]
Any ADE calls to the MAAP API should include a token identifying the user who originated the call, either via the maap-py library, DPS chained jobs or direct calls from the ADE UI. Currently, the proxy ticket is only being included for DPS calls and the MAAP login.

**Comment by gchang** [comment]
@bsatoriu to review and test. Could be fixed.

**Comment by oddes** [comment]
works as expected, as shown below, proxy token is populated:

![Screen Shot 2021-05-25 at 12.47.25 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/cad41b26-7703-4240-839e-64093c868fab)
