### ISSUE TITLE
Remove unused options in Jupyterlab

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#173]
Clean up options that aren't implemented/used. This includes options in:

- [ ] Jupyterlab left tabs
- [ ] Jupyterlab menu items
- [ ] Jupyterlab file browser, right-click popup
- [ ] The main menu (top)

**Comment by echyam** [comment]
Workaround for left panels from https://stackoverflow.com/questions/54640350/jupyter-lab-hide-vertical-navigation-pane/54694800
> While this feature is not added, what you can do is to write a small browser extension to execute this code on every notebook server (in the onDOMContentLoaded event):
e.g. Remove entire toolbar of left panels (or select specific tabs to remove)
```
const leftSidebar = document.querySelector('.jp-SideBar')
document.querySelector('#jp-main-content-panel').removeChild(leftSidebar)
```

**Comment by echyam** [comment]
remove extension manager tab by running this in the ADE Dockerfile:
` jupyter labextension disable @jupyterlab/extensionmanager-extension`

**Comment by gchang** [comment]
Given the code "freeze" for next week, let's look to deploy this afterwards.
