### ISSUE TITLE
Running ADE on TEST (GCC) with DPS on DEV (JPL)

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#177]
Since we don't have the ability to create AMIs in GCC, we can't use the automated deployment of the DPS. For D2 as a fallback plan, I'd like to run as much as we can on TEST with DPS jobs running on DEV. Need to figure out what needs to be connected to do so.

Some things:
- [ ] Image builds in TEST Gitlab and pulls from DEV DPS
- [x] S3 mounts in ADE on TEST, but points to JPL/DEV bucket

**Comment by bsatoriu** [comment]
@gchang the UAT ADE workspace mounts are now pointing to the `maap-uat-dataset` bucket in the JPL account. This is achieved, for now, by the continued use of our AWS credential file. 

I tested the org bucket and user bucket mounting on UAT with our `develop`-tagged stacks.

**Comment by gchang** [comment]
I was talking to "someone" briefly this morning and he mentioned that it may be easier to have DPS push to the GCC bucket. To discuss.

**Comment by gchang** [comment]
For D2, we're going to be doing it all from JPL as that's the most vetted environment.
