### ISSUE TITLE
Migrate CAS stylesheets to UAT

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#179]
The CAS system on UAT is still using the default CAS log in. Can verify with the UAT portal login.

**Comment by bsatoriu** [comment]
I updated the UAT CAS UI and added @marjo-luc 's latest code to our CAS overlay template: https://github.com/MAAP-Project/maap-auth-cas/commit/22988cbf16de3d449c0f5c2fbb375e533993bc8b
