### ISSUE TITLE
Git sync functionality not working

### ISSUE THREAD

**Issue by pahbs** [MAAP-Project/ZenHub#180]
**Describe the bug**
Basic Git add, commit, push, pull, status functionality seems to be not working as expected:

**To Reproduce**
(GEDIPY) root@workspacehwfg7pmy64t3ycyr:/projects/jabba/code/icesat2# git pull
error: bad index file sha1 signature
fatal: index file corrupt
(GEDIPY) root@workspacehwfg7pmy64t3ycyr:/projects/jabba/code/icesat2# git status
error: bad index file sha1 signature
fatal: index file corrupt

**Expected behavior**
Unable to push new code to github repo

**Screenshots**
n/a

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gchang** [comment]
@echyam Could this be an issue with working with data on the s3 mount?

**Comment by pahbs** [comment]
Hi all - has there been any progress towards understanding this issue? I see it is still happening, which means I cannot pull or push any code from any GitHub repo.

**Comment by echyam** [comment]
I tried pushing and pulling with a repository outside of the s3-backed folder, and it worked fine.
This seems to be happening if the repository is within your S3 bucket, in which case I'm seeing an error with the git config. Looking into how to solve that one.

**Comment by bsatoriu** [comment]
@pahbs this issue comes up occasionally when cloning repos inside of your user folder. To resolve this issue, repair the corrupted git index file by running the following commands:

```
cd ~/jabba/code/icesat2
rm -f .git/index
git reset
```

All of your commits and un-staged changes will NOT be affected by running these commands. We are looking at long term solutions for preventing this issue in a future update.

**Comment by pahbs** [comment]
@bsatoriu it seems the the problem re-emerges after doing this reset:

(GEDIPY) root@workspacehwfg7pmy64t3ycyr:/projects/jabba/code/icesat2_boreal# 
(GEDIPY) root@workspacehwfg7pmy64t3ycyr:/projects/jabba/code/icesat2_boreal# rm -f .git/index
(GEDIPY) root@workspacehwfg7pmy64t3ycyr:/projects/jabba/code/icesat2_boreal# git reset
Unstaged changes after reset:
M       notebooks/1.Reference product creation/.ipynb_checkpoints/1.3 Reference map production (LVIS) - R - PM, JA, LD, CS-checkpoint.ipynb
M       notebooks/1.Reference product creation/1.3 Reference map production (LVIS) - R - PM, JA, LD, CS.ipynb
(GEDIPY) root@workspacehwfg7pmy64t3ycyr:/projects/jabba/code/icesat2_boreal# git add notebooks/1.Reference\ product\ creation/1.3\ Reference\ map\ production\ \(LVIS\)\ -\ R\ -\ PM\,\ JA\,\ LD\,\ CS.ipynb 
(GEDIPY) root@workspacehwfg7pmy64t3ycyr:/projects/jabba/code/icesat2_boreal# git commit -m 'draft 1.3 nb for LVIS gridding'                         On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
        modified:   notebooks/1.Reference product creation/.ipynb_checkpoints/1.3 Reference map production (LVIS) - R - PM, JA, LD, CS-checkpoint.ipynb
        modified:   notebooks/1.Reference product creation/1.3 Reference map production (LVIS) - R - PM, JA, LD, CS.ipynb

no changes added to commit
(GEDIPY) root@workspacehwfg7pmy64t3ycyr:/projects/jabba/code/icesat2_boreal# git diff --cached --name-only --diff-filter=A
error: bad index file sha1 signature
fatal: index file corrupt
(GEDIPY) root@workspacehwfg7pmy64t3ycyr:/projects/jabba/code/icesat2_boreal# git add notebooks/1.Reference\ product\ creation/1.3\ Reference\ map\ production\ \(LVIS\)\ -\ R\ -\ PM\,\ JA\,\ LD\,\ CS.ipynb 
error: bad index file sha1 signature
fatal: index file corrupt
(GEDIPY) root@workspacehwfg7pmy64t3ycyr:/projects/jabba/code/icesat2_boreal#

**Comment by bsatoriu** [comment]
@pahbs thanks for following up, and sorry for the continued difficulty. I'm investigating your s3 folder to determine if there are other corrupt .git data that might also need repair. I'll follow up today once I get this resolved.

**Comment by bsatoriu** [comment]
@pahbs I'm still investigating this error, and need a bit more time to get it resolved. I will follow up again tomorrow as soon as I'm done. 

On a side note, I noticed the repo you referenced in your most recent comment belongs to `wksp-paul`, which uses a deprecated image. Once this issue is figured out, I'd like to copy your repos to the new storage location we are using and upgrade your workspace to the latest version.

**Comment by bsatoriu** [comment]
@pahbs I've copied your workspace files to our new s3 bucket and remounted your workspace folder. I ran a few tests with no errors. Please try resuming with your updates and let me know if you run into any problems.

**Comment by pahbs** [comment]
@bsatoriu ok, thank you, but now I get this: 

(base) root@workspacerd5inpaxhmxbo3wp:~/jabba/code/icesat2_boreal# git add notebooks/1.Reference\ product\ creation/1.3\ Reference\ map\ production\ \(LVIS\)\ -\ R\ -\ PM\,\ JA\,\ LD\,\ CS.ipynb 
fatal: Unable to create '/projects/jabba/code/icesat2_boreal/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
(base) root@workspacerd5inpaxhmxbo3wp:~/jabba/code/icesat2_boreal# rm -f .git/index
(base) root@workspacerd5inpaxhmxbo3wp:~/jabba/code/icesat2_boreal# git reset
fatal: Unable to create '/projects/jabba/code/icesat2_boreal/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
(base) root@workspacerd5inpaxhmxbo3wp:~/jabba/code/icesat2_boreal#

**Comment by bsatoriu** [comment]
This is the s3fs git issue Liz opened up: https://github.com/s3fs-fuse/s3fs-fuse/issues/1152

While we continue to investigate this issue, the recommended workaround is to perform git operations *outside* of your user directory.  As an example, move or clone your repo into the `/projects` in your workspace, which is outside of your user directory.

**Comment by gchang** [comment]
Closing issue as there's a workaround right now. Will continue to monitor with ticket #222
