### ISSUE TITLE
ADE users cannot contribute to external Github repos

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#183]
From Laura D:

> We’re seeing an issue with github. We want to clone an external git repo, and then commit changes or push back to github.com
> 
> This seems pretty fundamental - we don’t want to be limited to the Gitlab because we are collaborating with researchers both within and outside the MAAP. Is there are solution here?

Steps to reproduce:

1. Create a new workspace that includes a `git` project pointing to a Github.com repo
2. Make a change to the repo, and commit.
3. Push the repo using the UI of the Git plugin.

Result: fatal error as shown in the attached 
![Screen Shot 2020-09-29 at 1 04 50 PM](https://user-images.githubusercontent.com/27687558/94610725-90d0a280-0255-11eb-99ea-903771b5c56d.png)
screenshot

**Comment by gchang** [comment]
This is a dupe.
