### ISSUE TITLE
Create and update new table "member_algo_registration"

### ISSUE THREAD

**Issue by NamrataM** [MAAP-Project/ZenHub#187]
On Algorithm registration,
It would have the following fields:
member id
algorithm_key
creation_datetime
commit_hash
ade_webhook
username
email

On every git commit and push, add a record to the table and store the commit hash and ADE webhook URL to send registration updates back to ADE.

On receiving CI build job updates, 
if job succeeds, add record to the "member_algorithm" table
if job fails, don't add record.

**Comment by gchang** [comment]
Obsolete, new tix will be created.

**Comment by gchang** [comment]
Obsolete, new tix will be created.
