### ISSUE TITLE
Failed to get user's Che orgs

### ISSUE THREAD

**Issue by oddes** [MAAP-Project/ZenHub#188]
Unable to get user's Che orgs when we open ADE.

**Comment by oddes** [comment]
Steps:
1. Open ADE Environment in DEV
2. You will notice the error:  "Failed to get user's Che orgs" and as a result, user unable to see maap-users folder

**Comment by oddes** [comment]
@bsatoriu 
Do u guys have any update on this?

**Comment by gchang** [comment]
@oddes Do you still see this issue with the new stacks that were pushed out this week?

**Comment by oddes** [comment]
@gchang 
I am still having the issue in DEV environment.  Please see the attached screenshot with failed to get user Che Orgs

![Screen Shot 2020-11-03 at 11.14.31 AM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/e423865d-1768-4dc4-aa9a-7c9d72f07b73)

**Comment by oddes** [comment]
@gchang  and @bsatoriu 
Actually, this is working fine with some of the developer branch stacks

**Comment by gchang** [comment]
Will close this. I believe there's an issue upstream with people being removed from organizations, which is listed in #221
