### ISSUE TITLE
Add versioning to the MAAP API repositories

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#190]
The MAAP API and maap-py libraries would benefit from version tags that align with MAAP as a whole. A common version across the MAAP API repositories and Jupyterlab extensions should simplify testing and CI/CD processes.

I propose using the same numbering as https://github.com/MAAP-Project/maap-jupyter-ide

- [x] Add a version and changelog to MAAP API right now, set version .8. At delivery, it will be 1.0.
- [x] Add a version and changelog to MAAP-py right now, set version at .8 At delivery, it will be 1.0.

For the jupyter extensions, use the existing versioning scheme. By delivery, that will be bumped to 3.0

**Comment by gchang** [comment]
We'll call the release at delivery (end of Feb) to be v1.0. In the meantime, specify a <1.0 version number to the various components.
