### ISSUE TITLE
Install r-rgdal and sf in R images

### ISSUE THREAD

**Issue by mayadebellis** [MAAP-Project/ZenHub#193]
Was on a call with Laura and others trying to get these packages working because they need them for their code. Was able to create a new conda environment within the workspace with the packages working!!

Current work around:
- Run `source activate test-r-packages`
- Run code in the terminal instead of in the notebook

Next steps:

- [ ] Get kernel/jupyter to use the new conda environment
- [ ] Install packages in the base image. I think it will show up in jupyter as a second R kernel

**Comment by mayadebellis** [comment]
Can get both sf and rgdal to work in the terminal and the notebook kernel OR notebook kernel works but only rgdal works and not sf

**Comment by mayadebellis** [comment]
Updated instructions for testing:

- Open workspace with stack pointing at `mas.maap-project.org:5000/root/jupyter_image/r-with-gdal:stable`

- Create new conda environment. For example: `conda create --name <name> -c conda-forge -c r gdal r-rgdal r-sf r-irkernel --yes`
- Must have r-irkernel to create R kernel from the environment

**Comment by gchang** [comment]
Try adding `apt-get install libxt-dev` into the workspace and restart the notebook.

**Comment by mayadebellis** [comment]
Shared workspace with laura to validate. If all is good will update generic r image

**Comment by mayadebellis** [comment]
Updated generic R stack to have gdal and sf packages. Available to all users
