### ISSUE TITLE
algorithm_config.yaml file is getting overwritten during registration

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#194]
When the submit_jobs extension was updated to use the new queue selection menu, a bug was introduced that causes the inputs section of the file to be altered, preventing any successful registrations that include inputs. See https://github.com/MAAP-Project/maap-jupyter-ide/blob/develop/submit_jobs/submit_jobs/handlers.py#L147

**Comment by gchang** [comment]
This is still valid and open. This was opened b/c something wasn't working during the f2f demo.

**Comment by gchang** [comment]
Outdated and solved by new process.
