### ISSUE TITLE
MAAP basic can't open Terminal

### ISSUE THREAD

**Issue by lauraduncanson** [MAAP-Project/ZenHub#200]
**Describe the bug**
In a new MAAP Basic workspace (gedi-test-py-basic) Terminal will not open, gives Launcher error: Invalid Response 404

**To Reproduce**

**Expected behavior**
Terminal was expected to open

**Screenshots**

**Desktop (please complete the following information):**
iOS, Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gchang** [comment]
This has been identified and fixed. We updated Jupyter versions and there was a change that broke our workaround to get it working under Che. Will do some more tests tomorrow and push it out.
