### ISSUE TITLE
Install packages to vanilla image for superdemo

### ISSUE THREAD

**Issue by mayadebellis** [MAAP-Project/ZenHub#202]
Request from Laura:
Hi Brian and Maya - for the superdemo we are using some software called gedipy that
UWG member John Armston developed. It has a bunch of python dependencies that we couldn’t get working in an R workspace, but it’s all python so we got it running in a plant workspace, but needed to install the following

What we had to install for gedipy on the MAAP Basic Stack:
```
conda install -c conda-forge numba
conda install -c conda-forge/label/cf202003 pygeos
conda install -c conda-forge/label/cf202003 pyproj
conda update -c conda-forge pyproj
conda install -c conda-forge rasterio

```
we’d like to do a dps job with gedipy but of course we’d need these in the base image of plant (or similar in a different image, but this is where we tested because we had issues with the other workspaces; python 2 in isce, terminal window wasn’t launching in MAAP Basic, etc.)

**Comment by mayadebellis** [comment]
To test:
Open plant stable workspace. In notebook:
```
import rasterio
import numba
import pygeos
import pyproj
```
If it all imports then it worked!

**Comment by oddes** [comment]
@mayadebellis 

Followed the test instruction in DEV environment. I am getting the module not found errors: Do we have any specific build for this?
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-350e27267e59> in <module>
----> 1 import rasterio

ModuleNotFoundError: No module named 'rasterio'

**Comment by mayadebellis** [comment]
Hi Sri - This ticket actually changed slightly and I forgot to update the name! These packages were installed in the MAAP Basic Stable image instead of plant. I think this should also be tested in the Ops environment.

**Comment by oddes** [comment]
Verified. I can successfully import packages in OPS environment for the MAAP Basic Stable image.
