### ISSUE TITLE
Add packages to Nathan's workspace/image

### ISSUE THREAD

**Issue by mayadebellis** [MAAP-Project/ZenHub#203]
Sent an email back to clarify the urgency and whether this needs to be in his custom image or if it will be sufficient to add it to Basic or Plant.

Hi Maya,
 
I know this is a call back to a while ago, but I wanted to check if it were possible to make a quick request. I was having some issues creating my own dockerfile but I think we can resolve that later.
 
A while ago you built me a custom workspace that had a piece of software called rsgislib in it. At the time the builds were broken so while you were able to provide it, it wouldn’t work on the MAAP. The devs have updated the packages and rsgsilib is now working on conda. Would you be able to update the workspace with the new package?
 
Thanks, Nathan

**Comment by mayadebellis** [comment]
Not super urgent but I attempted to add it with the updates Laura requested. It caused the build to fail so I got rid of it and will look into it more later

**Comment by mayadebellis** [comment]
`conda install -c conda-forge rsgislib` breaks image build. Emailed thomas to let him know and see if he has any other advice

**Comment by gchang** [comment]
Will close because the library breaks the build and is outside the scope of the ADE.
