### ISSUE TITLE
Update MAAP API to allow for variable presigned URL expiration times

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#208]
Undo the 7 day/1 week expiration for the demo and properly implement variable expiration times based on the UI updates.

**Comment by bsatoriu** [comment]
On dev, there is a new expiration option in the pre-signed url feature that sets the expiration period. The hard-coded 14 day expiration has been replaced in Ops by the 'exp' parameter: https://api.maap-project.org/api/ (see 
/members/self/presignedUrlS3/{bucket}/{key})

**Comment by oddes** [comment]
@Brian

Could u please see as shown below, I do not see option to set sets the expiration period. 

![Screen Shot 2021-01-04 at 9.17.37 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/fb6f7778-cbb7-4ba4-8abe-1b1d7ba36615)

**Comment by bsatoriu** [comment]
@oddes the 24 hours/1 week/30 days options shown in your screenshot are the expiration period choices. This looks correct. I am seeing the same thing on my end.

![Screen Shot 2021-01-12 at 1 04 12 PM](https://user-images.githubusercontent.com/27687558/104374721-27f4f980-54d7-11eb-88ae-33ab8ae7d3ae.png)
