### ISSUE TITLE
GEDI data not downloading to workspace

### ISSUE THREAD

**Issue by lauraduncanson** [MAAP-Project/ZenHub#211]
**Describe the bug**
Using same script as previously, GEDI granules are not downloading to workspace. The first granule is, but subsequent downloads seem to start (file appears), but then the file disappears with a large error message about i/o:

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-73-9ffa431f13d3> in <module>
     37     else:
     38         #print(f)
---> 39         gedi_granules[f].getLocalPath(download_dir)
     40 print(count)

/opt/conda/lib/python3.7/site-packages/maapPy-0.3.0-py3.7.egg/maap/Result.py in getLocalPath(self, destpath, overwrite)
     37             if not overwrite and not os.path.isfile(destpath + "/" + filename):
     38                 s3 = boto3.client('s3', aws_access_key_id=self._awsKey, aws_secret_access_key=self._awsSecret)
---> 39                 s3.download_file(o.netloc, o.path.lstrip('/'), destpath + "/" + filename)
     40 
     41             return destpath + '/' + filename

/opt/conda/lib/python3.7/site-packages/boto3-1.16.8-py3.7.egg/boto3/s3/inject.py in download_file(self, Bucket, Key, Filename, ExtraArgs, Callback, Config)
    170         return transfer.download_file(
    171             bucket=Bucket, key=Key, filename=Filename,
--> 172             extra_args=ExtraArgs, callback=Callback)
    173 
    174 

/opt/conda/lib/python3.7/site-packages/boto3-1.16.8-py3.7.egg/boto3/s3/transfer.py in download_file(self, bucket, key, filename, extra_args, callback)
    305             bucket, key, filename, extra_args, subscribers)
    306         try:
--> 307             future.result()
    308         # This is for backwards compatibility where when retries are
    309         # exceeded we need to throw the same error from boto3 instead of

/opt/conda/lib/python3.7/site-packages/s3transfer-0.3.3-py3.7.egg/s3transfer/futures.py in result(self)
    104             # however if a KeyboardInterrupt is raised we want want to exit
    105             # out of this and propogate the exception.
--> 106             return self._coordinator.result()
    107         except KeyboardInterrupt as e:
    108             self.cancel()

/opt/conda/lib/python3.7/site-packages/s3transfer-0.3.3-py3.7.egg/s3transfer/futures.py in result(self)
    263         # final result.
    264         if self._exception:
--> 265             raise self._exception
    266         return self._result
    267 

/opt/conda/lib/python3.7/site-packages/s3transfer-0.3.3-py3.7.egg/s3transfer/tasks.py in __call__(self)
    124             # main() method.
    125             if not self._transfer_coordinator.done():
--> 126                 return self._execute_main(kwargs)
    127         except Exception as e:
    128             self._log_and_set_exception(e)

/opt/conda/lib/python3.7/site-packages/s3transfer-0.3.3-py3.7.egg/s3transfer/tasks.py in _execute_main(self, kwargs)
    148         )
    149 
--> 150         return_value = self._main(**kwargs)
    151         # If the task is the final task, then set the TransferFuture's
    152         # value to the return value from main().

/opt/conda/lib/python3.7/site-packages/s3transfer-0.3.3-py3.7.egg/s3transfer/download.py in _main(self, fileobj, data, offset)
    570         """
    571         fileobj.seek(offset)
--> 572         fileobj.write(data)
    573 
    574 

/opt/conda/lib/python3.7/site-packages/s3transfer-0.3.3-py3.7.egg/s3transfer/utils.py in write(self, data)
    362     def write(self, data):
    363         self._open_if_needed()
--> 364         self._fileobj.write(data)
    365 
    366     def seek(self, where):

OSError: [Errno 5] Input/output error

**To Reproduce**
count=0
for f in range(2, len(gedi_granules)):
    #ID = s[f]['Granule']['DataGranule']['ProducerGranuleId']
    ID = gedi_granules[f]['Granule']['OnlineAccessURLs']['OnlineAccessURL']['URL']                    
    count=count+1
    download_dir = '/projects/r2d2/gedi_test_granules_congo'
    existingfiles = [file for file in os.listdir(download_dir)]
    print(os.listdir(download_dir))
    if ID in existingfiles:
        print('file exists...')
    else:
        #print(f)
        gedi_granules[f].getLocalPath(download_dir)
print(count)

**Expected behavior**
Granules to download 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gchang** [comment]
This could be because you're downloading to your S3-backed folder. Will need to test some more.
