### ISSUE TITLE
Error Message for S3 Presigned URL Generation

### ISSUE THREAD

**Issue by echyam** [MAAP-Project/ZenHub#214]
The user doesn't get any error message when trying to generate a URL from an unsupported file directory

**Comment by echyam** [comment]
Click to get presigned s3 url the same way:
<img src="https://user-images.githubusercontent.com/11476825/99012457-4a808b80-2503-11eb-9d44-6a19fc85c4bd.png" width="500"/>

### Scenario 1:
Get link for any folder -> error message saying links cannot be generated for folders:
<img src="https://user-images.githubusercontent.com/11476825/99012848-0fcb2300-2504-11eb-9390-373e14da8b13.png" width="300"/>

### Scenario 2:
Get link for file outside mounted directory -> error message saying wrong path, lists mounted directories
<img src="https://user-images.githubusercontent.com/11476825/99012924-3f7a2b00-2504-11eb-9ac3-56d1c7c71a1a.png" width="550"/>

### Scenario 3:
Get link for file inside mounted directory -> presigned s3 link provided with reminder of selected duration and button to copy link to clipboard
<img src="https://user-images.githubusercontent.com/11476825/99013027-794b3180-2504-11eb-9726-accda7d2dff7.png" width="670"/>

**Comment by oddes** [comment]
@echyam 
Thanks for the updating the Instructions & screen shots.

Scenario 1: Works as expected. PASS
Scenario 2: Works as expected. PASS
Scenario 3: FAILS with "Failed to get presigned s3 url" Please see the attached screen shot for further details. I have refreshed the page and verified loading the workspace again but still see the same error:

![Screen Shot 2020-11-13 at 1.49.25 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/2af385a7-7544-40dd-b2fa-393993e6f117)

**Comment by echyam** [comment]
@bsatoriu it looks like the call to the API for getting a signed URL is getting a 500 in this section: https://github.com/MAAP-Project/maap-jupyter-ide/blob/4852468450bc3a82270bc18fecc7cfe1e502600a/show_ssh_info/show_ssh_info/handlers.py#L424-L433

(check logs)

**Comment by oddes** [comment]
@gchang 

This issue is still reproducible as explained above. Please assign this to someone in our team for the fix.

**Comment by gchang** [comment]
@oddes I'm able to successfully execute scenario #3. Could you re-verify?

**Comment by oddes** [comment]
Working as expected: Please see the attached screenshot:

![Screen Shot 2020-12-01 at 2.27.54 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/509c3288-29fc-4d4f-825a-2aab09eb28b3)
