### ISSUE TITLE
Consolidate User S3 Folders

### ISSUE THREAD

**Issue by echyam** [MAAP-Project/ZenHub#215]
Since we want `/projects/eyam` (read-write) and `/projects/maap-users/eyam` (read-only) to point to the same s3 prefix (`s3://maap-dev-dataset/maap-users/eyam`), we need to:

- [ ] update DPS to upload output to `s3://maap-dev-dataset/maap-users/<username>/dps_output` instead of `s3://maap-dev-dataset/<username>/dps_output`
- [ ] update jlab extension `show_ssh_info` to mount `s3://maap-dev-dataset/maap-users/<username>` to `/projects/<username>`
- [ ] copy user data on s3 from `s3://maap-dev-dataset/<username>` to `s3://maap-dev-dataset/maap-users/<username>`
- [ ] remove top-level user folders in s3 `s3://maap-dev-dataset/<username>`

**Comment by gchang** [comment]
Outdated, replaced with the new bucket structure.
