### ISSUE TITLE
Disable file trash storage in JupyterLab

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#220]
The Ops ADE reached maximum storage capacity recently when a user generated 1TB worth of h5 files in a local workspace.  Even after deleting these files, the storage usage remain unchanged after Jupyter moved the deleted files into the system's trash folder. See this PR for info on this behavior: https://github.com/jupyter/notebook/pull/1968#issuecomment-682281332

To prevent unintended caching of deleted files, we can set the `delete_to_trash` config setting in `send2trash` library to `false`. This will prevent users from being able to recover files that may get deleted accidentally. However, the convention in MAAP is to store critical data inside of a S3-backed user folder, which mitigates this potential risk.

**Comment by gchang** [comment]
This is still valid and open.

**Comment by gchang** [comment]
Or... we could move/link the trash folder to a S3-backed folders.

**Comment by gchang** [comment]
In GCC, the project file system is now on EFS so there's no limit to storage so the system trash is no longer an issue that will prevent users from using more storage. However, we need to still monitor disk usage and let users know when they're using a lot of resources. Captured in #374.
