### ISSUE TITLE
Clear up discrepancies between mas and dev gitlab

### ISSUE THREAD

**Issue by mayadebellis** [MAAP-Project/ZenHub#237]
- We build everything on dev but the same repos also exist on mas - it is confusing.
- We have run into issues with our base images sometimes pulling from mas and sometimes from dev
- I dont understand how the mirroring of the jupyter_image container registry works but that is the only one that seems to be working
- Change base_images.txt in dev to point to the dev base images (make sure they are all up to date and none of the things in mas are needed. Then hopefully we can get rid of mas? set up a better mirror?

**Comment by gchang** [comment]
Please go ahead replace the repository in mas.maap-project.org with the ones in repo.nasa.maap.xyz. Eventually this should be out in Github-land, but for now, let's just consolidate everything in our ops repository. Take a backup of git repo in mas.maap-project.org and then force push the repository from the dev repo.

**Comment by gchang** [comment]
Now that repo.nasa and mas.maap-project are split, need to verify that the references are still correct. For example, `jupyter_image` in repo.nasa point to the `ade_base_images` in mas.maap-project. Should they be?

**Comment by mayadebellis** [comment]
Yeah that was the thing I was mumbling about in Tuesday's meeting. Everything in repo should point to things in repo. Even though they will all move eventually, for now this is where all the correct images are. We used to point to the base images in mas, but I switched that today to repo's `ade_base_images` and I think things should be good.

**Comment by mayadebellis** [comment]
Migration from xyz -> mas

- [ ] Archive current out of date repos on mas
- [ ] Copy repos on xyz to mas
- [ ] Copy all images on xyz to mas
- [ ] Move GitHub trigger from xyz to mas
- [ ] Update urls everywhere (in devfiles and images etc) to point to mas
- [ ] Test
- [ ] Delete everything from xyz once we are sure that’s safe to do so
