### ISSUE TITLE
Update DNS entries for all environments

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#241]
Here's the list of IP addresses and their mappings. I added the `ops` subdomain so we don't conflict with the existing systems (hostnames that don't specify an environment). Once everything is prepared, we can then switch over the actual ops domains. This follows the naming convention as specified here: https://earthdata.nasa.gov/eosdis/science-system-description/web-infrastructure

```
auth.dit.maap-project.org   A Record    100.21.12.166
api.dit.maap-project.org    A Record    100.21.12.166
dit.maap-project.org        A Record    100.21.12.166
www.dit.maap-project.org    CNAME       dit.maap-project.org
ade.dit.maap-project.org    A Record    52.11.142.173
repo.dit.maap-project.org   A Record    52.11.173.8
mas.dit.maap-project.org    A Record    52.11.173.8

auth.uat.maap-project.org   A Record    52.25.47.49
api.uat.maap-project.org    A Record    52.25.47.49
uat.maap-project.org        A Record    52.25.47.49
www.uat.maap-project.org    CNAME       uat.maap-project.org
ade.uat.maap-project.org    A Record    54.203.251.197
repo.uat.maap-project.org   A Record    54.184.115.46
mas.uat.maap-project.org    A Record    54.184.115.46

auth.ops.maap-project.org   A Record    52.25.223.135
api.ops.maap-project.org    A Record    52.25.223.135
ops.maap-project.org        A Record    52.25.223.135
www.ops.maap-project.org    CNAME       ops.maap-project.org
ade.ops.maap-project.org    A Record    44.232.24.204
repo.ops.maap-project.org   A Record    34.210.15.84
mas.ops.maap-project.org    A Record    34.210.15.84
```

**Comment by gchang** [comment]
The `uat` stuff should already be there. The `dit` environment at JPL will be set up in us-west-2 (everything is currently in us-east-1). I reserved some IP addresses for `ops` already.

**Comment by abarciauskas-bgse** [comment]
@gchang This should be done. For future reference, I created some scripts to do this, which are in a gist
https://gist.github.com/abarciauskas-bgse/e87914eaf58ea95d7ff756e993f58582

I have screenshots from route53 and can post those here for verification but don't want to clutter the ticket.

**Comment by abarciauskas-bgse** [comment]
@gchang I believe this is done so closing.
