### ISSUE TITLE
Remove access keys from the S3FS mounting extension and use IAM roles

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#243]
With IAM roles, we don't need to inject the workspace with keys. The machines that run workspaces have access to S3 directly. You should be able to mount s3 buckets with the `iam_role=auto` mounting parameters. You can also presign urls with iam roles as well. Once this is done, we can remove access keys from everywhere, including Gitlab CI.

**Comment by gchang** [comment]
In order to use iam_roles in GCC, you need to also add the `-o imdsv1only` flag as well. Otherwise it'll hang.

**Comment by bsatoriu** [comment]
This is implemented in the develop branch and verified on UAT.
