### ISSUE TITLE
Update CMR and Earthdata Search URLs in UAT Platform Systems (www, ade and api)

### ISSUE THREAD

**Issue by abarciauskas-bgse** [MAAP-Project/ZenHub#247]
The URLs for CMR and Earthdata Search in uat.maap-project.org (and presumably ade.uat.maap-project.org, api.uat.maap-project.org) should be:

* cmr.uat.maap-project.org
* search.uat.maap-project.org

and _not_ cmr.maap-project.org, search.maap-project.org

I did verify that
* uat.maap-project.org/search points to search.maap-project.org and _not_ search.uat.maap-project.org. 

~Also nothing that search.uat.maap-project.org _currently_ points to cmr.maap-project.org when it should be pointing to cmr.uat.maap-project.org as well, so I will create a separate ticket to make that change.~ ⬅️ this has been resolved

**Comment by gchang** [comment]
I've verified that links from UAT versions of ade and www point to the UAT EDSC. @bsatoriu Does the UAT api point to the UAT cmr as specified above?

**Comment by gchang** [comment]
@abarciauskas-bgse Is this a typo? "cmr.maap-project.org when it should be pointing to cmr.maap-project.org", do you mean "should be pointing to cmr.**uat**.maap-project.org?"

**Comment by abarciauskas-bgse** [comment]
Yes thanks for flagging @gchang I've updated the description
