### ISSUE TITLE
Unable to register algorithm on UAT ADE 

### ISSUE THREAD

**Issue by sujen1412** [MAAP-Project/ZenHub#248]
To recreate: 

After setting up a repo with algorithm_config.yaml, right click and click on Register as MAS Algorithm. 

After clicking ok, I see nothing on the screen. 

On inspecting the browser console I see 

![Screen Shot 2021-02-18 at 5.51.27 PM.png](https://images.zenhubusercontent.com/5ee96ae63216ffad10c6273e/6bae46c8-ab33-4820-a832-cd90d027777d)

**Comment by gchang** [comment]
Here's the log for that error. Looks like the MAAP API isn't configured correctly? @bsatoriu 

```
[E 01:51:05.861 LabApp] Uncaught exception GET /hysds/getQueues (10.115.187.107)
    HTTPServerRequest(protocol='http', host='ade.uat.maap-project.org', method='GET', uri='/hysds/getQueues', version='HTTP/1.1', remote_ip='10.115.187.107')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 1701, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/maap-jupyter-ide/submit_jobs/submit_jobs/handlers.py", line 1228, in get
        maap = MAAP(maap_api(self.request.host))
      File "/maap-py/maap/maap.py", line 52, in __init__
        self._SEARCH_GRANULE_URL = self._get_api_endpoint("search_granule_url")
      File "/maap-py/maap/maap.py", line 75, in _get_api_endpoint
        return 'https://{}/api/{}'.format(self._MAAP_HOST, self.config.get("maap_endpoint", config_key))
      File "/opt/conda/lib/python3.7/configparser.py", line 780, in get
        d = self._unify_values(section, vars)
      File "/opt/conda/lib/python3.7/configparser.py", line 1146, in _unify_values
        raise NoSectionError(section) from None
    configparser.NoSectionError: No section: 'maap_endpoint'
```

**Comment by bsatoriu** [comment]
I think this queues error is unrelated. I am able to register, but did notice that sometimes it only works on the second attempt.  I will try impersonating @sujen1412 's account to try and reproduce.

**Comment by bsatoriu** [comment]
@sujen1412 the plant stack you were using pointed to an out-of-date image. I've updated this, so if you restart your workspace, you should be able to register.

**Comment by gchang** [comment]
🙇 🙇 🙇

**Comment by sujen1412** [comment]
how do I check if my workspace has the correct image ? 

I stopped and restarted the workspace, I am still seeing the same error. 

Should start a new stack completely ?

**Comment by bsatoriu** [comment]
@sujen1412 yes, start a new stack.

**Comment by gchang** [comment]
The plant stack points to this https://mas.maap-project.org/root/che-devfile-registry/-/raw/7.23.1-maap/devfiles/maap-plant/impl.yaml which references `plant:develop`. However, `plant:develop` is older than `plant:develop-che7` here: https://mas.maap-project.org/root/jupyter_image/container_registry/10 Is that suppose to be the case?

**Comment by bsatoriu** [comment]
@gchang @sujen1412 I see the problem. The image at registry.nasa.maap.xyz/root/jupyter_image/plant:develop is no longer mirrored to mas.maap-project.org. It looks we need to either restore the mirror or update the stacks to point to the maap.xyz registry.

**Comment by gchang** [comment]
Yup, they're split now. The "mirror" was sharing the same backend, which leads to more confusion. I'd say let's switch it over to maap.xyz for now. We have to eventually rebuild mas.maap-project.org to make sure that's the master.

**Comment by bsatoriu** [comment]
I updated the stack definitions to point to maap.xyz and tested that algorithm registration now works in all three stacks.

**Comment by sujen1412** [comment]
okay started a new workspace and a new repository on repo.uat, and was able to register.
