### ISSUE TITLE
Sharing workspaces tab no longer visible?

### ISSUE THREAD

**Issue by lauraduncanson** [MAAP-Project/ZenHub#251]
**Describe the bug**
Went to add a user to workspace, no longer a share button/option, not clear how to do this anymore.

**To Reproduce**
1. Go to workspaces, settings

**Expected behavior**
There used to be an 'Add user' option

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gchang** [comment]
@marjo-luc @bsatoriu Was the sharing tab removed from the UI updates? I don't see it either on the pilot ops portal (ade.maap-project.org).

**Comment by bsatoriu** [comment]
@gchang I think Marjorie was working on restoring this, but I have the bandwidth today to get this re-enabled. @marjo-luc let me know if you want to tackle this today--otherwise I'll get it resolved later this afternoon.

**Comment by bsatoriu** [comment]
I re-enabled the Share tab, but will need to restart Che to deploy it. A restart will cause a minute-long outage, since the rolling update feature of Che is not available in the v6 version on Ops. @gchang do you want me to do the restart after hours?

**Comment by bsatoriu** [comment]
@lauraduncanson the sharing tab has been restored. You should see it the next time you refresh your workspace.

**Comment by oddes** [comment]
its restored:
![Screen Shot 2021-05-25 at 11.32.30 AM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/70abd640-6a21-4f71-b420-4fc5358275f9)
