### ISSUE TITLE
Update API to only allow algorithm registration if queue name is valid

### ISSUE THREAD

**Issue by NamrataM** [MAAP-Project/ZenHub#253]
If anyone registers an algorithm with any random queue name, we see the new invalid queue name show up in the `queues/list` endpoint of HySDS. Since HySDS doesn't validate queue names, we need to do so in the API.

Logic:
On algorithm registration, verify queue name specified by user against `queues/list` response from HySDS (on a fresh/clean cluster).
If queue is invalid, return a 500 response code with message asking the user to select a queue from a list.

**Comment by gchang** [comment]
Already implemented in HySDS v4.
