### ISSUE TITLE
Install a system memory monitor in Jupyterlab

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#255]
Running out of memory and having the kernel crash was a common occurence during the demos. Being able to show memory usage may help explain to users why kernels are crashing.

https://github.com/jupyter-server/jupyter-resource-usage

**Comment by mayadebellis** [comment]
`jupyter-resource-manager` only works in jupyterlab 3.x. Would have been very nice if they had said that in their readme or requirements somewhere clear! It was previously named `nbreuse` for 2.x - but the version specifically needs to be set to 0.3.6. The extension looks a little bit different but still helpful. It shows up in the  bottom right hand corner. It shows current memory but doesn't include what the max is, which can be seen by looking at the stack. Seems good enough for now and will improve when we update to jupyterlab 3.x
 ![image.png](https://images.zenhubusercontent.com/5ee967d942152fe068604fa1/63511f40-11eb-4db2-8b79-ac2bc50be236)
