### ISSUE TITLE
Implement federated login within the MAAP API and workspace

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#256]
Implement the solution without needing to give users the token, keep the federated token at the API level.

**Comment by bsatoriu** [comment]
UPDATE: the API work on federated login is ready: https://github.com/MAAP-Project/maap-api-nasa/commits/edl-federated-login. I am currently testing the client integration from the workspace.

**Comment by bsatoriu** [comment]
The federated login support is added now to the `edl-federated-login` branches of [maap-py](https://github.com/MAAP-Project/maap-py/tree/edl-federated-login) and [maap-api-nasa](https://github.com/MAAP-Project/maap-api-nasa/tree/edl-federated-login).

Federated login is invoked when calling Granule.getLocalPath() from the maap-py library  results in a 401 access denied response. This method first attempts the granule download directly against the CMR file url. If 401 response is received, maap-py then calls `{maap api}/api/cmr/file/{file_uri}` with the proxy-token included in the http headers ([see code](https://github.com/MAAP-Project/maap-py/blob/edl-federated-login/maap/Result.py#L56)). 

On the API side, we fetch the user's URS token from the MAAP db and pass that on to CMR ([see controller code](https://github.com/MAAP-Project/maap-api-nasa/blob/edl-federated-login/api/endpoints/cmr.py#L119)). Any non-200 response is passed back up as the maap-py error message.

**Comment by oddes** [comment]
Verified part of the following:

getLocalPath error in maap-py#366
