### ISSUE TITLE
Eliminate Eclipse Che Login by redirecting directly to CAS

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#258]
Currently when a user wants to log into the ADE, they have to click the MAAP login at the Che/Keycloak login page. For everyone except developers, the default is to log in via MAAP authentication so unless otherwise specified, it should always redirect to MAAP login.

**Comment by bsatoriu** [comment]
The auto-redirect is enabled. Documentation on enabling this is here: https://github.com/MAAP-Project/keycloak-cas-services#optional-central-authentication-service-configuration
