### ISSUE TITLE
Deploy CMR in GCC Ops environment

### ISSUE THREAD

**Issue by abarciauskas-bgse** [MAAP-Project/ZenHub#261]
Acceptance criteria:
* cmr.ops.maap-project.org/search/granules and /collections return same results as cmr.uat.maap-project.org
* cmr.ops.maap-project.org/ingest and /access-control are working

Tasks:
- [x] Check the VPC and subnets exist as expected in GCC Ops account. They should match those resources in GCC UAT: VPC with at least 2 public and 2 private subnets.
- [x] Create a replica of the CMR UAT database and share it with the CMR Ops account
- [ ] Follow steps in https://github.com/MAAP-Project/maap-data-system-services/blob/main/DEPLOYMENT.md but instead of terraforming the VPC, use the VPC and subnets already in GCC environment

**Comment by abarciauskas-bgse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Deploy CMR to GCC Ops Account](https://trello.com/c/Jluhl5XA/184-deploy-cmr-to-gcc-ops-account)

**Comment by markdboyd** [comment]
Resources for the deployment:

- GCC OPS Elasticsearch AMI: `ami-0de92f2c5eff55f1c`
- VPC: `vpc-04d00d6e2f7b09557`
- Public subnets: `["subnet-0402383901f09cf2e", "subnet-04359612e3a31ff36"]`
- Private subnets: `["subnet-0ad02d1118fa10eb5", "subnet-01e5cff1672b5de8f"]`

Variables for deployment (excluding others for security):

```
prefix = "maapds"
environment_name = "gccops"
```

S3 backend information:

```
terraform {
  backend "s3" {
    bucket = "maap-data-system-services-gcc-ops-tfstate"
    key    = "maapds-gcc-ops"
    region = "us-west-2"
  }
}
```

Progress:

- [x] Deployed `maapds-ops-elasticsearch-cluster` Cloudformation stack for ES cluster
- Deployment of maap-data-system-services in progress

**Comment by markdboyd** [comment]
There was an issue where the VPCs in the account did not have both:

- access to outbound internet from a private subnet
- inbound access to port 443

However, coordinating with GCC, they created a new private subnet in VPC vpc-0b66bf97fe23db1b2. I was able to re-deploy the ES cluster in that VPC and it is stable.

I'm now trying to redeploy the data system services in that VPC

**Comment by markdboyd** [comment]
After a few attempts, the ES cluster and maap-data-system-services deployments are now stable in GCC OPS. 

The last piece is trying to get `cmr.ops.maap-project.org` to resolve to the DNS name for the CMR load balancer in GCC OPS. I believe that I updated the appropriate configuration for the `maap-project.org` hosted zone in the UAH Dev account, but it's still not working

**Comment by markdboyd** [comment]
All of the database migration and indexing requests have been made. Will check back to ensure that all data has been properly indexed to ES.

**Comment by markdboyd** [comment]
After letting the database indexing run overnight and doing a few spot checks, it seems like the data in GCC OPS now matches the data in UAT

https://cmr.ops.maap-project.org/search/collections
https://cmr.uat.maap-project.org/search/collections

https://cmr.ops.maap-project.org/search/granules?provider=NASA_MAAP&short_name=ATL08&version=003
https://cmr.uat.maap-project.org/search/granules?provider=NASA_MAAP&short_name=ATL08&version=003

This ticket is complete.
