### ISSUE TITLE
Update CMR UAT deployment with latest CMR prod database

### ISSUE THREAD

**Issue by abarciauskas-bgse** [MAAP-Project/ZenHub#268]
We need to update CMR UAT deployment with the latest CMR Prod snapshot (still in UAH) because we have a number of metadata updates that are currently blocked due to a queue error.

Today we are going to update the deployment in GCC UAT together to make sure another dev can update that deployment.

- [x] Make sure Mark can authenticate with GCC UAT using credentials from cloudtamer
- [x] Create the DB replica from the existing prod DB (in UAH)
- [x] share that DB snapshot with the GCC UAT environment
- [ ] Make sure Mark has the right terraform variables for the GCC UAT environment. Make sure the snapshot id is for the newly created DB snapshot
- [ ] Mark runs terraform plan + apply

**Comment by abarciauskas-bgse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update CMR UAT deployment with latest CMR prod database](https://trello.com/c/z0znTTku/265-update-cmr-uat-deployment-with-latest-cmr-prod-database)

**Comment by abarciauskas-bgse** [comment]
From our meeting this morning, we have the following steps outlined:

Since I have gcc tenant operator privelges, and the updated terraform code requires security groups and roles to be created, I will first deploy to UAT to create the roles and security groups. Then Mark will (using the same terraform state from S3) use the database snapshot identifier (from the snapshot of the UAH prod database) and update the GCC UAT database using that snapshot.

- [x] (aimee) update vpc and subnets in terraform.tfvars
- [x] (aimee) update bucket in terraform.tf
- [x] (aimee) correct AWS_PROFILE
- [ ] aimee deploys new security groups and roles and asserts things are working
- [ ] (mark) update vpc and subnets in terraform.tfvars
- [ ] (mark) update bucket in terraform.tf
- [ ] (mark) correct AWS_PROFILE
- [ ] (mark) update snapshot identifier in terraform.tfvars and deploy
- [ ] (mark) run reindexing commands
- [ ] (mark) assert updated data, some possible things to check:
    - https://cmr.uat.maap-project.org/search/granules?provider=NASA_MAAP&short_name=ATL08&version=003 (GCC UAT) - 117965 results
    - https://cmr.maap-project.org/search/granules?provider=NASA_MAAP&short_name=ATL08&version=003 (UAH) - 119100 results
    - also check SENTINEL-1A_DP_GRD_HIGH should exist

**Comment by abarciauskas-bgse** [comment]
@markdboyd this is ready for you to take the rest of the steps, but also I think requires https://github.com/MAAP-Project/maap-data-system-services/pull/23

**Comment by markdboyd** [comment]
Update:

- [x] (mark) update vpc and subnets in terraform.tfvars
- [x] (mark) update bucket in terraform.tf
- [x] (mark) correct AWS_PROFILE
- [x] (mark) update snapshot identifier in terraform.tfvars and deploy
  - Had to delete the RDS database and let Terraform recreate it using the snapshot 
- [x] (mark) run reindexing commands:

```
HTTP/2 202
date: Tue, 16 Mar 2021 21:24:44 GMT
content-type: application/json;charset=utf-8
content-length: 80
cmr-request-id: 765fd3ea-5680-4aa9-93e8-b8e057340788
x-request-id: 765fd3ea-5680-4aa9-93e8-b8e057340788
server: Jetty(9.4.z-SNAPSHOT)

{"message":"Processing provider NASA_MAAP for bulk indexing from start index 0"}%
```

```
HTTP/2 202
date: Tue, 16 Mar 2021 21:24:59 GMT
content-type: application/json;charset=utf-8
content-length: 79
cmr-request-id: 1fedc630-9c74-4ee0-9525-3e6843bdfe4d
x-request-id: 1fedc630-9c74-4ee0-9525-3e6843bdfe4d
server: Jetty(9.4.z-SNAPSHOT)

{"message":"Processing provider ESA_MAAP for bulk indexing from start index 0"}%
```

**Comment by abarciauskas-bgse** [comment]
I noticed there was no change in the granule counts in ATL08 v003 and the `SENTINEL-1A_DP_GRD_HIGH` dataset so I looked into the logs and saw we were seeing again the sql error `Table or view does not exist`, which seemed to be stopping the reindexing from running successfully.

searching around in the logs near that error, I noticed this error:

```
2021-03-17 19:42:50.660 ip-10-50-160-159.us-west-2.compute.internal [async-dispatch-1] INFO [cmr.message-queue.queue.memory-queue] - Message {:action "index-provider", :provider-id "ESA_MAAP", :start-index 0, :id 3, :retry-count 1} re-queued with response: "Tool-association search failed. status: 500 body: {\"errors\":[\"An Internal Error has occurred.\"]}"
```

This led me to suspect that there was a database update (migration) that was missing since we restored from the update snapshot. So I went ahead and ran all the database migration commands, although I suspect the metadata-db was the key migration, looking at the Common Metadata Repository database (e.g. when I search for that log message response I found some references to "Tool-association" in the metadata-db app)

once I ran 
```
curl -i -XPOST -H "Echo-Token: $ECHO_TOKEN" https://$CMR_HOST/access-control/db-migrate
curl -i -XPOST -H "Echo-Token: $ECHO_TOKEN" https://$CMR_HOST/metadata-db/db-migrate
curl -i -XPOST -H "Echo-Token: $ECHO_TOKEN" https://$CMR_HOST/ingest/db-migrate
curl -i -XPOST -H "Echo-Token: $ECHO_TOKEN" https://$CMR_HOST/indexer/db-migrate
curl -i -XPOST -H "Echo-Token: $ECHO_TOKEN" https://$CMR_HOST/indexer/update-indexes
```

I ran
```
curl -i -XPOST -H "Echo-Token: $ECHO_TOKEN" -H "Content-Type: application/json" https://$CMR_HOST/bootstrap/bulk_index/providers/all
```

# Reviewing some expected changes

* `SENTINEL-1A_DP_GRD_HIGH` returns 3569 in "CMR Prod" (still UAH). CMR UAT now returns _more_ granules for this collection then "CMR Prod". This concerned me at first, but it seems likely that since @chuckwondo reported (See https://github.com/MAAP-Project/maap-cumulus-deploy/issues/44#issuecomment-789378623) that ~27k workflows succeeded that the number in CMR UAT is actually the number in the RDS database and 3569 granules is how many were indexed into "CMR Prod" database
    * See https://cmr.[uat.]maap-project.org/search/granules?provider=NASA_MAAP&short_name=SENTINEL-1A_DP_GRD_HIGH
* ATL08 v003 returns the same number of granules in prod and uat
    * See https://cmr.[uat.]maap-project.org/search/granules?provider=NASA_MAAP&short_name=ATL08&version=003

So we should be done with this update, thanks @markdboyd

**Comment by markdboyd** [comment]
@abarciauskas-bgse Sorry there was more to do here, but thanks for carrying this across the finish line and documenting the remaining problems/resolution! Helps build my understanding of CMR
