### ISSUE TITLE
Revert Eclipse Che modification that gave privileged mode to all containers

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#269]
Since we're using the Kubernetes definition in the dev files, we can strategically identify containers that need privileged mode. Since we're using a sidecar container to mount and expose the S3FS folders, we no longer need the primary workspace container to have privileged mode.

**Comment by bsatoriu** [comment]
The privileged access has been removed completed from our Che fork. See:

https://mas.maap-project.org/root/che7/-/commit/8565bea21ba4cbee09146910d8176d13661be363
https://mas.maap-project.org/root/che7/-/commit/0e8edf80c4381b674e066b948943d2a653c1a814
