### ISSUE TITLE
Ensure that S3 presigned URLs still operate as expected in the new folders

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#273]

**Comment by gchang** [comment]
@mayadebellis Bump

**Comment by mayadebellis** [comment]
Current status: we are generating urls for the right buckets but clicking on them leads to access denied

**Comment by bsatoriu** [comment]
I updated the API to support a new 'ws' (workspace) parameter to allow for mapping physical bucket paths to our mounted folders: https://github.com/MAAP-Project/maap-api-nasa/commit/135cf9e4c3a23cea27f98de7e9ec66da1b8c2743

And I updated the `show_ssh_info` plugin to pass in the `CHE_WORKSPACE_NAMESPACE` variable to this new ws parameter: https://github.com/MAAP-Project/maap-jupyter-ide/commit/3628dc216c678083aff7dbdba5e7a3a595436c0b

@oddes note you will need to restart your workspace to test this story.

**Comment by oddes** [comment]
@bsatoriu I am able to create and download the files as expected in Public and Private buckets. I am unable to add/delete or create a S3 presigned URLs in  "/Shared-buckets/sodde/" folder, is that expected functionality?

**Comment by bsatoriu** [comment]
No, @oddes , shared-buckets should also support presigned urls. I'll put this back in my queue to address this issue.

**Comment by bsatoriu** [comment]
@oddes and I were not able to reproduce this s3 presigned url issue in the `shared-buckets` folder during a test yesterday. Putting this issue back in the test queue.

**Comment by oddes** [comment]
Thanks Brian. Its working as expected.
