### ISSUE TITLE
Re-enable service name in the MAAP authentication style sheets

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#274]
When goes to the MAAP login page, it doesn't provide context to the login. For example, if a user is logging into MAAP from the web portal or from the ADE, the login page for both just say "Log with: ESA/URS." It should at the minimum show the CAS service name which states where the user is logging in from. The default stylesheet already does this so it's a matter of reinstating it.

This provides a better user experience in light of #258. When users are automatically redirected to the log in page, they know why they're being asked to log in rather than just being presented with essentially a blank log in screen.

**Comment by bsatoriu** [comment]
The service name has been re-enabled in GCC Ops. I also updated the background color to the dark blue used in the portal. 

Note that CAS will display an application icon that can be set in the service definition file, in addition to the text that is there now. I commented out the fallback icon.
