### ISSUE TITLE
Add URS app token to MAAP API and DPS environments

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#276]
To facilitate the use of federated-accessible DAAC data retrieval external to MAAP, URS requires both a URS token and the MAAP URS application credentials in the header of any download requests. As a first step in supporting these external DAAC requests, I propose targeting the following use cases:

## Scenario 1: Request data from a Jupyter notebook in the ADE.

This scenario will require proxying external data ingestion through the MAAP API, since the URS token and MAAP credentials cannot be stored on the client ADE. This will require adding the MAAP URS application the MAAP API, and also retrieving the user's URS token during the external data request.

## Scenario 2: Request data from a DPS Job.

In this scenario, the data ingestion will not be proxied through the MAAP API, but will be retrieved directly from the DAAC using DPS server environment, as described in issue #275 

## Changes required

1. Update the MAAP API to support the URS token retrieval and a new MAAP URS credentials setting.
2. Update the maap-py library to support sending the user's URS token and MAAP URS credentials directly to external DAAC resources. These checks would verify the presence of environment variables in the host environment. Unless running in DPS, these checks would be expected to fail (see #275).

**Comment by gchang** [comment]
@bsatoriu I think this is done based on what you've been working on? Any way to test?
