### ISSUE TITLE
Migrate MAAP's Che "fork" to Github and update references accordingly

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#278]
Since Che is part of MAAP infrastructure, we should have a primary copy in Github. We can keep a copy of the code in Gitlab for CI purposes. The new repos would be:

* github.com/maap-project/maap-ade-che
* github.com/maap-project/maap-ade-che-dashboard
* ...

I noticed that for change #277, it references Gitlab the jar in the source code, so that should be updated as well (registry/images items can stay in mas.maap-project). May want to squash some of the commits, especially the numerous gitlab-ci commits and possibly others to make the git history more manageable.

- [x] Revert one last remaining privileged mode change in `che/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/DockerimageComponentToWorkspaceApplier.java`
- [x] Squash superfluous commits in the MAAP branch of the code
- [x] Update references to files in the source code to point to Github instead of Gitlab
- [x] Update/rebase changes to Che 7.25.2, the last version officially supported with the old dashboard
- [x] Update/rebase changes to `che-devfile-registry` repo to version 7.25.2
- [x] Update/rebase changes to `che-dashboard` repo to version 7.25.2
- [x] Add a Github action to trigger a Gitlab build on commit (e.g. jupyter-ide [gitlab-trigger](https://github.com/MAAP-Project/maap-jupyter-ide/blob/master/.github/workflows/gitlab-trigger.yml))

**Comment by bsatoriu** [comment]
Bumped the Estimate to 13 to reflect the addition changes to dependent repos and additional unit testing.

**Comment by bsatoriu** [comment]
Our Che repos are moved to Github, with CI triggers pointed to their corresponding Gitlab repos:

- https://github.com/MAAP-Project/eclipse-che
- https://github.com/MAAP-Project/eclipse-che-dashboard
- https://github.com/MAAP-Project/eclipse-che-devfile-registry

I also added a gitlab pipeline build status badge to our new Readme files.
