### ISSUE TITLE
Deploy Authentication subsystem

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#279]
Off the top of my head, these may be the steps. Update if I'm missing anything.

- [x] Create or amend existing documentation about this setup
- [x] Create new EC2 instance that is linked to the `auth/www/api.ops.maap-project.org` elastic IP
- [x] Install/copy CAS configuration from UAT
- [x] Verify that CAS produces the proper log files with INFO settings
- [x] Verify service definitions are named correctly and have appropriate descriptions as these will be exposed with the new UI changes in #274
- [x] Install the new CAS stylesheets from #274
- [x] Install Syncope and ensure it's connected with CAS and Gitlab

**Comment by bsatoriu** [comment]
Documentation has been updated here: https://github.com/MAAP-Project/maap-auth-cas/blob/master/README.md

I moved the GitLab syncing code from the GitLab connector to the CAS overlay: https://github.com/MAAP-Project/maap-auth-cas/commit/1c2953e8ebc13cb59a4a5d5d97fcfcbc95543f0b. This was necessary to ensure the GitLab impersonation token is created as part of the initial user login into CAS. The overlay now creates a new user's Syncope and GitLab accounts during the first login to CAS. One benefit to this change is the elimination of an extra topology resource to configure and maintain. The GitLab root token is now stored in the cas.properties file.
