### ISSUE TITLE
Deploy MAS subsystem in Ops

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#283]
- [x] Create or amend existing documentation about this setup
- [x] Set up Gitlab and runners as they are in UAT and pilot ops.
- [x] Connect Gitlab to CAS and test login and token access
- [x] Copy over relevant repositories and exercise CI. Update Gitlab runner with different libraries as needed.
- [x] Verify container registry capability.

**Comment by gchang** [comment]
I've created a new Gitlab instance at https://repo.ops.maap-project.org. The registry is at https://mas.ops.maap-project.org. There's also an associated runner as well. Nothing has been initialized yet, so the Gitlab is currently empty and the runner doesn't have any libraries yet. We'll need to figure out what needs to be installed as we migrate repositories there.

**Comment by gchang** [comment]
Documentation here:
https://github.com/maap-project/maap-mas-gitlab

**Comment by bsatoriu** [comment]
@gchang GitLab auth is configured and set to auto-redirect to CAS. To circumvent the redirect, we'll need to navigate here: http://repo.ops.maap-project.org/users/sign_in?auto_sign_in=false
