### ISSUE TITLE
Verify interoperable logins between NASA and ESA in the OPS environment

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#291]

**Comment by oddes** [comment]
ESA link on OPS is throwing the client error. Can we fix the hyperlink?

{
    “reason”: “Unable to find client.“,
    “error_description”: “The client is not authorized to request an access token using this method.“,
    “state”: “TST-159-K8c3c-9JkOkMF6usbUR6Sd8V-jX-sVPG”,
    “error”: “unauthorized_client”
}

Steps:
1. Open https://ops.maap-project.org/
2. Click-on Login Link then and Login with ESA, you will notice the error:

**Comment by oddes** [comment]
Works as expected in UAT and OPS.
