### ISSUE TITLE
Deploy Dynamic Tiler API to GCC UAT (WMTS)

### ISSUE THREAD

**Issue by abarciauskas-bgse** [MAAP-Project/ZenHub#298]
Acceptance Criteria:
* Assert that a dynamic tiler is deployed in GCC UAT and can be used to tile our cloud-optimized datasets (UAVSAR, LVIS, SRTM)

Background:
* MAAP Dynamic Tiler Lambda is currently deployed https://us-east-1.console.aws.amazon.com/lambda/home?region=us-east-1#/functions/maap-dynamic-tiler-production
* The gateway endpoint https://us-east-1.console.aws.amazon.com/apigateway/home?region=us-east-1#/apis/8e9mu91qr6/resources/6u5q55/methods/ANY is referenced in maap-api-nasa as the `TILER_ENDPOINT` https://github.com/MAAP-Project/maap-api-nasa/blob/master/api/settings.py#L51

Tasks:
- Test deployment in UAH AWS account
    - [x] @abarciauskas-bgse come up with test tiles and mosaic urls
    - [x] @TonHai1111 Test deployment of titiler lambda (CDK code in titiler) UAH AWS account: https://developmentseed.org/titiler/deployment/aws/lambda/#deploy, this should create an AWS API Gateway endpoint which can be used in the next step
    - [x] @TonHai1111 Test URL by running https://github.com/MAAP-Project/maap-api-nasa with updated `TILER_ENDPOINT` locally
    - [x] Request updated endpoints in test deployment (api.maap.xyz / maap-api-nasa codebase)
        - should there be api.test.maap-project.org?
    - [x] Update maap-data-system-services documentation as required to inform new developers about how to deploy and manage the dynamic tiler 
- @abarciauskas-bgse or other GCC Dev: Run titiler deployment in GCC UAT
    - [x] repeat steps above
    - [ ] work with jpl team to update the api.uat.maap-project.org endpoint to point to the updated GCC UAT tiler and assert that the wmts endpoints work via the documentation in https://docs.maap-project.org/en/latest/visualization/using_pycmc.html

Follow up tasks:
- Update API endpoints for visualization in metadata for SRTM, LVIS and UAVSAR (pointing to api.maap.xyz and not api.maap-project.org)
- Can we use dynamic URL generation via SSM parameter?

**Comment by abarciauskas-bgse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Deploy Dynamic Tiler API to GCC UAT (WMTS)](https://trello.com/c/nGo6SLc6/273-deploy-dynamic-tiler-api-to-gcc-uat-wmts)

**Comment by TonHai1111** [comment]
Done: 
 - Deployment of titiler lambda (CDK code in titiler) UAH AWS account
 - Test URL by running https://github.com/MAAP-Project/maap-api-nasa with updated TILER_ENDPOINT locally

**Comment by abarciauskas-bgse** [comment]
Working on generating a more complete / better set of test urls, but here is one where `8e9mu91qr6` should be replaced

- https://8e9mu91qr6.execute-api.us-east-1.amazonaws.com/production/tiles/11/1076/1020.png?url=s3://cumulus-map-internal/file-staging/nasa-map/AFLVIS2___001/LVIS2_Gabon2016_0308_R1808_048492_cog.tif&rescale=11,57&indexes=1

@TonHai1111 what is the URL of your API gateway in UAH AWS account?
What steps did you follow to get the maap-api-nasa working locally that weren't in that repos README? I think you mentioned something about having to run a postgres database?

**Comment by TonHai1111** [comment]
This is the endpoint in my account: https://baxpil3vd6.execute-api.us-east-1.amazonaws.com/

**Comment by TonHai1111** [comment]
Yes, If you follow the instructions: https://github.com/MAAP-Project/maap-api-nasa and reach to the following step:

```
FLASK_APP=api/maapapp.py flask run --host=0.0.0.0
```
Then you should need to create a postgres DB if you haven't had one. Here is the steps to create a database (named: maap_dev):
#>>> 3. create an empty postgres db (maap_dev) (a fix for 'database maap_dev does not exist'):
#>>> sudo -u postgres psql
#>>> (in postgres shell): create database maap_dev;
#>>> (in postgres shell): \q

If you have any other issues with postgres. Let's me know, I experienced a couple of them, but fixed them all, so I can send you a quick fix for that!

**Comment by abarciauskas-bgse** [comment]
@TonHai1111 thanks - can you create a branch and open a PR to maap-api-nasa to add these instructions to the README - perhaps somewhere in https://github.com/MAAP-Project/maap-api-nasa/blob/master/README.md#local-development-using-python-virtualenv ?

**Comment by TonHai1111** [comment]
Sure: Here is the PR for the maap-api-nasa: https://github.com/MAAP-Project/maap-api-nasa/pull/16

I don't have permission for the titiler, can you give me write access to the titiler? Thanks!

**Comment by abarciauskas-bgse** [comment]
@TonHai1111 Why do you need access to titiler?

**Comment by abarciauskas-bgse** [comment]
@TonHai1111 what additions or changes are you thinking about making for titiler?

I was thinking we need to add some documentation to maap-data-system-services about how to deploy titiler. Either we could add a few lines to this document: https://github.com/MAAP-Project/maap-data-system-services/blob/main/DEPLOYMENT.md about how to find the source code and deployment instructions for titiler and how to test the deployment.

I will generate another test URL for the mosaic endpoint, but I think the next step will be to include a script for testing /tiles and /mosaic endpoints with MAAP data similar to what @slesaad has done in https://github.com/MAAP-Project/maap-api-query-service/pull/4. Right now I'm thinking that test script can live in maap-data-system-services as well, what do you think?

**Comment by TonHai1111** [comment]
1. Yeah, I would also like to add some comments on a couple of issues I got during the deployment of titiler in the hope that it would help someone in the future.
2. Yeah, agree it would benefit for anyone who will work with maap-data-system-services. Do you want me to take a look into that and get it done? 
3. Yes, we can do some think similar!

**Comment by abarciauskas-bgse** [comment]
@TonHai1111 following up on :

**Comment by abarciauskas-bgse** [comment]
@wildintellect and @TonHai1111 and I have been investigating this and at the moment it looks like using `titler` and `maap-api-nasa`'s `/wmts` endpoint will not work as-is. `maap-api-nasa`'s `/wmts` end point users `/mosaic/z/x/y.png` and `/mosaic/tilejson` - neither of these endpoints exist in the newer titiler and from what we can tell the way you are able to pass multiple comma-delimited URLs to those `/mosaic/` endpoints is not a feature of any `titiler` endpoint.

Right now, the code in maap-api-nasa for `/GetTile` collects a string of URLs which should be COGs on S3
it then calls `gen_mosaic_url()` to generate a complete URL to the TILER_ENDPOINT `/mosaic/z/x/y`, for example:

https://8e9mu91qr6.execute-api.us-east-1.amazonaws.com/production/mosaic/11/1077/1020.png?urls=s3://cumulus-map-internal/file-staging/nasa-map/AFLVIS2___001/LVIS2_Gabon2016_0308_R1808_048492_cog.tif,s3://cumulus-map-internal/file-staging/nasa-map/AFLVIS2___001/LVIS2_Gabon2016_0308_R1808_049095_cog.tif&rescale=11,57&indexes=1,2

The code in maap-api-nasa for `GetCapabilities` (which is used by clients such as the [common mapping client](https://github.com/nasa/common-mapping-client) which is used in maap via the `ipycmc` library, see documentation https://docs.maap-project.org/en/latest/visualization/using_pycmc.html) uses `/mosaic/tilejson.json`, see https://github.com/MAAP-Project/maap-api-nasa/blob/57236a44311f5095ed08a6e67047cbd7b9ff7048/api/endpoints/wmts.py#L177

In practice I don't think either of these /mosaic endpoints is necessary. There should really just be 2 use cases we need to fulfill:
* Dynamic visualization of a single granule
* Dynamic visualization of a "collection" - in the case of AFLVIS2 and AfriSAR_UAVSAR_Coreg_SLC we enable these as default "layers" via something like the common mapping client and to support these visualizations via a mosaic cog specifically created for AFLVIS2. All the granules for `AfriSAR_UAVSAR_Coreg_SLC` I believe overlap so mosiacing those COGs doesn't make sense (need to check this)

In short, I think we can update the existing code to just use the [Tile](https://d852m4cmf5.execute-api.us-east-1.amazonaws.com/docs#/Cloud%20Optimized%20GeoTIFF/tile_cog_tiles__z___x___y___format__get) endpoint for `GetTile` and the [bounds](https://d852m4cmf5.execute-api.us-east-1.amazonaws.com/docs#/Cloud%20Optimized%20GeoTIFF/bounds_cog_bounds_get) endpoint for `GetCapabilities`. Users will no longer be able to pass a list of granules or S3 URLs but visualizing all of the AFLVIS2 collection should still be possible.

Next steps:
* Use a local deployment of `maap-api-nasa` to test `GetCapabilities` and `GetTile` after updating `TILER_ENDPOINT` to point to an updated titiler deployment and verify that reqeusts fail (since there is no `/mosaic/` endpoint
* Write or update automated tests
* Update code in the local deployment to use `/cog/tiles/z/x/y` for GetTile and `/cog/tiles/bounds` for GetCapabilities and test
* Submit PR to maap-api-nasa and coordinate with JPL on deployment

**Comment by wildintellect** [comment]
There is a 3rd use case which is dynamic visualization of a collection search result (could be made to also use a list of user specified granules). There are a few options to support.
1. Translate the search results from CMR to STAC and use the `stac` endpoint
2. Return a tilejson or mosiacjson, and use the `mosaicjson` endpoint (which is basically what was happening before)

I could see a python module in the ADE to create mosaicjson for ADE users who want to make custom visuals with specific granules.

**Comment by wildintellect** [comment]
This is what we were missing, pass an arbitrary list of COG urls and get a mosaicjson back, that can then be forwarded to titiler.
I was incorrect above the `/stac` only does single items.
```
from cogeo_mosaic.mosaic import MosaicJSON

# list of COG
dataset = ["1.tif", "2.tif"]
mosaic_definition = MosaicJSON.from_urls(dataset)

print(mosaic_definition.tiles)
> {"tile": {"00001": ["cog1.tif", "2.tif"]}}
```
https://developmentseed.org/cogeo-mosaic/intro/

How to do it from a STAC api https://developmentseed.org/cogeo-mosaic/examples/Create_a_Dynamic_StacBackend/

**Comment by wildintellect** [comment]
Another option is to create a custom backend for Titiler, [example](https://developmentseed.org/titiler/examples/code/mosaic_from_urls/)

**Comment by abarciauskas-bgse** [comment]
This is deployed to UAT, however it uses a different deployment configuration to test, since we are waiting on CDK bootstrapping of the UAT environment - which there is a GCC ticket for https://gcc-jira.gsfc.nasa.gov/servicedesk/customer/portal/4/GSD-518

The deployment is https://titiler.uat.maap-project.org/. Setting

```
TILER_ENDPOINT = 'https://titiler.uat.maap-project.org'
```

in settings.py of maap-api-nasa and running the tests runs successfully:

```
(maap-api-nasa) aimeebarciauskas@Aimees-MacBook-Pro-2 maap-api-nasa % python3 -m unittest -v test/api/endpoints/test_wmts_get_capabilities_new_titiler.py

test_get_capabilities_default (test.api.endpoints.test_wmts_get_capabilities_new_titiler.GetCapabilitiesCase) ... ok

----------------------------------------------------------------------
Ran 1 test in 5.814s

OK
(maap-api-nasa) aimeebarciauskas@Aimees-MacBook-Pro-2 maap-api-nasa % python3 -m unittest -v test/api/endpoints/test_wmts_get_tile_new_titiler.py
test_get_tile_collection_returns_image (test.api.endpoints.test_wmts_get_tile_new_titiler.GetTileCase) ... ok
test_get_tile_no_browse (test.api.endpoints.test_wmts_get_tile_new_titiler.GetTileCase) ... [<FrameSummary file /Users/aimeebarciauskas/github/maap-project/maap-api-nasa/api/endpoints/wmts.py, line 131 in get>]
ok
test_get_tile_no_identifier (test.api.endpoints.test_wmts_get_tile_new_titiler.GetTileCase) ... ok
test_get_tile_returns_image (test.api.endpoints.test_wmts_get_tile_new_titiler.GetTileCase) ... ok
test_get_tile_returns_image3 (test.api.endpoints.test_wmts_get_tile_new_titiler.GetTileCase) ... ok
test_get_tile_returns_image4 (test.api.endpoints.test_wmts_get_tile_new_titiler.GetTileCase) ... ok

----------------------------------------------------------------------
Ran 6 tests in 5.601s

OK
```

So outstanding work is to update the deployment to use API Gateway + Lambda package, plus the CDK updates in https://github.com/MAAP-Project/maap-data-system-services/pull/33/files

**Comment by abarciauskas-bgse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update GCC UAT titiler deployment to match test environment](https://trello.com/c/38CE45tO/310-update-gcc-uat-titiler-deployment-to-match-test-environment)
