### ISSUE TITLE
Copy + Share the gedi cal/val database to GCC UAT

### ISSUE THREAD

**Issue by abarciauskas-bgse** [MAAP-Project/ZenHub#300]
Acceptance criteria: Replicate https://console.aws.amazon.com/rds/home?region=us-east-1#database:id=gedicalval;is-cluster=false in the GCC UAT environment

It should:
* Be in the MAAP data system services VPC
* Be accessible on port 5432 to the query service

Steps:
- [x] copy the latest GEDI RDS system snapshot to manual snapshot and share with GCC UAT
- [x] in GCC UAT, either create a database and "restore from snapshot" manually OR include the database creation in the automated deployment of https://github.com/MAAP-Project/maap-api-query-service

**Comment by abarciauskas-bgse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Replicate the gedi cal/val database in GCC UAT](https://trello.com/c/VTSl0wBm/275-replicate-the-gedi-cal-val-database-in-gcc-uat)

**Comment by markdboyd** [comment]
I had to manually "restore from snapshot" because trying to include the database creation in the automated deployment was not giving options to control the VPC, which is necessary in the GCC UAT environment where there are no subnets in the default VPC.

The database name is `gcc-dev-gedi-calval`
