### ISSUE TITLE
Deploy User Metadata Form (UMF) in GCC UAT

### ISSUE THREAD

**Issue by abarciauskas-bgse** [MAAP-Project/ZenHub#301]
Acceptance criteria:
* questionnaire.dit.maap-project.org is accessible instance of https://questionnaire.maap-project.org/ (UAH AWS account)
* questionnaire.uat.maap-project.org is accessible instance of https://questionnaire.maap-project.org/

Background
* The  UMF is a web form and ruby on rails backend application https://github.com/MAAP-Project/user-metadata-form
* It includes a postgres database configured here: https://github.com/MAAP-Project/user-metadata-form/blob/master/config/database.yml
* Previous deployment details are here: https://github.com/MAAP-Project/maap-cmr/wiki/MAAP-Data-System-Deployment#user-metadata-form-umf
* Users navigate to the user metadata form from the MAAP ADE (Eclipse Che) through the sidebar in the ADE "Share your data" link

Tasks for UAH AWS (dit environment):
- [x] Update the environments modify the UMF codebase to replace the `sit` with `dit` and add an option for `uat`
- [x] Write and document a script for building and pushing the user metadata form docker image to AWS ECR - this should take the `AWS_ACCOUNT_ID` as a parameter, see https://github.com/MAAP-Project/maap-cmr/wiki/MAAP-Data-System-Deployment#user-metadata-form-umf-1
    - I'm pretty sure we don't want to use this script https://github.com/MAAP-Project/user-metadata-form/blob/master/build-sit.sh.example as-is, I think we want to remove all of the references to those environment variables from the Dockerfile and from the build script and pass those environment variables at run time the same way we do for CMR (using AWS Secure Secrets). See https://github.com/MAAP-Project/maap-data-system-services/search?q=ssm and specifically https://github.com/MAAP-Project/maap-data-system-services/blob/d3b16df10737243c9ad71224e9485837cb783394/cmr-services.tf#L81. In this case I think the build script can be as simple as:
```bash
docker build -f docker/app/Dockerfile -t maap-umf:dit .
```
- [x] Include a new RDS instance in maap-data-system-services terraform code for the the user-metadata form
- [x] Include a new ECS service in maap-data-system-services which runs the the user-metadata form. This should replicate the CMR deployment, but with different ECR Image identifier. Note that:
    - There are some run-time environment variables as noted above we should add to SSM parameter store. These will need to be generated dynamically in the case of RDS database hostname.
    - This service can probably be in the same ECS cluster as the CMR, but we need to make sure that if the services are running on the same EC2 instance there is no port conflict (I don't think there is if UMF is running at 3000)

Tasks for UAT:
@slesaad has addressed all the tasks above and deployed to https://questionnaire.dit.maap-project.org/ and has opened PRs against maap-data-system-services and user-metadata-form, so once those PRs are merged we should:
* [x] Follow the deployment instructions in https://github.com/MAAP-Project/user-metadata-form/blob/260bfe814d7baccd9bbb0fc96b1756c84514182e/DEPLOYMENT.md to push the user-metadata-form ECR image to GCC UAT
* [x] Update the terraform deployment in GCC UAT with @slesaad changes from https://github.com/MAAP-Project/maap-data-system-services/pull/27/files
* [x] Update DNS in Route53 so that https://questionnaire.uat.maap-project.org points to the load balancer in GCC UAT
* Request an update to ade.uat.maap-project.org to point to the questionnaire.uat.maap-project.org

**Comment by abarciauskas-bgse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Deploy User Metadata Form in GCC UAT](https://trello.com/c/SrwWtWoj/274-deploy-user-metadata-form-in-gcc-uat)

**Comment by markdboyd** [comment]
Deployed the `maap-umf` image to GCC UAT. Submitted a PR with documentation updates:

https://github.com/MAAP-Project/user-metadata-form/pull/10

**Comment by markdboyd** [comment]
I had to recreate the entire maap-data-system-services deployment in GCC UAT with an environment name of `uat` for compatibility with the UMF deployment (it was easier in the long run than adding more variables to the TF code)

Everything seems to be back up and running, including CMR (https://cmr.uat.maap-project.org/search/collections).

UMF is deployed and the ECS task seems to be stable, but I don't know how to tell if it is up (https://maapds-uat-umf-service-lb-tf-1825167170.us-west-2.elb.amazonaws.com/). 

I also updated the route 53 config for both `cmr.uat.maap-project.org` and `questionnaire.uat.maap-project.org`, so those should both begin resolving correctly shortly

**Comment by abarciauskas-bgse** [comment]
@markdboyd thanks for this, the service is up https://questionnaire.uat.maap-project.org/ perhaps @slesaad can provide some advice on how to test that if you fill out the form you can look up the result?

I did have to make one chance which was to add port 2998 to the inbound rules for the security group. Could you make sure this is part of the terraform? https://us-west-2.console.aws.amazon.com/ec2/v2/home?region=us-west-2#SecurityGroup:groupId=sg-02c5c58539f0702d8

**Comment by markdboyd** [comment]
Here is that PR @abarciauskas-bgse : https://github.com/MAAP-Project/maap-data-system-services/pull/34

**Comment by abarciauskas-bgse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Automate deployment of user metadata form](https://trello.com/c/KZhiKtk3/43-automate-deployment-of-user-metadata-form)
