### ISSUE TITLE
Update links in all environments to point to the new ESA portal

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#304]
Includes our dev/uat/ops portals and the scimaap.net landing page, hosted at MSFC I believe.

```             
We noticed that all links that redirect to ESA platform from your MAAP points to the old pilot map. Could you please update it to point on the v1 platform ? The new link is here : https://liferay.val.esa-maap.org/
```

**Comment by gchang** [comment]
Also the forum links in the portal as well.

**Comment by abarciauskas-bgse** [comment]
@gchang where can I help make a change? I'm not sure what component we manage that links to https://liferay.val.esa-maap.org/

**Comment by gchang** [comment]
https://scimaap.net I believe is hosted on S3 as a static web page on an MSFC bucket. It's the ESA link in the bottom right when users click the ESA logo.

**Comment by abarciauskas-bgse** [comment]
Apologies for the delay, I was confused because I don't recall setting up this DNS, it's in GCC UAT so perhaps you can help @gchang, I am getting

**Comment by gchang** [comment]
@abarciauskas-bgse Thanks for looking at that. I saw your slack message and decided to investigate and discovered that JPL is actually hosting it via our www.maap-project.org server. My recollection is that we opted to use MSFC’s S3 websites to host this and because JPL’s account prohibit that feature. However, for one reason or another, we ended up hosting it instead. I’ll go ahead and update the HTML on the server. I apologize for the confusion.

We will need to update the route53 to point to the ops ec2 server or its s3 website, but not as urgent.

@marjo-luc Will still need to go through our portals and update.

**Comment by gchang** [comment]
@abarciauskas-bgse P.S. I don't remember how the GCC DNS was set up either.

**Comment by gchang** [comment]
@marjo-luc bump

**Comment by marjo-luc** [comment]
I believe I need gcc access before I can tackle this ticket.

**Comment by gchang** [comment]
Some of the links should be editable by just logging into the wordpress instances and updating pages/menu items.

**Comment by marjo-luc** [comment]
I've updated the Communities link.

The footer links are pending gcc access.
