### ISSUE TITLE
Notebook to visualize field data

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#314]
L2-VIZ-180
The MAAP shall support visualization of field data.

**Comment by wildintellect** [comment]
In progress from [V1 F2F demo](https://github.com/MAAP-Project/maap-documentation/blob/abarciauskas-bgse_gedi-demo/docs/source/query/gedicalval-demo_V1_F2F.ipynb) started by @abarciauskas-bgse
