### ISSUE TITLE
Can't install some pkgs in conda env, DEV 

### ISSUE THREAD

**Issue by wildintellect** [MAAP-Project/ZenHub#322]
**Describe the bug**
Conda env mismatch break conda install. 

**To Reproduce**
1. Create a MAAP basic workspace
2. `conda install -c conda-forge geopandas rasterio`

**Expected behavior**
Conda should install the packages. It was working a couple of weeks ago.

**Screenshots**
```
ResolvePackageNotFound: 
  - conda=4.7.12
```

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Based on the [ADE images ](https://repo.nasa.maap.xyz/root/ade_base_images/blob/vanilla/docker/Dockerfile )in gitlab the conda version should be 4.7.12 but `conda --version` returns 4.9.2
This is using the ADE hosted at JPL, should check if the new GCC deployment has this issue.
It's doubly odd that `rasterio` can't be installed, as it's already installed apparently.

For future documentation, since we're going to be recommending that users use conda to add packages we should link to the base images that correspond to the workspace options. It's unclear to users what packages are already installed, and it's assumed that none are, except when custom environments have been built on request. Another todo, instructions on how to build a clean environments.yml that could be applied to the base image to meet an algorithm need, and a workflow for building those environments before running DPS jobs to avoid reinstalling every job. Also if we're using conda-forge are we doing a strict limit, should be documented.

Workaround `pip install` the packages that are needed. I attempted to create a new conda env, and install maap-py and conda libs to that, was unable to get both geopandas and rasterio to install to the same conda env.

**Comment by wildintellect** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cloud Optimized Data access example](https://trello.com/c/FRm2P71P/285-cloud-optimized-data-access-example)

**Comment by mayadebellis** [comment]
Did some tracking of the conda version throughout the build process:
- Miniconda image we start with is v4.7.12
- The final vanilla base image is v4.9.1
- In the `jupyter-image` we specify v4.7.12 for our first line of conda installs, but not for the second
- Final `jupyter-image` has conda v4.9.2

Now will make sure that we stay at v4.7.12 throughout. Will likely have to specify this on all conda install lines in our build to ensure it doesn't upgrade conda.

**Comment by mayadebellis** [comment]
@wildintellect if that trello link is for me - I don't have access to it

**Comment by wildintellect** [comment]
The Trello link is automated to a board the data team uses, don't worry about it.

If we're going to align on a version should we go with the newer version 4.9.x would be fine for the Boreal work? Seems down the line we'll need to account for this to allow for upgrades but at the same time allow for preserving old environments at algorithm publication time. Once the system for allowing users to create custom workspace images comes about it should be easier to tag/pin, and allow the base image to be refreshed over time.

**Comment by mayadebellis** [comment]
For now I think it is easier to align on 4.7.12. As we are migrating to gcc and changing a lot of configurations I am hesitant to add more things into the mix. Things should be aligned now on the gcc environments. In the pilot ops environment, these inconsistencies will still be there - I didn't want to update the stacks to point to our latest images as some of the changes we've made will break features in pilot ops. 

Once we are up and running on gcc ops hopefully we will have more time to address the base image versioning and user customizations!
