### ISSUE TITLE
Dynamic Tiler access to ADE S3 storage

### ISSUE THREAD

**Issue by wildintellect** [MAAP-Project/ZenHub#323]
**Is your feature request related to a problem? Please describe.**
Allow Dynamic Tiler (Titiler) service access to maap-user files to allow for tiling of in-progess & dps output datasets as an XYZ/WMTS layer in Jupyter based MAAP widgets. Without this there's no way to visualize very large outputs in notebooks.

**Describe the solution you'd like**
AWS permissions to allow Lambda access to specific S3 buckets/paths - read-only

**Describe alternatives you've considered**
Deploying a 2nd Lambda specifically for internal data.

**Additional context**
So the alternative solution is around limiting accidental data leakage. If we want to restrict access to not quite published data, then we'll need some more specific permissions. This is more complicated in the Pilot env since the ADE/DPS are in a different account from the MAAP Data Store (UAH). We also want people to submit user-shared data, and public tiling of data into services is an incentive, however users need to be able to review the data before that step.

Examples:
* Unmesh made a VRT of COGs
* Boreal project is making 2 tiled layers of Landsat and Elevation bands.

**Comment by gchang** [comment]
In the OPS and UAT envs, since we're all under the same AWS account, shouldn't the Lambda have access to the S3 bucket already via IAM roles? In the (old) dev environment, we were able to accomplish something similar to this with a bucket policy that allowed the MSFC acct number to access the JPL bucket.

**Comment by wildintellect** [comment]
Yes in OPS, UAT likely access will be handled. There is still a policy question, if the Tiler should be allowed to serve data not in CMR outside the ADE, perhaps  a question for @kaulfusa @kbugbee1
However what about DEV/DIT? I thought it was JPL can access MSFC, does it go both ways? I just wanted to make sure it was both ways, will test, any hints about what maap IAM has access to JPL bucket? cc: @abarciauskas-bgse

**Comment by abarciauskas-bgse** [comment]
Thanks for opening this @wildintellect - if I understand correctly I think we need 2 separate tickets:

1. (trello card for the data team) Should the tiler be allowed to serve data not in the CMR outside the ADE?
2. Assuming the answer to (1) is yes, create a bucket policy for the ADE storage bucket to permit access from the UAH AWS DIT environment. Then test (create notebook demonstrating) DIT environment has the expected functionality to visualized data in ADE S3 storage as higher environments

@wildintellect does that sound right to you?

**Comment by wildintellect** [comment]
@abarciauskas-bgse that sounds right.
If the answer to public access is no (we might need to ask UWG about expectations), then we'd need a more elaborate system to allow internal use.

**Comment by abarciauskas-bgse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dynamic Tiler access to ADE S3 storage](https://trello.com/c/fwBj8j5U/332-dynamic-tiler-access-to-ade-s3-storage)

**Comment by abarciauskas-bgse** [comment]
@gchang @bsatoriu so I think we just need a bucket policy on the ADE S3 workspace bucket to permit access to the UAH AWS account. If you agree and someone on the JPL team can pick this up, I can share the UAH AWS account number over email or slack (unless you already have it)

**Comment by wildintellect** [comment]
Just noting this also impacts @gllewellyn19 work on ADE data viz. cc: @mayadebellis 
We'll also want to make sure the lambdas in each GCC env have access their respective ADE buckets - I think in initial testing in Ops this is not currently working.

**Comment by gchang** [comment]
@wildintellect Have the lambdas been assigned roles to access the S3 buckets? If you're in GCC and trying to access the buckets in GCC, IAM roles should be sufficient.

Also, the UAH account is now able to access the pilot ops (JPL) bucket. I added the UAH account to our bucket permissions and @abarciauskas-bgse confirmed.

**Comment by abarciauskas-bgse** [comment]
Yes! @gchang helped create a bucket policy for all AWS resources, providing policy as example below.

@wildintellect let me know if you verify the test environment via the visualizing a workspace file using its S3 location using the dynamic tiler in the test account.

```json
{
    "Version": "2012-10-17",
    "Id": "S3PolicyId1",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::<UAH_AWS_ACCOUNT_ID>:root"
            },
            "Action": "s3:GetObject",
            "Resource": [
                "arn:aws:s3:::maap-ops-dataset/*",
                "arn:aws:s3:::maap-ops-dataset"
            ]
        }
    ]
}
```

**Comment by wildintellect** [comment]
I'll try to get to it today, maybe @gllewellyn19 can test this using the Pilot Ops Tiler endpoint. I don't have specifics on what wasn't working in Ops, because I think we tried it, will see if there's an easy test to verify.

**Comment by gllewellyn19** [comment]
@wildintellect I tried passing https://maap-ops-workspace.s3.amazonaws.com/graceal/N45W101.SRTMGL1.tif into https://8e9mu91qr6.execute-api.us-east-1.amazonaws.com/production/docs at /production/tiles/{z}/{x}/{y}.pbf and I got the following error (while using 1, 1, 1 for x, y, z): 
{
  "errorMessage": "HTTP response code: 403"
}
I believe this means the permissions are not working for the Tiler Pilot Ops

**Comment by wildintellect** [comment]
@gllewellyn19 
maap-ops-workspace is in Ops tiler would be https://jqsd6bqdsf.execute-api.us-west-2.amazonaws.com/
if you're in Pilot Ops the bucket is s3://maap-ops-dataset/

**Comment by wildintellect** [comment]
I think these permissions are now working on Pilot Ops:
```
aws --profile=maap s3 ls maap-ops-dataset/alexdevseed/
```
Now on to troubleshooting why the Tiler doesn't like it.

**Comment by gllewellyn19** [comment]
@wildintellect My bad! I now changed to pass https://maap-ops-dataset.s3.amazonaws.com/graceal/gebco_08_rev_elev_A1_grey_geo.tif into https://8e9mu91qr6.execute-api.us-east-1.amazonaws.com/production/docs at /production/tiles/{z}/{x}/{y}.pbf and I still got the following error (while using 1, 1, 1 for x, y, z):
{
"errorMessage": "HTTP response code: 403"
}

**Comment by wildintellect** [comment]
Something isn't right with the Tiler execution role, I'm not getting to work either. Going to look into it tomorrow. FYI since this isn't public data you have to use the s3:// urls.

**Comment by abarciauskas-bgse** [comment]
Reposting what I shared in slack in #maap-shared-dev:

>I think that what is going on is when you hit the file with https it works (given the file is publicly available) but for you to hit the URL with S3 it will fail unless the AWS Lambda has a role with the AmazonS3FullAccess AWS managed policy. This way it can inherit S3 access enabled for the AWS "root" account as George added.
>
>I've added this to the role (hai-tiler-lambda-dev-haitilerlambdadevlambdaServic-1LKS46JOQOC6G) and now the vsis3 request works for me.
>
>Alex mentioned that it was already working with data in the same account but I have to assume that's because the permissions for the lambda accessing data in the same AWS account are more open / more permissive.

Let me know if it's working for you all and sorry I didn't jump in sooner!

**Comment by wildintellect** [comment]
Confirmed, now working in JPL/UAH cross account.
Also confirmed GCC Ops within account works too.
