### ISSUE TITLE
Can't clone gitlab repos

### ISSUE THREAD

**Issue by lauraduncanson** [MAAP-Project/ZenHub#327]
**Describe the bug**
Trying to clone gitlab repos. Was failing to clone gedipy_maap so started a brand new project in the new icesat2_boreal group and could not clone icesat2nb211_dps

Error: fatal: bad config line 1 in file /projects/r2d2/icesat2nb211_dps/.git/config

**To Reproduce**
In gitlab, create a project. Clone the project:
git clone git@mas.maap-project.org:icesat2_boreal/icesat2nb211_dps.git

**Expected behavior**
Clones gitlab repo

**Comment by sujen1412** [comment]
Currently, Cloning into the user workspaces (/projects/<username>) does not work due to the nature of the underlying filesystem used. 

Try cloning the the same to any other place under /projects/

**Comment by lauraduncanson** [comment]
We then run into a permissions issue:

git@mas.maap-project.org: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by sujen1412** [comment]
Try using https://mas.maap-project.org/icesat2_boreal/icesat2nb211_dps.git.

You may need to create a password first. 
Top right user icon --> Settings --> Password

**Comment by wildintellect** [comment]
@lauraduncanson reports that it's working with this info. I suggest we add something to the FAQ in the MAAP docs regarding gitlab interactions.

Here's a summarized version of the solution:
1. In gitlab, verify you have a password set. Go to user settings, top right user icon --> Settings --> Password
2. Use the **Clone with HTTPS** url
3. git clone in the top level /projects/ folder, do not try to clone inside your user folder or maap-users (in ops this will be *bucket* folders)

**Comment by sujen1412** [comment]
cc @marjo-luc  - are you the one updating user docs/FAQs ?
