### ISSUE TITLE
Add Platform Technical Documentation

### ISSUE THREAD

**Issue by abarciauskas-bgse** [MAAP-Project/ZenHub#329]
**Is your feature request related to a problem? Please describe.**
All the user documentation is located on a single entry point

**Describe the solution you'd like**
Add "Platform Technical Documentation" (here https://www.maap-project.org/user-guides/) to docs.maap-project.org

**Describe alternatives you've considered**
Not applicable as prior decision has been made to consolidate on docs.maap-project.org

**Additional context**
The FAQ on https://www.maap-project.org/user-guides/ has already been added to docs.maap-project.org but there might be a little bit more work to convert the Platform Technical Documentation since it's stored in github markdown files.

cc @spa0002

**Comment by abarciauskas-bgse** [comment]
@marjo-luc @gchang let me know if this sounds reasonable to you

**Comment by marjo-luc** [comment]
I created a pull request with the updated technical documentation:
https://github.com/MAAP-Project/maap-documentation/pull/66

It may be worth tagging up briefly to review the organization of the content on docs.maap-project. It looks like there are at least two distinct use cases -- one where the user is not familiar with the platform components and just wants to understand how to perform high-level actions i.e. 'search', 'query', 'visualize', etc.; and another where the user _is_ familiar with the components and is looking for detailed documentation specific to said component.
