### ISSUE TITLE
Presigned S3 URLS are throwing error 

### ISSUE THREAD

**Issue by oddes** [MAAP-Project/ZenHub#332]
Steps to Reproduce:

1. Login to Che in OPS environment
2. Open EDSC
3.  For a dataset in Earthdata Search Client and find the S3 link that can be shared with anyone.
4. Create a Presigned S3 URLS as shown in attached screenshot, and try to Open the URL. you will notice Access Denied Error:
![Screen Shot 2021-05-17 at 3.04.13 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/cbdcbe63-380d-431c-b580-17aa2a4dd98e)

**Comment by gchang** [comment]
This is currently captured in #273. Please watch that tix!
