### ISSUE TITLE
Deploy cmr-stac proxy API to MAAP AWS account

### ISSUE THREAD

**Issue by abarciauskas-bgse** [MAAP-Project/ZenHub#336]
**Acceptance Criteria**
A STAC API endpoint which lists collections in MAAP CMR

**Describe the solution you'd like**
- [x] Fork https://github.com/nasa/cmr-stac
- [x] Follow instructions in https://github.com/nasa/cmr-stac to deploy to the UAH "MAAP Test" AWS account (AWS account number that starts with `53`)
- [x] When deploying `--cmr-search-host <cmr-search-host>` should be cmr.maap-project.org

**Describe alternatives you've considered**
Using CMR API directly to generate mosaic is also possible but requires more ground work and also supports less potential future users, since STAC is a more common and open geospatial metadata standard and API.

**Comment by abarciauskas-bgse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Deploy cmr-stac against cmr.maap-project.org](https://trello.com/c/VVSuE2mt/342-deploy-cmr-stac-against-cmrmaap-projectorg)

**Comment by abarciauskas-bgse** [comment]
@slesaad I looked into the deployment and was able to get a stack deployment past the error you mentioned by removing some of the lines that depend on a stack that already exists:

https://github.com/nasa/cmr-stac/compare/master...abarciauskas-bgse:abarciauskas-bgse_maap-changes?expand=1

I got there by reading https://seed.run/docs/serverless-errors/stack-with-id-does-not-exist.html#:~:text=A%20couple%20of%20common%20causes,app%20has%20been%20manually%20removed. (I think we are in situation #3 where the stack does not exist yet so we can't have those ${cf:stage...} variables

I'm running into a different error in the stack deployment but I think it's something we can fix with some development of serverless.yml... see https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/events?filteringStatus=active&filteringText=&viewNested=true&hideStacks=false&stackId=arn%3Aaws%3Acloudformation%3Aus-east-1%3A532321095167%3Astack%2Fcmr-maap-cmr-stac-api-uat%2F8e87fbf0-b979-11eb-9f92-0e0fe8a96c03

**Comment by slesaad** [comment]
Yeah, no, I did try that already. But I suppose we actually do need those resources that we removed.
The error in my terminal says:
`An error occurred: SearchDashapiSubscriptionFilter - Property DestinationArn cannot be empty..`
And I didn't know what values they are supposed to be.
Thus, I was asking if I should start diving into that or if you had a better solution.

**Comment by abarciauskas-bgse** [comment]
Ah sorry didn't realize you had try this already - ya if you could dig into what's required to set up a new stack that would be great. I'll also try and connect you with Matt Hanson.
