### ISSUE TITLE
ATL08v4 data request

### ISSUE THREAD

**Issue by kaulfusa** [MAAP-Project/ZenHub#338]
**Dataset Name**
ATLAS/ICESat-2 L3A Land and Vegetation Height, Version 4

**Dataset Description**
This data set (ATL08) contains along-track heights above the WGS84 ellipsoid (ITRF2014 reference frame) for the ground and canopy surfaces. The canopy and ground surfaces are processed in fixed 100 m data segments, which typically contain more than 100 signal photons. The data were acquired by the Advanced Topographic Laser Altimeter System (ATLAS) instrument on board the Ice, Cloud and land Elevation Satellite-2 (ICESat-2) observatory.

**Requestor name/affiliation**
Aaron Kaulfus/MSFC - MAAP Data Team

**Platform/Instrument/Method**
ICESat-2 / ATLAS / Satellite LIdar

**URL or DOI to dataset description**
https://nsidc.org/data/atl08

**URL to download or access data**

**Data License**
*Is the data openly available?*

**Intended science use case**
*Please describe how you intend to use the data, or the expected relevance to MAAP users.*

## Optional

**Approximate size of data**
*Please estimate of how many GB/TB/PB the data is.*

**Additional information**
*Any additional info you think is relevant, possibly including spatial or temporal subset if applicable.*

**Comment by wildintellect** [comment]
Merge with #388
