### ISSUE TITLE
Remove download granules options from MAAP EDSC

### ISSUE THREAD

**Issue by abarciauskas-bgse** [MAAP-Project/ZenHub#341]
**Describe the bug**
Earthdata Search Client download granules feature does not work.

**To Reproduce + Expected behavior**
Navigate to search.maap-project.org and search.earthdata.nasa.gov and compare results.
* in maap-project.org version the download icon on each granule is greyed out --> this icon should be removed
* in maap-project.org version, @gchang has removed the download all button with CSS, we should remove it all together in the EDSC codebase for maap-project.org

**Screenshots**
maap-project.org version:
![Screen Shot 2021-05-24 at 1 50 12 PM](https://user-images.githubusercontent.com/15016780/119406024-067ef800-bc97-11eb-80af-90dc72ac7f27.png)
earthdata.nasa.gov version:
![Screen Shot 2021-05-24 at 1 50 25 PM](https://user-images.githubusercontent.com/15016780/119406075-1565aa80-bc97-11eb-92a0-9394b8b8822f.png)

**Comment by gchang** [comment]
Also related is the "Earthdata Login" button which doesn't make sense when used in MAAP. On https://search.maap-project.org/search it is removed, but in https://search.uat.maap-project.org/search and https://search.ops.maap-project.org/search, that button is still there.
