### ISSUE TITLE
MAAP Dynamic Tiler includes mosaicjson endpoints

### ISSUE THREAD

**Issue by abarciauskas-bgse** [MAAP-Project/ZenHub#342]
**Problem:**
We already have an instance of titiler deployed that should be able to tile using an existing mosaicjson _but_ it does not include mosaicjson layer management we need for MAAP.

**Proposed solution:**
* an API endpoint `POST /mosaicjson` create - given a list of file urls, generates a mosaicjson dictionary and uploads it to dynamoDB and returns a layer name
* an API endpoint `POST /mosaicjson?stac_api_endpoint=` create - given a set of stac parameters and stac endpoint generates a mosaicjson dictionary and uploads it to dynamodb and returns a layer name
* Internals of `create`:
   * If passed a list of file URLs use `MosaicJSON.from_urls` or the equivalent to create a mosaic json dictionary
   * If passed a `stac_api_endpoint` use the code from https://github.com/NASA-IMPACT/dashboard-api-starter/pull/8 to generate a list of files from the STAC API query results
   * Mosaic json dict is then uploaded DynamoDB. I'm not sure exactly how this works in cogeo.xyz but it seems like these lines are critical parts: https://github.com/developmentseed/cogeo.xyz/blob/68703033ec2231fb47a7f5e311515fb650356dad/backend/app/routes/mosaic.py#L123 and https://github.com/developmentseed/cogeo.xyz/blob/master/backend/app/dependencies.py#L39, presumably there are some internals of `mosaic.write` which uploads mosaic to a layername which I assume is a key pointing to a dynamoDB table row

1. Fork titiler into NASA-IMPACT github organization
2. Add dynamodb storage of mosaicjson to create mosaic endoint(s) and return a layer name (e.g. like `mosaic.write` in cogeo.xyz)
3. Verify the layername works to call `/mosaicjson/{layername}/tiles/{z}​/{x}​/{y}@{scale}x.{format}`

**Describe alternatives you've considered**
* Using the deployed instance api.cogeo.xyz, as done in the current PR in dashboard-api-starter.
* Deploying api.cogeo.xyz codebase as-is for a new deployment which can basically be cogeo.xyz "out of the box" but this give us more code than we need and duplicates titiler endpoints
* putting this code in dashboard-api-starter - reason for this is we already are putting our mosaicjson generation code there. Not doing this to separate concerns of dynamic tiling from dashboard-api code which should really be more specific to the dashboard needs. Eventually we might not need the dashboard-api-starter if the dashboard just proxies to other services...

**Questions:**
* does the existing Titiler know how to tile a `TileMatrixSetId` using a layername that refers to a layer in dynamodb?

**Comment by abarciauskas-bgse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add mosaicjson layer management to MAAP titiler deployment](https://trello.com/c/pZH9mk1E/347-add-mosaicjson-layer-management-to-maap-titiler-deployment)

**Comment by philvarner** [comment]
Tuesday, we throught that TileMatrixSetId was the layername in these URLs -- it's actually an OGC thing that's always WebMercatorQuad (or something like that). The location of the MosaicJSON file is actually passed to the tile endpoint via the `url` parameter, e.g., `http://example.com/mosaic/tiles/{z}/{x}/{y}@1x?url=http://example.com/mymosaicjson.json`

**Comment by philvarner** [comment]
I'd like to propose a more RESTful API for mosaic creation. 

Retrieval of an already-created Mosaic entity would be from:

```
GET /mosaics/{mosaic_id}
```

This would only contain Links to other sub-resources, like the actual MosaicJSON, which could be retrieved from:

GET /mosaics/{mosaic_id}/mosaicjson

with a Link like

```
    {
      "href": "http://example.com/mosaics/34ab724c-3cd3-4e4d-9384-e215afde3073/mosaicjson",
      "rel": "mosaicjson",
      "type": "application/vnd.mosaicjson+json",
      "title": "MosiacJSON"
    },
```

Creation would be done via:
POST /mosaics

There would be several options driven by Content-Type header and the body:

Create with MosaicJSON:

```
POST /mosaics
Content-Type empty, application/vnd.mosaicjson+json, or application/json
{
  "attribution": "(c) Digitalglobe",
  "quadkey_zoom": 10,
  "bounds": [
    34.8046875,
    -20.3034175184893,
    35.5078125,
    -19.3111433550646
  ],
  "center": [
    35.15625,
    -19.807280436777,
    10
  ],
  "minzoom": 12,
  "tiles": {
    "3001322011": [
      "s3://opendata.remotepixel.ca/dg_post_idai/2019_03_20/0201110.tif",
      "s3://opendata.remotepixel.ca/dg_post_idai/2019_03_20/0201111.tif"
    ],
    "3001322013": [
      "s3://opendata.remotepixel.ca/dg_post_idai/2019_03_20/0023310.tif",
      "s3://opendata.remotepixel.ca/dg_post_idai/2019_03_20/0023311.tif",
      "s3://opendata.remotepixel.ca/dg_post_idai/2019_03_20/0023312.tif"
    ],
    ...
  },
  "version": "0.0.1",
  "description": "Digitalglobe post Idai cyclone data.",
  "maxzoom": 18,
  "mosaicjson": "0.0.2",
  "name": "dg_post_idai"
}'
```

Create with STAC API query:

```
POST /mosaics
Content-Type application/vnd.stac-api-query+json
{
  "stac_api_root": "https://earth-search.aws.element84.com/v0",
  "datetime": "2021-04-20T00:00:00Z/2021-04-21T02:00:00Z",
  "collections": [
    "sentinel-s2-l2a-cogs"
  ],
  "bbox": [ 20, 20, 21, 21 ]
}
```

Create with list of files:

```
POST /mosaics
Content-Type application/vnd.files+json
{ 
    "urls": [
      "s3://opendata.remotepixel.ca/dg_post_idai/2019_03_20/0023310.tif",
      "s3://opendata.remotepixel.ca/dg_post_idai/2019_03_20/0023311.tif",
      "s3://opendata.remotepixel.ca/dg_post_idai/2019_03_20/0023312.tif"
   ],
    "minzoom": "3",
    "maxzoom": "20"
}
```

All 3 create paths would ultimately result in a MosaicJSON file that would be stored in DynamoDB. They would then all return the same thing: a Location header referencing the GET endpoint and a body containing the same entity that the GET endpoint returns. Most relevant here is the `tiles` Link that constructs a proper URL to the tiles endpoint using the mosaicjson representation of this resource:

```
{
  "id": "34ab724c-3cd3-4e4d-9384-e215afde3073",
  "links": [
    {
      "href": "http://example.com/mosaic/mosaics/34ab724c-3cd3-4e4d-9384-e215afde3073",
      "rel": "self",
      "type": "application/json",
      "title": "Self"
    },
    {
      "href": "http://example.com/mosaic/mosaics/34ab724c-3cd3-4e4d-9384-e215afde3073/mosaicjson",
      "rel": "mosaicjson",
      "type": "application/vnd.mosaicjson+json",
      "title": "MosiacJSON"
    },
    {
      "href": "http://example.com/mosaic/mosaics/34ab724c-3cd3-4e4d-9384-e215afde3073/tilejson.json",
      "rel": "mosaicjson",
      "type": "application/json",
      "title": "TileJSON"
    },
    {
      "href": "http://example.com/mosaic/tiles/{z}/{x}/{y}@1x?url=http://example.com/mosaic/mosaics/34ab724c-3cd3-4e4d-9384-e215afde3073/mosaicjson",
      "rel": "tiles",
      "type": "application/json",
      "title": "Tiles Endpoint"
    }
  ]
}
```

Also, there should be a `PUT /mosaics/{id}` endpoint that behaves the same as POST, but instead overwrites an existing mosaic resource.

**Comment by abarciauskas-bgse** [comment]
Thanks @philvarner I think this makes sense to me. I'm not familiar with creating and handling of new custom content types - is there anything to be aware of in terms of client or server limitations or constraints when using custom types? Does this potential raise concerns with different servers or clients which by default might be expecting a vanilla "application/json" content type header? Or perhaps this is not a problem because the content itself is still valid json.

Also curious what @vincentsarago thinks but this looks like a nice API to me so far.

**Comment by vincentsarago** [comment]
👍 @philvarner this looks great

**Comment by philvarner** [comment]
> Thanks @philvarner I think this makes sense to me. I'm not familiar with creating and handling of new custom content types - is there anything to be aware of in terms of client or server limitations or constraints when using custom types? Does this potential raise concerns with different servers or clients which by default might be expecting a vanilla "application/json" content type header? Or perhaps this is not a problem because the content itself is still valid json.

I think it's pretty common to set content-type, so it shouldn't be a problem in any language/library.

For example, with requests, using the `json` keyword instead of `data` will automatically set the Content-Type header to `application/json`.

```python
requests.post(url, json=payload)
```

so now, a client just has to add a header:
```python
response = requests.post(
            url="http://localhost:8000/mosaicjson/mosaics",
            headers={
                "Content-Type": "application/vnd.stac-api-query+json",
            },
            json="""{
  \"stac_api_root\": \"https://earth-search.aws.element84.com/v0\",
  \"collections\": [
    \"sentinel-s2-l2a-cogs\"
  ]
  ]
}""")
```

A key piece is that we provide good examples, since most people are going to just copy those to start with, and that will clarify way more than just the text description. I'm going to create a Notebook that tests this and will document it well.

**Comment by philvarner** [comment]
@abarciauskas-bgse I put up a notebook that demonstrates the api:

https://github.com/NASA-IMPACT/titiler/blob/philvarner/mosaicjson-stac/docs/using_mosaics_api.ipynb

Using a dict in memory to store the mosaicjsons, i got it to render in a map (in that notebook):

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/124996/119865873-26f2c080-beea-11eb-90cd-65027143a5c3.png">

I have a bunch of smaller todo's to follow up for that code, but the only major thing that's missing right now is persisting them to DynamoDB (or S3?).

**Comment by abarciauskas-bgse** [comment]
So at the moment the API is storing the mosaics in memory?

**Comment by philvarner** [comment]
> So at the moment the API is storing the mosaics in memory?

yes, just in a dict

**Comment by philvarner** [comment]
One of the things I hadn't realized yesterday, until I got the persistence working, is that cogeo.xyz has a set of endpoints like:

```
/mosaicjson/{layername}/tiles/{z}/{x}/{y}
```

so instead of using this as the tiler endpoint (where you have a generic endpoint that takes that MosaicJSON `url` as a parameter):

```
/mosaicjson/tiles/{z}/{x}/{y}?url=https://api.cogeo.xyz/mosaicjson/{layername}
```

The point of this is that for very large mosaicjson definitions, like the 40K one we're looking at for boreal, the server can pull only the part of the mosaicjson file it needs from DynamoDB by layername+quadkey, instead of having to retrieve the **entire** (possibly huge) mosaicjson file by url for **each** tile.

I'm going to add this endpoint, otherwise I think we're going to run into performance bottlenecks really quickly.

**Comment by abarciauskas-bgse** [comment]
👍🏽  sorry I didn't mention how there are 2 options before @philvarner, still learning the API myself! I was actually expecting we use the former option (passing the `{layername}` in the path and doing a dynamodb lookup) but I'm glad to learn there is a URL option as well in case the mosaicjson is not stored in dynamoDB (i.e. we want to pass a file URL for testing purposes)
