### ISSUE TITLE
Create onboarding documentation

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#354]

**Comment by bsatoriu** [comment]
Onboarding guide commit: https://github.com/MAAP-Project/maap-documentation/commit/646d77e98d21d94a2ae7bf3bfd36175e48c7c58e

**Comment by oddes** [comment]
@bsatoriu "DPS Algorithms" Section, all the subsection are pointing to List algorithm , needs to be updated.

**Comment by bsatoriu** [comment]
> @bsatoriu "DPS Algorithms" Section, all the subsection are pointing to List algorithm , needs to be updated.

@oddes can you check if this is still an issue and, if so, post the link to the DPS Algorithms section you're referring to? Thank you.

**Comment by oddes** [comment]
1. Please see the screenshot attached to show the section:
2. Here is the sample link: it supposed to show describe algorithm but it is going to List algorithm.![DPS_section.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/dcb036e7-1443-40ce-a927-9d62f1bfde6d) 
https://github.com/MAAP-Project/maap-jupyter-ide/blob/master/user_guides/algorithms.md#describe-an-algorithm

**Comment by oddes** [comment]
Looks Good.
