### ISSUE TITLE
ESA link is not working on the NASA MAAP web portal

### ISSUE THREAD

**Issue by oddes** [MAAP-Project/ZenHub#358]
Steps:

1. Navigate to the https://ops.maap-project.org/
2. try to login with ESA, throwing following error:

{"error":"invalid_request_redirect_uri","error_description":"The redirect_uri in the Authorization Request does not match any of the Client's pre-registered redirect_uris.","state":"TST-124-fEsfFv-C-MK5lptNvUZ5XFDmv4fMIrUH"}

**Comment by gchang** [comment]
Currently the ESA cert for Gluu has expired, so it's not even connecting.

**Comment by gchang** [comment]
The URL to the Gluu server has changed, but the existing oauth keys do not work. Will need to coordinate with ESA servers and environments are correct.

**Comment by gchang** [comment]
Still a problem, but different error. Need to confirm with ESA
```
    "reason": "Unable to find client.",
    "error_description": "The client is not authorized to request an access token using this method.",
    "state": "TST-220-R2GKfkUBtK-O4SRzcvGfppDT4kUtFjWy",
    "error": "unauthorized_client"
}
```

**Comment by gchang** [comment]
Same issue as #291
