### ISSUE TITLE
Ops deleting conda environments/ roots

### ISSUE THREAD

**Issue by gllewellyn19** [MAAP-Project/ZenHub#370]
In order to implement my function load_geotiffs, I needed to create a conda environment (maap-ade) in Ops so I could run a notebook with that environment as the root. I was using a notebook with that root on Thursday (7/1). When I tried to open that notebook on Tuesday (7/6), I was prompted to select the kernel of the notebook and maap-ade was not an option. When I try to run the command `conda activate maap-ade`, it says that environment cannot be found. I also cannot see my conda environment when launching a new notebook as shown below:

![image.png](https://images.zenhubusercontent.com/60b0015d86f9229fe5c8c52f/3aea736e-bb34-47c9-aa18-204e9395e0ba)

**Comment by gllewellyn19** [comment]
Note this error does not occur in Pilot ops

**Comment by gchang** [comment]
Did you happen to stop the environment over the weekend or was it left on? If you did stop the workspace, then yes, it will get rid of everything outside of your home directory (/projects) as it's starting up a new docker image. If you didn't stop it, we'll need to investigate whether it stopped itself. There's a Che configuration that controls auto-shutdowns, but it should be disabled in our installation.

**Comment by gllewellyn19** [comment]
Answered in MAAP meeting (sorry George just saw this message), but for people reading this thread I did not stop my workspace over the weekend.

Update: when I logged onto MAAP Ops this morning, my conda environment in my workspace still existed

**Comment by gchang** [comment]
The next time it happens, try running `uptime` in the terminal to see if the VM actually restarted.

**Comment by gllewellyn19** [comment]
Update on this: My workspace wasn't working and was taking a long time to load a line that I know shouldn't have taken a long time. I exited out of the MAAP ops tab, and when I went back to [https://ade.ops.maap-project.org/](https://ade.ops.maap-project.org/), there was a gray circle next to my workspace. My conda environment had been deleted which I know is standard behavior since the workspace stopped. 

When I run uptime, I get this image and I am not sure if this is right since my workspace just restarted:
![image.png](https://images.zenhubusercontent.com/60b0015d86f9229fe5c8c52f/3c2f4b0d-1b6a-4da1-81d4-f2f6dd02a679)

Note that I took this image after I started basic-7lkcd again, but I did not stop the other 2 workspaces. 
![image.png](https://images.zenhubusercontent.com/60b0015d86f9229fe5c8c52f/a400b965-8159-4c04-8a7f-a58743ea43a5)

**Comment by gllewellyn19** [comment]
Another update: This is what my Ops workspace looked like this morning:

![image.png](https://images.zenhubusercontent.com/60b0015d86f9229fe5c8c52f/4c52197e-8b27-495a-9966-30902e11fc16)

Even more workspaces have been shut down (but luckily `basic-7lkcd` is still running which is where I have been doing my work in my conda environment).

When I run uptime in one of these newly shut down workspaces,
![image.png](https://images.zenhubusercontent.com/60b0015d86f9229fe5c8c52f/fa65d248-4c64-4327-99d2-793f69305661)

**Comment by gchang** [comment]
@gllewellyn19 Do you know how long these workspaces were running? @bsatoriu I noticed https://github.com/MAAP-Project/maap-eclipseche-ops/blob/master/che7/maap-k8sconfig-patch.yaml#L21 I wonder if that's what's causing the shutdowns.

**Comment by gllewellyn19** [comment]
Below is the earliest I recall creating these workspaces, and I normally don't shut down my workspaces (I only do when there is an error in the workspace which has only happened in Pilot ops):
basic-nt7vi- 6/28
basic-sg58y- 6/28
basic-7lkcd- 7/6 (when I created this issue because this was the one stopping)
basic-r9ct1- apparently Aimee created this one and I don't really remember that happening
basic-q8otl- 7/8 (created after our meeting when you asked me to just leave a workspace running)

**Comment by gllewellyn19** [comment]
Update: This happened today (7/23) and on 7/20, so I believe that this is still an ongoing problem (happened to basic-7lkcd both times, but also I only have 2 workspaces running and that's one of them). 

Note that the workspaces appeared to stop and when I restarted them my conda environment was lost.

**Comment by gchang** [comment]
This may be caused by disk space issues that @bsatoriu has already solved.

**Comment by gchang** [comment]
Haven't heard any issues with workspaces closing and losing data, so closing this tix.
