### ISSUE TITLE
SSL Certificate in GCC Ops Portal

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#377]
ops.maap-project.org has a valid SSL certificate, but www.ops.maap-project.org does not. www.ops.maap-project.org should be redirecting to ops.maap-project.org, but because the cert is invalid, it stops. www.uat.maap-project.org property redirects to uat.maap-project.org, so ops should copy that behavior. (pilot ops only has www.maap-project.org, but that's because of historical reasons).

**Comment by bsatoriu** [comment]
The certs and redirects for GCC Ops and UAT portals are now valid.

**Comment by gchang** [comment]
Verified!
