### ISSUE TITLE
Update references to maap.xyz

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#380]
While reviewing our [portal site](https://ops.maap-project.org/), I noticed the logo on the [login page)(https://auth.ops.maap-project.org/cas/login?service=https%3A%2F%2Fops.maap-project.org%2Fwp-login.php%3Fexternal%3Dcas%26redirect_to%3Dhttps%253A%252F%252Fops.maap-project.org%252F) references the homepage of a different domain, [https://www.maap.xyz](https://www.maap.xyz).

After sharing this finding with @gchang , he pointed out that we simply need to update any references to the `.xyz` version of MAAP so that the environment in question, points back to its respective homepage.

**Comment by anilnatha** [comment]
So my review of this issue has lead me to the realization that I don't have the access to update the page where the invalid links reside.  The login links for our respective environments send users to another CNAME. For example:

https://auth.uat.maap-project.org/
https://auth.dit.maap-project.org/
https://auth.ops.maap-project.org
https://auth.maap-project.org/

I can fix the links if I can gain access to these environments.

**Comment by bsatoriu** [comment]
@anilnatha here is where we store the html code for this UI: https://github.com/MAAP-Project/maap-auth-cas/tree/master/src/main/resources/templates/fragments

I think this is one problematic link: https://github.com/MAAP-Project/maap-auth-cas/tree/master/src/main/resources/templates/fragments

My recommendation would be to make this hardcoded string dynamic with a js function that transforms the host url (e.g. "https://auth.dit.maap-project.org/") by simply removing the "auth" portion of the url.

**Comment by bsatoriu** [comment]
@anilnatha once you have updated this code, just let me know and I can deploy the change.

**Comment by anilnatha** [comment]
@bsatoriu I have submitted a [pull-request](https://github.com/MAAP-Project/maap-auth-cas/pull/1) that I hope will resolve this issue.

**Comment by bsatoriu** [comment]
@anilnatha just deployed this to DIT. I had to move your js script to the bottom of the <header> element, since CAS auto-removes any <head> section code at compile time.

**Comment by anilnatha** [comment]
DIT looks good. I suppose the next steps are to deploy to UAT, GCC OPS and/or Pilot Ops to allow @oddes for QA?

**Comment by bsatoriu** [comment]
Yes, I have deployed to all environments and ran a quick smoke test. This is ready for QA.

**Comment by anilnatha** [comment]
I tested all the environments and things are looking good. I'll move this to the review queue so @oddes can get started on his end.

**Comment by oddes** [comment]
Looks good. Closing the issue.
