### ISSUE TITLE
Migrate Pilot OPS data to GCC ops

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#382]
Tracking ticket for data, s3 paths, and files that need to be migrated from pilot ops to gcc ops. Please add as comments the list of usernames (full email not necessary as zenhub is publicly visible), paths, and mappings.

**Comment by pahbs** [comment]
Copy the dps output (lots of CSV files) whose current pilot ops paths are stored in this file (/projects/jabba/data/extract_atl08_csv_list.csv) over to the new ade into some shared space

**Comment by wildintellect** [comment]
Also please copy everything in `maap-users/alexdevseed/`(Pilot) to `shared-buckets/alexdevseed/` (GCC)
