### ISSUE TITLE
Prototype DPS UI for CMR Metadata Collection

### ISSUE THREAD

**Issue by NamrataM** [MAAP-Project/ZenHub#386]
Update the DPS Jobs UI design for 2 actions to include the ability to deliver products to CMR.

**Comment by NamrataM** [comment]
Working with @abarciauskas-bgse on this. Meeting notes captured [here](https://paper.dropbox.com/doc/Meeting-notes-DPS-CMR-Interaction--BOeOnC9nPA7w1xs2hrIldNsdAQ-use9kgnKvY8QVgvCVM9AS). [Figma prototypes](https://www.figma.com/file/CGPxmwoNApnFrNwnMh2OzB/CMR-Delivery?node-id=0%3A1) are in progress.

**Comment by NamrataM** [comment]
Met with @anilnatha and @marjo-luc to sync up on this. Now handing this over to @anilnatha to merge with the UI styles for the project and update prototypes as design evolves.

**Comment by anilnatha** [comment]
The Questionnaire UI task #468 overlaps this task and is done. In addition, updates have been made to the Jobs UI to capture CMR information. After speaking with Namrata and Marjorie about this ticket, we agreed the work is completed. If additional changes for the related UIs are needed, new tickets will be created and assigned.
