### ISSUE TITLE
cd out of deleted folder ends in trash

### ISSUE THREAD

**Issue by gllewellyn19** [MAAP-Project/ZenHub#394]
When I delete a folder that I am still in and cd out of it, I end up in the trash as shown below:
![image.png](https://images.zenhubusercontent.com/60b0015d86f9229fe5c8c52f/8fb42064-d7a6-41f1-83b4-c09070c4e217)

I replicated this in Windows and got a different result:
![image.png](https://images.zenhubusercontent.com/60b0015d86f9229fe5c8c52f/e1c94fd2-8756-494c-8585-75cca5656383)

**Comment by gchang** [comment]
This is expected behavior on recent unix systems and MacOS. When you delete something via a GUI, it actually moves it to a "deleted" folder just in case you want to retrieve it. It's similar to the Recycle Bin in Windows.
