### ISSUE TITLE
Destructive buttons are colored like regular buttons

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#408]
Destructive buttons should use appropriate colors that make them stand apart from other buttons. Traditionally, red is used for destructive buttons.

Examples:

<img width="1280" alt="Screen Shot 2022-12-06 at 16 29 47" src="https://user-images.githubusercontent.com/931107/206264925-eefb1ce8-fa11-4c7f-9739-73283a92f2e7.png">

<img width="1280" alt="Screen Shot 2022-12-06 at 16 29 55" src="https://user-images.githubusercontent.com/931107/206264935-36aca12e-d461-4e53-9387-325ef20fa0d4.png">

In this case this applies to deleting a workspace or stopping a workspace.

**Comment by anilnatha** [comment]
@marjo-luc Brian mentioned to me that you had worked on the initial CHE workspace UI. This ticket, and two others involve some minor changes to the UI that I was hoping you could assist with.  I'll mention you on the other workspace UI issues.

**Comment by anilnatha** [comment]
I've modified the delete buttons in the workspaces area so they use the `danger` button instead of the `primary` button.

<img width="1280" alt="Screen Shot 2022-12-06 at 16 29 58" src="https://user-images.githubusercontent.com/931107/206265302-d577ffe5-b21a-46c3-ad3b-1aa6f40545ff.png">

<img width="1280" alt="Screen Shot 2022-12-06 at 16 30 09" src="https://user-images.githubusercontent.com/931107/206265306-6b89bcf4-561c-4d49-aa80-fd44fc024318.png">

Still looking at how to modify the "stop" workspace button.

**Comment by anilnatha** [comment]
Was able to modify the hover colors for the start and stop buttons to be green and red respectively instead of the blue that was previously used.

<img width="1261" alt="Screen Shot 2022-12-07 at 11 09 40 AM" src="https://user-images.githubusercontent.com/931107/206274942-8ab9c75a-a309-4377-a353-4312cfeb4019.png">

<img width="1261" alt="Screen Shot 2022-12-07 at 11 09 36 AM" src="https://user-images.githubusercontent.com/931107/206274939-1f505fc2-256b-4c5d-be8e-79f87485302a.png">

**Comment by anilnatha** [comment]
This was pushed to UAT and OPS so is ready for testing.

**Comment by oddes** [comment]
works as expected.
