### ISSUE TITLE
Running icon is missing tooltip

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#410]
The running workspace icon shown next to workspace name doesn't show a tooltip when the user hovers it unlike the name which does.

**Comment by anilnatha** [comment]
@marjo-luc

In reference to #408, this is another issue I could use your assistance with.

**Comment by anilnatha** [comment]
I've added tooltips to the workspace status indicators. Examples shown below:

<img width="344" alt="Screen Shot 2022-12-07 at 11 36 55 AM" src="https://user-images.githubusercontent.com/931107/206280126-a4906ea8-263f-4f59-ad89-f81f305b5fdc.png">

<img width="329" alt="Screen Shot 2022-12-07 at 11 36 58 AM" src="https://user-images.githubusercontent.com/931107/206280128-255cda1c-d54c-477e-80fb-f906f257afac.png">

**Comment by anilnatha** [comment]
Looks like this has already been pushed to UAT and OPS so is ready for testing.

**Comment by oddes** [comment]
Looks good.
