### ISSUE TITLE
Add user friendly option in Che 7 to set workspace RAM

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#415]
In Che 6, there is a RAM field in the UI when creating a new workspace, but no such field is present in Che 7. Investigate re-adding this field in the Che 7 ADE.

![Screen Shot 2021-07-23 at 3.08.26 PM.png](https://images.zenhubusercontent.com/5eea55df96327c1c7b658a63/14ec2771-5d88-46ff-be89-33f5d6c0044c)

**Comment by gchang** [comment]
I'm undecided on this one. RAM is one of the most expensive resources in the cloud, if we let users set this up, they may end up going to the max every time. I think before implementing this, we should have a way of quickly finding out how much ram any given user has allocated in their workspaces.

**Comment by gchang** [comment]
Will probably not address, workaround is to update the devfile.
