### ISSUE TITLE
Missing skip-to-content target

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#417]
The [profile page](https://ops.maap-project.org/profile/) contains a link to skip to the main content that targets an ID of `genesis-content` that is non-existent.

For reference, the [homepage](https://ops.maap-project.org/) showcases where the missing target ID should probably be added.

**Comment by gchang** [comment]
Need to run accessibility scan to double check.

**Comment by anilnatha** [comment]
After running a scan and looking at the reports, changing the following markup resolved the issue.

```
<main id="main" class="site-main" role="main">
```

to 

```
<main class="content" id="genesis-content">
```
