### ISSUE TITLE
Knowledge Base Plugin Implementation Question

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#422]
The UAT environment is using a third party WP plugin called "Knowledge Base for Documents and FAQs" that hasn't been installed in GCC or Pilot Ops.

Should this plugin and associated content be installed and synchronized to those environments for the September release?

**Comment by gchang** [comment]
We were experimenting with different plugins to store documentation. I think we've settled on using readthedocs, so probably don't need this plugin anymore.

**Comment by anilnatha** [comment]
Thanks for the info @gchang . One thing I liked about the plugin was its scrollspy integration.

Unless there are objections, I'll create a ticket to track the removal of this plugin from UAT and ensure content that is bundled with it that is available in GCC/Pilot Ops is preserved.
