### ISSUE TITLE
Issue accessing s3 links in gcc ops

### ISSUE THREAD

**Issue by gllewellyn19** [MAAP-Project/ZenHub#424]
![image.png](https://images.zenhubusercontent.com/60b0015d86f9229fe5c8c52f/9fd4752a-bc21-4a5c-8b10-d1f06a4ed096)
Here I am getting an error that one geotiff in the folder cannot be found when you can see in the left side of the screenshot that file is in my folder like the rest of the geotiffs. 

Now when I change the file name to N46W103 instead of N46W102 (actual file remains the same),
![image.png](https://images.zenhubusercontent.com/60b0015d86f9229fe5c8c52f/df871c22-6cb8-42fc-affb-f9f87a1351ce)
The function works perfectly fine

Note that this may also be a problem with the TiTiler I am not sure how to tell. When I directly paste the N46W102 url into the TiTiler it works

Maybe this is even a problem with my code, I am just not sure how to debug it

I have encountered this problem before and it just magically stopped the next day

**Comment by gllewellyn19** [comment]
Note that the error just magically stopped again, but now just started that N46W103 doesn't work as a file name, but when I change the file name back to N46W102 as it was originally it works.

**Comment by gchang** [comment]
Not reproducible. I think this may just be a "feature" of S3's eventual consistency.
