### ISSUE TITLE
Add API to obtain temporary AWS credentials to access requester pays buckets

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#428]
RasterIO depends on GDAL and GDAL is able to access requester pays buckets directly but requires access keys and secret. As we use IAM roles, this is not available. However, we are able to use the sts assume-role functionality to assume an IAM role with bucket access to generate time-limited AWS access keys for GDAL/RasterIO.

This is a better solution to #321

**Comment by bsatoriu** [comment]
@wildintellect @gchang the new requester pays credential method is available for testing in Ops using the Basic Stable workspace stack. Here is draft documentation on the new library method: https://github.com/MAAP-Project/maap-documentation/blob/bsatorius/request-pays-doc/docs/source/access/accessing_data.ipynb (second section).

**Comment by bsatoriu** [comment]
@wildintellect forgot to mention, here is an updated version of your notebook example, working with the new method:

```python
import rasterio as rio
from rasterio.session import AWSSession
from rasterio.plot import show
import boto3

# ---- Brian's changes - START ----
from maap.maap import MAAP

maap = MAAP(maap_host='api.ops.maap-project.org')
credentials = maap.aws.requester_pays_credentials()

boto3_session = boto3.Session(
    aws_access_key_id=credentials['aws_access_key_id'],
    aws_secret_access_key=credentials['aws_secret_access_key'],
    aws_session_token=credentials['aws_session_token']
)
# ---- Brian's changes - END  ----

aws_session = AWSSession(boto3_session, requester_pays=True)
file_s3 = 's3://usgs-landsat/collection02/level-2/standard/oli-tirs/2015/044/025/LC08_L2SP_044025_20150812_20200908_02_T1/LC08_L2SP_044025_20150812_20200908_02_T1_SR_B2.TIF'
with rio.Env(aws_session):
    with rio.open(file_s3, 'r') as src:
        # list of overviews
        oviews = src.overviews(1)
        # get second item from list to retrieve a thumbnail
        oview = oviews[1]
        # read first band of file and set shape of new output array
        thumbnail = src.read(1, out_shape=(1, int(src.height // oview), int(src.width // oview)))
# now display the thumbnail
show(thumbnail)
```

**Comment by oddes** [comment]
@bsatoriu @gchang 
Verified in the OPS environment and works as expected, Please see the attached screenshot.![Screen Shot 2021-09-07 at 10.58.21 AM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/a6692ec8-1e99-46c8-9bfe-bc70309b6a7a)
