### ISSUE TITLE
Get Capabilities in ADE references api.maap.xyz

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#432]
The "Get Capabilities" feature in ADE accessed via "DPS/MAS Operation" is referencing `api.maap.xyz`, see screenshot below.

Since `api.maap.xyz` will be decommissioned in the future (#381) and we manage multiple environments, could we make it so each environment lists its respective API endpoints?

<img width="1280" alt="Screen Shot 2021-08-04 at 14 06 06" src="https://user-images.githubusercontent.com/931107/128255605-6ae6b207-8cf8-49dd-9def-985dc1c50f05.png">

The above screenshots were taken from Pilot OPS. I'm currently unable to access the ADE environment on UAT or GCC Ops to verify if it is the same there.

**Comment by gchang** [comment]
This value is hardcoded and should be updated to reflect the current environment.

**Comment by bsatoriu** [comment]
I updated this endpoint to make the base URLs dynamic: https://github.com/MAAP-Project/maap-api-nasa/commit/b7371be50805c675f95981c575c421c776a87e3c

This change is deployed to DIT, UAT, and Ops.

**Comment by oddes** [comment]
@bsatoriu @gchang 
Looks good to me. See attached.[Uploading... Screen Shot 2021-08-20 at 8.27.21 AM.png]
