### ISSUE TITLE
External DAAC granule 401 error

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#433]
Samuel Ayers reported receiving a 401 error when calling granule.getData() in the ADE, despite being logged in with a valid PGT.

To reproduce the original issue:

1. Delete any existing public SSH key from your MAAP profile via the portal account page.
2. Start a new MAAP session in the Ops ADE.
3. Run the following notebook: https://gist.github.com/bsatoriu/6210a0594da7433514ba9d7deef6c72e

Result: the second code cell will produce a 401 error.

**Comment by bsatoriu** [comment]
This error is caused by a bug in the `show_ssh_info` plugin, wherein the PGT environment variable will fail to be assigned if user has no public SSH key.

**Comment by bsatoriu** [comment]
This has been fixed by removing the PTG's dependency on the presence of a public SSK key. Commit details: https://github.com/MAAP-Project/maap-jupyter-ide/commit/2297e6ca02eaf5f7c0e30ed105d70f30a23d61eb

**Comment by oddes** [comment]
@bsatoriu 
I followed the steps but getData() function throwing following error: Could u please check this?
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-0fc1b02b1d42> in <module>
      1 results = maap.searchGranule(collection_concept_id='C1200231010-NASA_MAAP')
----> 2 download = results[0].getData()

AttributeError: 'Granule' object has no attribute 'getData'

**Comment by bsatoriu** [comment]
@oddes currently, the `getData()` method is only available using this image: 
  `mas.maap-project.org:5000/root/jupyter-image/vanilla:edl-federated-login`

Once you open a new workspace on ade.ops.maap-project.org, you will need to update the workspace settings. On line 34 of the "Devfile" tab, replace the container name  with the new test image referenced above. Once the workspace is restarted, this error message will no longer appear.

**Comment by oddes** [comment]
@ Bryan
As we have discussed updating the ticket and assigning back to you for the fix:

Issue: User without accepting End user license agreement from "https://search.asf.alaska.edu/#/?dataset=UAVSAR" in the URS profile, unable to get the getData() function. Need a fix.

**Comment by bsatoriu** [comment]
Here are steps to reproduce the error @oddes encountered:

1. Ensure your EDL profile has no ASF application (delete Alaska Satellite Facility data access from https://urs.earthdata.nasa.gov/users/bsatoriu/authorized_apps if it exists)
2. Re-run the [EDL-enabled notebook](https://gist.github.com/bsatoriu/6210a0594da7433514ba9d7deef6c72e)

Result: the `getData()` call will return a 401 error. 

This is what I consider the correct behavior, but in Sri's case, the underlying reason for the error--he had not approved the ASF EDL app--was unclear from the maap-py error message. 

@oddes I propose we close this ticket, since the target use case is now working as expected, and create a separate ticket to change the maap-py error message in the case of a 401 response. This error message should inform the user about the corresponding DAAC app requirement, and include a link to the DAAC app if feasible.

**Comment by oddes** [comment]
this will be handles in getData() is throwing 401 error#439
