### ISSUE TITLE
Automate MAAP API deployment process 

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#434]
In the development environment, the MAAP API uses a Gitlab CI project to auto-deploy after any git commits to the [maap-api-nasa repo](https://github.com/MAAP-Project/maap-api-nasa). We need to apply a similar process to the other MAAP environments: DIT, UAT, Ops, and Pilot Ops.

**Comment by bsatoriu** [comment]
I set up Gitlab CI projects against the following maap-api-nasa branches:

pilot-ops https://mas.maap-project.org/root/maap-api-ci
release https://repo.ops.maap-project.org/root/maap-api-nasa-ci
develop https://repo.nasa.maap.xyz/root/maap-api-nasa (this is being migrated to DIT)

The develop branch is deployed automatically on commit (this will also apply to DIT) in contrast to pilot-ops and release, which are deployed by running their respective Gitlab pipelines. We can add Github webhooks for these two environments as well, if needed. I'm still in the process of adding a UAT CI project, which will use the release branch as its build source.

Most importantly, all three of these branches are now in sync with their respective target environments, and any deployments going forward will be made transparently through the [maap-api-nasa](https://github.com/MAAP-Project/maap-api-nasa) repo.

**Comment by oddes** [comment]
@bsatoriu All of these pages are redirecting to 404 error. Could u please check with you login. I have tried with my URS login.

**Comment by bsatoriu** [comment]
@oddes I added you as a user to pilot-ops, ops, and uat. Once you sign on to dit and your gitlab account is generated, I will add you on that project as well.

**Comment by oddes** [comment]
@bsatoriu it works. Closing.
