### ISSUE TITLE
DNS Record Updates for *.uat.maap-project.org (Part 2)

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#437]
Please update the IP addresses for the following UAT DNS entries:

auth/api/www.uat.maap-project.org 54.70.136.24
ade.uat.maap-project.org 44.232.227.159
repo/mas.uat.maap-project.org 52.42.144.178

**Comment by michaelsfoley** [comment]
These should be in place:

Default Server:  ns1.msfc.nasa.gov
Address:  128.158.4.14

> auth.uat.maap-project.org
Server:  ns1.msfc.nasa.gov
Address:  128.158.4.14

Non-authoritative answer:
Name:    auth.uat.maap-project.org
Address:  54.70.136.24

> api.uat.maap-project.org
Server:  ns1.msfc.nasa.gov
Address:  128.158.4.14

Non-authoritative answer:
Name:    api.uat.maap-project.org
Address:  54.70.136.24

> www.uat.maap-project.org
Server:  ns1.msfc.nasa.gov
Address:  128.158.4.14

Non-authoritative answer:
Name:    uat.maap-project.org
Address:  54.70.136.24
Aliases:  www.uat.maap-project.org

> ade.uat.maap-project.org
Server:  ns1.msfc.nasa.gov
Address:  128.158.4.14

Non-authoritative answer:
Name:    ade.uat.maap-project.org
Address:  44.232.227.159

> repo.uat.maap-project.org
Server:  ns1.msfc.nasa.gov
Address:  128.158.4.14

Non-authoritative answer:
Name:    repo.uat.maap-project.org
Address:  52.42.144.178

> mas.uat.maap-project.org
Server:  ns1.msfc.nasa.gov
Address:  128.158.4.14

Non-authoritative answer:
Name:    mas.uat.maap-project.org
Address:  52.42.144.178

>
