### ISSUE TITLE
Side panel shows twice on ADE workspace

### ISSUE THREAD

**Issue by oddes** [MAAP-Project/ZenHub#442]
1. Created a newly registered user and activated.
2. Login with new user (test_user_test)
3. User lands on Che workspace
4. Open new workspace, you will notice side panel twice as shown in attached screens.

![Screen Shot 2021-09-02 at 3.24.41 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/f84f836c-83e9-45b5-ba01-8a7b8f160c0a)

**Comment by gchang** [comment]
I think might be related to #429

**Comment by oddes** [comment]
@gchang Agree, I will follow in the original ticket. we can safely close this ticket.
