### ISSUE TITLE
UAT machines cleanup

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#444]
Now that we have moved some machines around in UAT into the new subnets, can we do some cleanup and shutoff old machines (possibly creating a backup first)? The AWS account is running hotter the past two months.

Also, is the ADE in UAT configured as a multinode microk8s or is it still single node? I only see one machine with the ADE label.

**Comment by bsatoriu** [comment]
@gchang the UAT ADE was setup as a single node. Should we make it multinode to be consistent with Ops and DIT?

The following instances were shut down today:

**Dev** (replaced UAT environment in old subnet)
- auth - t3.xlarge
- repo - c5.xlarge
- gitlab runner - c5.xlarge 
- ade - c5.4xlarge

**Ops** (never-used UAT environment)
- auth - t3.xlarge
- repo - t3.xlarge
- gitlab runner  - t3.xlarge
- ade - r5.8xlarge (x3)

**Comment by bsatoriu** [comment]
The UAT repo machine was backed up right before final replacement on August 17. The auth and ade machines were backed up on August 14th and 18th, respectively.

**Comment by gchang** [comment]
Thx, we'll see if that makes a dent in the budget. And yes, we should make UAT the same as Ops and DIT. We can use smaller machines (r5.2xlarge I think), similar to DIT so that we don't use up too many resources.
