### ISSUE TITLE
FAQ section of "User Guides" header image is missing

### ISSUE THREAD

**Issue by oddes** [MAAP-Project/ZenHub#451]
Steps to Reproduce:

1. Login to Portal.
2. Navigate to "Help-->Guides...>FAQ
3. All subsection in FAQ are showing as shown in attached screenshot.![FAQ-Page.jpg](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/49ad37d0-e160-46c3-86bc-8a0f3933837e)

![page1.jpg](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/c3995615-5479-4afe-9efa-3c2b1dfa5623)

**Comment by marjo-luc** [comment]
@anilnatha Can we close this?

**Comment by anilnatha** [comment]
@marjo-luc Yes, I think this ticket is a duplicate. I resolved this issue in ticket #450.
