### ISSUE TITLE
Update GitLab and workspace root certificate

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#459]
Starting September 30 2021, MAAP users were unable to clone from their GitLab repositories from within ADE workspaces. Example:

```bash
> git clone https://repo.ops.maap-project.org/lduncanson/biomass_harmonization.git
fatal: unable to access ‘https://repo.ops.maap-project.org/lduncanson/biomass_harmonization.git/’: server certificate verification failed. CAfile: none CRLfile: none
``` 

This cert error is caused by an [expired CA certificate from Let's Encrypt](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/). We'll need to update the certs on the workspace and any affected GitLab host.

**Comment by bsatoriu** [comment]
I updated [the ADE base image](https://mas.maap-project.org/root/ade-base-images/-/commit/9feefb4fffb12e2d0d1b61d9e568ffe559b02143) to resolve the workspace cert error, as well as the Pilot Ops GitLab runner server to resolve our CI errors.

**Comment by oddes** [comment]
Works fine. cloned project with no error
