### ISSUE TITLE
Create DPS job unit test

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#463]
See parent epic for description. We may already have this, not sure. Also, if we're short on time, we can skip this for now, but we really should have a way of verifying the DPS plumbing.

**Comment by gchang** [comment]
Implemented at https://github.com/MAAP-Project/dps-unit-test

**Comment by oddes** [comment]
Success Criteria:
1. User can successfully Register algorithm 
2. Get list of algorithms response should show the registered algorithm.
3. Successfully execute registered algorithm should generate corresponding output

**Comment by gchang** [comment]
@oddes Perform this as an independent test on the new DPS on Ops
