### ISSUE TITLE
Period in username doesn't work in OPS ADE

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#472]
Could be related to an issue we've seen in the past that I thought we corrected.

**Comment by bsatoriu** [comment]
@gchang I pointed the workspace images back the develop tag, and cleared Masato's Keycloak account. The next time he logs in, the workspace will load properly. Let me know if you'd like me to reply back to him and Laura.

**Comment by oddes** [comment]
works fine
