### ISSUE TITLE
Unable to open ADE workspace in UAT

### ISSUE THREAD

**Issue by oddes** [MAAP-Project/ZenHub#476]
Steps to Reproduce:
1. Login to the UAT [ https://uat.maap-project.org/] as ESA user
2. Navigate to ADE Workspace, you will notice the issue as shown in screen shot![Screen Shot 2021-10-20 at 9.29.39 AM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/63e45fbc-83aa-470d-acb3-fa3ae43afc03)

**Comment by bsatoriu** [comment]
This has been addressed-- @oddes  can you please confirm?

**Comment by oddes** [comment]
work as expected.
