### ISSUE TITLE
Build new CAS image with new MAAP logo

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#477]
The current logo update is just copied into the webapps directory so it'll disappear of CAS is redeployed.

**Comment by anilnatha** [comment]
I've updated the header imagery and favicons while working on the login UI updates.  This will be published when we finish testing the UI updates.

<img width="1280" alt="Screen Shot 2021-11-09 at 12 29 38" src="https://user-images.githubusercontent.com/931107/141000009-f8c0f576-4748-4add-b57e-9742e5947ce9.png">
