### ISSUE TITLE
Unable to get into ADE workspace

### ISSUE THREAD

**Issue by oddes** [MAAP-Project/ZenHub#478]
Unable to get into ADE workspace

Steps:
1. Login into the https://uat.maap-project.org/ as a ESA user
2. When I try to choose workspace, its non functional.

Please see screenshot ![Screen Shot 2021-11-04 at 3.58.46 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/e09fe722-051d-44aa-ac26-477951586fe8)

When I login with NASA User and try the same I am getting following error:
" Unexpected error when authenticating with identity provider"

**Comment by gchang** [comment]
Two issues:
1) As ESA user, cannot start workspace (could be because pilot ops gitlab/registry is down)
2) Cannot login with NASA URS

**Comment by bsatoriu** [comment]
I updated the CAS overlay to resolve a bug related to Syncope access token generation, which has fixed the NASA URS  and ESA workspace startup errors.

**Comment by oddes** [comment]
works for both ESA and NASA users
