### ISSUE TITLE
Update reference to api.maap.xyz

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#488]
https://github.com/MAAP-Project/maap-api-nasa

**Comment by anilnatha** [comment]
Should help narrow down what needs to be addressed:

https://github.com/search?q=maap.xyz

**Comment by bsatoriu** [comment]
I updated the references in the following commits:

- https://github.com/MAAP-Project/maap-auth-example/commit/4d19f682ec1d8c9ee45913c4b832fd5d43604a98
- https://github.com/MAAP-Project/maap-jupyter-ide/commit/2bb5c2173cbf5a03230ab439d72ee1992bfa74aa
- https://github.com/MAAP-Project/maap-jupyter-ide/commit/4f2b691a3f1d3af445af5b53afe3f3d159a46e04
- https://github.com/MAAP-Project/maap-api-nasa/commit/5104a91622bd41c3e6047d266b9297b5ac09d283
- https://github.com/MAAP-Project/maap-eclipseche-ops/commit/4b7e1662731ea58737921cf3c372eb5f5380798a
- https://github.com/MAAP-Project/maap-ade-edscproxy/commit/ed8ba534da41b333a6cad4f30d47687a0f9072e8
- https://github.com/MAAP-Project/maap-ade-tutorials/commit/2ad4ea0f69a47e9d5597bb5fdd84e0edd30b8b61
- https://github.com/MAAP-Project/maap-auth-syncope/commit/2799cc1308047afc267673089bef86a98f1542a8
- https://github.com/MAAP-Project/maap-auth-keycloak/commit/c2633be765a9dafd01592263a00d876221f63c96
