### ISSUE TITLE
Clean up existing Portal stylesheet

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#49]
Revisit the NASA MAAP CSS stylesheet and ensure that all elements, especially colors, are used. If not, consider removing them to simplify the stylesheet.

**Comment by marjo-luc** [comment]
Done. I left most of the bootstrap boilerplate, but removed the items we are clearly not using (i.e. social media button info, styling for components that no longer exist, etc.). I also took this opportunity to sync the css on maap-project with that on maap.xyz as they had deviated from each other.
