### ISSUE TITLE
Inconsistent portal session lengths

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#493]
Now that the profile page is working in DIT, during testing I observed differing session timeouts between the WordPress (WP) Session, PHP Session, and URS Session. This was observed on the profile page where profile information wasn't being displayed because my PHP session had timed out; however, my WP session was still active.

At minimum, I believe the PHP Session (needed by CAS) and the WP session should use the same timeout value.  PHP's default session timeout is 24 minutes, WP's default session timeout is 48 hours.

@gchang Do you know of any cyber security policies that stipulate what the maximum session timeouts should be for NASA? If there aren't any, what value shall we use for the session timeout?

**Comment by gchang** [comment]
@gchang to take a look at URS defaults

**Comment by gchang** [comment]
We're targeting a consistent 24 hour session length for the portal.

**Comment by anilnatha** [comment]
@bsatoriu I've  modifed the `wp_maap_pgt` cookie to expire after 24 hours.

I've also added a new cookie to store a user's username to be used for #537 that also expires at the correct timeout.

I'm now testing that this implementation is working.

**Comment by anilnatha** [comment]
@oddes This issue is ready to be tested in UAT.  A user's session (Admin and regular users), will expire 24 hours after login. A user's session is _not_ extended by performing activity on the site.

After their session expires the user is logged out. If they attempt to view their profile by navigating to the profile page, [https://uat.maap-project.org/profile/](https://uat.maap-project.org/profile/) directly, they will be instructed to login.

Please let me know if you have any questions.

**Comment by anilnatha** [comment]
@oddes Which environment and user account was used for this testing?

**Comment by oddes** [comment]
@anilnatha 
I have tested in UAT environment. I have used sodde

**Comment by anilnatha** [comment]
@oddes Thanks for the info. I'll take a look.

**Comment by anilnatha** [comment]
At @oddes, can you retest.  If memory serves me right, this issue was expected for users that were already signed in after we rolled out the new code.  The cookie that contains the information needed to fetch a user's profile information is only set upon login.  Subsequent login attempts will set the cookie and this page should load normally.  Since this issue was temporary and fixed upon subsequent login attempts, no further resolution was needed.

On a related note, there is one exception that may cause this issue but that only pertains to ESA users, which doesn't apply in this case, and one that we intend to resolve with a future update to the portal and MAAP API.

**Comment by oddes** [comment]
Looks good.
