### ISSUE TITLE
Update Authorizer plugin management

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#494]
Our portal is dependent on a specific version of the Authorizer plugin that we have forked and modified to work with our CAS instance. Because of this, we should not use WordPress's plugin update features; otherwise it will overwrite our modified version of the plugin.

We need to:

- [x] Determine a simple solution that allows us to use the plugin as-is so that our changes don't get overwritten when we need to update the plugin.
- [x] ~Create a child theme of MonochromePro so that changes to `functions.php` are not overwritten when the theme is updated~

**Comment by anilnatha** [comment]
Commented out second task since we now have a custom maap plugin for WordPress where we can add WP customizations.

**Comment by anilnatha** [comment]
Code has been submitted to the original author of the plugin in the form of a pull request. They have already replied stating they will review it this week.

https://github.com/uhm-coe/authorizer/pull/117

**Comment by anilnatha** [comment]
The changes I proposed for the Authorizer plugin were accepted and merged into the official Authorizer repo.

I've upgraded the plugin in DIT and UAT to version 3.4.1. and set the `cas_method` to `PROXY` under the 'External' tab of the Authorizer settings. Login was still working after upgrading to the new version of the plugin.

@oddes When you have a moment, could you please test and verify that you are able to login to the portal using your test accounts?

**Comment by oddes** [comment]
Looks good. Able to login to both UAT and OPS.

**Comment by anilnatha** [comment]
@oddes only DIT and UAT have been updated.  Was awaiting your tests before I published to OPS.

**Comment by oddes** [comment]
@anilnatha Please push this to OPS for testing.

**Comment by anilnatha** [comment]
The Authorizer plugin has been updated in OPS and is ready for your testing @oddes 

- Crucial test would be to ensure you're able to login using EarthData (URS) successfully.

**Comment by oddes** [comment]
works good.
