### ISSUE TITLE
Direct Access to EarthData Cloud via AWS tokens

### ISSUE THREAD

**Issue by wildintellect** [MAAP-Project/ZenHub#495]
**Is your feature request related to a problem? Please describe.**
Unable to directly use s3 paths to EarthData Cloud resources with methods beyond the maap-py [getData](https://github.com/MAAP-Project/maap-py/blob/87efa1ea31098bc9cc43bbf04d3ddf2388caf7d2/maap/Result.py#L15) function. This is a problem if we want to try any cloud-optimized data access methods or optimize remote subsetting.

**Describe the solution you'd like**
The ability to directly use S3 EarthData Cloud resources with additional functions (i.e. Rasterio, PDAL, etc..) through the use of temporary EDL AWS tokens. Each of the DAACs has a an s3credential url that an authenticated EDL user can hit to get temporary AWS credentials. We should implement that option `getS3` in maap py (very similar the requester pays workflow), and return the credentials so they can be passed to methods requiring them.

```
s3_cred_endpoint = 'https://data.lpdaac.earthdatacloud.nasa.gov/s3credentials'
temp_creds_req = requests.get(s3_cred_endpoint).json()

session = boto3.Session(aws_access_key_id=temp_creds_req['accessKeyId'], 
                        aws_secret_access_key=temp_creds_req['secretAccessKey'],
                        aws_session_token=temp_creds_req['sessionToken'],
                        region_name='us-west-2')
```
https://nasa-openscapes.github.io/slides/Earthdata_Cloud__Open-Science-Tutorial#/19

**Describe alternatives you've considered**
The only other option would be to directly hit the s3 credential request endpoints after directly authorizing with EDL user/password.

**Additional context**
This builds on previous work to utilize federated EDL tokens to get access to EarthData Cloud data. https://docs.maap-project.org/en/develop/access/accessing_external_data.html

**Comment by wildintellect** [comment]
@nmt28 is working on using HLS (to improve upon L8 data) for the boreal work now which will require LPDAAC AWS temp tokens. https://lpdaac.usgs.gov/resources/e-learning/getting-started-cloud-native-hls-data-python/#extracthls see part 4.2 <- we want to avoid having to put URS credentials in the workspace.

**Comment by wildintellect** [comment]
@bsatoriu after @abarciauskas-bgse did some more looking around, we think what really is needed is the Federated token to be easily available to users such that when requests are made in code that session cookies are available to things like libcurl (Basically the session token for EDL is passed as if auth happened with a .netrc file).
https://nasa-openscapes.github.io/2021-Cloud-Workshop-AGU/how-tos/Earthdata_Cloud__Single_File__HTTPS_Access_COG_Example.html

Looking at maap-py I'm trying to understand how the MAAP_PGT ENV var works https://github.com/MAAP-Project/maap-py/blob/14dc7c835de7f58185f703cccedc3cd15a098d50/maap/maap.py#L81-L88 , and if we just need to make sure that var is passed by various clients (i.e. gdal) when needed.

**Comment by bsatoriu** [comment]
@wildintellect the federated token requests in the CMR granule use cases we tested had to include not only the user's federated token, but also the MAAP EDL application token. For this reason, all EDL requests from within an ADE workspace are routed [through the MAAP API.](https://github.com/MAAP-Project/maap-api-nasa/blob/release/api/endpoints/cmr.py#L140) When running in the DPS, we have a separate process that can access data directly from a DAAC to bypass the API.

If these EarthData Cloud data don't require an EDL application token, then a .netrc approach should be feasible. I can run a quick test tomorrow to see if this will work.

**Comment by wildintellect** [comment]
the problem with the .netrc approach is that the username/password would then be in the workspace, and how would that be propagated to a DPS job? This seems insecure in a shared workspace model.

**Comment by bsatoriu** [comment]
Agreed--I was suggesting trying an EDL user token rather than storing the user's credentials, although I see now this won't work, so "requester pays"-style workflow may be necessary. I wonder though, would be more sensible for the MAAP system to auto-generate an AWS config file with these temp tokens for the user on workspace startup (or via a new button in the workspace)? Given the tokens are temporary, it may be feasible from a security standpoint.

**Comment by wildintellect** [comment]
Whatever the solution it needs to also work in DPS jobs, so an api call when needed, to setup the tokens would probably work.
Normal workflow would be, query for data, request credentials, then read data when needed.

**Comment by wildintellect** [comment]
@bsatoriu I've been able to verify that it works.

https://gist.github.com/wildintellect/057517ebed1cc590157f87ab58ad7a8f

**Comment by oddes** [comment]
works good. Please see attached.
![Screen Shot 2022-02-18 at 6.10.25 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/b9f724e2-da69-4157-94fe-de748b787da3)

**Comment by bsatoriu** [comment]
Thanks @oddes. This is deployed to Ops. I notified Alex of the update.
