### ISSUE TITLE
Remove portal elements from "Login in with" CAS page

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#50]
The login in page has the portal toolbar and footer. Those aren't necessary in the log in page.

**Comment by marjo-luc** [comment]
CAS login has been updated. @gchang do you have any comments before I close this ticket?

**Comment by gchang** [comment]
Please keep the sheep logo so users knows it's a MAAP login if they forget (as opposed to just some random page asking for a login).
