### ISSUE TITLE
[Data]: ATL08 & ATL03 v5

### ISSUE THREAD

**Issue by pahbs** [MAAP-Project/ZenHub#501]
**Dataset Name**
ATL08 & ATL03 version 5

**Dataset Description**
This is an upgrade of the existing data, L3A Land and Vegetation Height and L2A Global Geolocated Photon Data products

**Requestor name/affiliation**
Paul Montesano/ NASA-GSFC, MAAP UWG

**Platform/Instrument/Method**
ICESAT-2/ATLAS

**URL or DOI to dataset description**
https://nsidc.org/data/atl08
https://nsidc.org/data/atl03

**URL to download or access data**
LPDAAC EarthData Cloud

**Data License**
Attribution:
Neuenschwander, A. L., K. L. Pitts, B. P. Jelley, J. Robbins, B. Klotz, S. C. Popescu, R. F. Nelson, D. Harding, D. Pederson, and R. Sheridan. 2021. ATLAS/ICESat-2 L3A Land and Vegetation Height, Version 5. [Indicate subset used]. Boulder, Colorado USA. NASA National Snow and Ice Data Center Distributed Active Archive Center. doi: https://doi.org/10.5067/ATLAS/ATL08.005. [Date Accessed].

Neumann, T. A., A. Brenner, D. Hancock, J. Robbins, J. Saba, K. Harbeck, A. Gibbons, J. Lee, S. B. Luthcke, T. Rebold, et al. 2021. ATLAS/ICESat-2 L2A Global Geolocated Photon Data, Version 5. [Indicate subset used]. Boulder, Colorado USA. NASA National Snow and Ice Data Center Distributed Active Archive Center. doi: https://doi.org/10.5067/ATLAS/ATL03.005. [Date Accessed].

**Intended science use case**
Above ground biomass estimated, core MAAP dataset.

## Optional

**Approximate size of data**
 > 250TB

**Additional information**
NA

**Comment by TonHai1111** [comment]
Data has been published: https://github.com/MAAP-Project/ZenHub/issues/504
