### ISSUE TITLE
[Data]: Upgrade to Version 5 of ATL03/08

### ISSUE THREAD

**Issue by wildintellect** [MAAP-Project/ZenHub#504]
**Dataset Name**
 ATL08 & ATL03 version 5

**Dataset Description**
This is an upgrade of the existing data,  L3A Land and Vegetation Height and L2A Global Geolocated Photon Data products.

**Requestor name/affiliation**
Laura Duncanson @lauraduncanson , MAAP UWG, UMD
Paul Montesano @pahbs 

**Platform/Instrument/Method**
ICESAT-2/ATLAS

**URL or DOI to dataset description**
https://nsidc.org/data/atl08

**URL to download or access data**
LPDAAC EarthData Cloud

**Data License**
Attribution:
Neumann, T. A., A. Brenner, D. Hancock, J. Robbins, J. Saba, K. Harbeck, A. Gibbons, J. Lee, S. B. Luthcke, T. Rebold, et al. 2021. ATLAS/ICESat-2 L2A Global Geolocated Photon Data, Version 4. [Indicate subset used]. Boulder, Colorado USA. NASA National Snow and Ice Data Center Distributed Active Archive Center. doi: https://doi.org/10.5067/ATLAS/ATL03.004. [Date Accessed].

**Intended science use case**
Above ground biomass estimated, core MAAP dataset.

## Optional

**Approximate size of data**
250 TB

**Additional**
This data is required as it contains additional dates after 2021-07-15 and has new quality flags relevant to Biomass.

* Consider deprecating v3 and v4 after ingest, or at least moving v4 to colder storage level.
* Configure for ongoing ingest.

**Comment by spa0002** [comment]
Metadata created for ATL08 v005 data

**Comment by slesaad** [comment]
One granule has been successfully published (linked [here](https://cmr.maap-project.org/search/granules.json?shortName=ATL08&version=005)). Waiting for the metadata to be verified before going ahead and publishing the rest.

**Comment by slesaad** [comment]
**ATL08 v005:**

Kicked off the ingest.

Since the number of granules is huge (172,869), doing it in chucks of ~40k data each.

Feb 2nd: Temporal range: `2018-10-03T00:00:00.000Z, 2019-07-30T23:59:59.000Z` (total 41,992 granules)

As of 2:30 CST Feb 3rd, 10959 granules have been published. This can be monitored in [this link](https://cmr.maap-project.org/search/granules.umm_json?shortName=ATL08&version=005).

**Comment by slesaad** [comment]
I ran ingest for the ATL08 v005 granules, temporal[]": "2018-10-03T00:00:00.000Z, 2019-07-30T23:59:59.000Z which in nasa cmr has 41,992 granules. All the ingests ran successfully, no failed executions. The backgroundJobQueue has 0 messages available or in flight. But the number of granules published to the maap cmr is just 24,697 . The only weird thing I see is 14 messages available in the cleanExecutionsDeadLetterQueue, but i don’t know what it represents.

**Comment by slesaad** [comment]
On running ingest on single granules (from the granules that were published from the last ingest run), they seem to be working fine individually. Wondering if the silent failure was a one time thing and continuing ingest for the next batch.

**Comment by slesaad** [comment]
Upped the `desired_count` to 20 based on the instruction from [the document by Phil](https://github.com/MAAP-Project/maap-cumulus-deploy/blob/master/OPERATING.md#:~:text=The%20next%20limitation,starvation%20will%20occur.) 

Started new ingest for `"temporal[]": "2021-03-15T00:00:00.000Z, 2021-11-15T23:59:59.000Z"` on 8th Feb, 12:36PM.

**Comment by slesaad** [comment]
All granules have been ingested and published!
