### ISSUE TITLE
ADE Dockerfiles install maap-py library using different branches and different methods

### ISSUE THREAD

**Issue by philvarner** [MAAP-Project/ZenHub#505]
**Describe the bug**

Each of the two Dockerfiles that create the ADE Jupyter image install the maap-py, but do it from different branches and using different install methods. 

The Dockerfile https://mas.maap-project.org/root/ade-base-images/-/blob/vanilla-develop/docker/Dockerfile
installs the develop branch using setup.py

The Dockerfile https://mas.maap-project.org/root/jupyter-image/-/blob/master/docker/Dockerfile
installs the master branch using `pip install -e .`

These don't seem like intentional decisions to me, so I thought I'd bring it up.  I would have through they'd be installed in the same way and that both would use the same tag for installing rather than develop or master.

**Comment by gchang** [comment]
We're updating the build process for the new workspaces and they'll be consistent.
