### ISSUE TITLE
ADE & DPS Docker images have GBs of unnecessary files in Docker layers

### ISSUE THREAD

**Issue by philvarner** [MAAP-Project/ZenHub#506]
**Describe the bug**

The ADE Jupyter image is generated from these three Dockerfiles:

- https://github.com/ContinuumIO/docker-images/blob/master/miniconda3/debian/Dockerfile
- https://mas.maap-project.org/root/ade-base-images/-/blob/vanilla-develop/docker/Dockerfile
- https://mas.maap-project.org/root/jupyter-image/-/blob/master/docker/Dockerfile

These images use apt-get and conda commands in a way that leave a large number of unnecessary files in the layers, causing significant bloat to the images. In my (brief) trials with improving the layers, I was able to reduce just the ade-base-images size from 6GB to 3.4GB, but haven't tried slimming jupyter-image. The mas.ops.maap-project.org/root/jupyter-image/vanilla:develop image is about 10GB and includes more conda installs, so this image could probably be slimmed down to 5-6GB. That would significantly improve retrieval and unpacking time, which is currently on the order of minutes (I've been seeing 4 minutes in my GitHub Actions I'm using it in).

These are a summary of recommendations, with links to a few articles that describe them in more detail at the end of this issue.

### apt-get:

(1) use `--no-install-recommends` with apt-get so that extra packages that are simply recommended dependencies are not installed. This may result in needing to add an explicit install for a desired package that was installed as a dependency of an explicit one. For example, in the miniconda3 docker image, the mercurial package is installed which transitively installs the python3 package -- which is a pretty significant dependency for this image!

```
    RUN apt-get install -q -y --no-install-recommends PACKAGE_NAME
```

(2) Within the same RUN command that any `apt-get install` is performed, cleanup the apt cache:

```
    RUN apt-get install -q -y --no-install-recommends PACKAGE_NAME \
   && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
```

### Conda:

(3) use the `--freeze-installed` flag to prevent inadvertently upgrading a package, which causes both versions of the package to remain on the filesystem unnecessarily. This may result in older versions of libraries existing, so the entire set of conda libraries shoudl be checked against the old set after adding this flag.

```
conda install --yes --freeze-installed PACKAGE_NAME
```

(4) After each conda install, within the same Docker RUN command, the conda cache must be cleaned up like:

```
RUN conda install --yes --freeze-installed PACKAGE_NAME && \
  find /opt/conda/ -follow -type f -name '*.a' -delete && \
    find /opt/conda/ -follow -type f -name '*.js.map' -delete && \
    /opt/conda/bin/conda clean -afy
```

Resources:
- [Dive](https://github.com/wagoodman/dive) is a great tool for cleaning up Docker layers
- The base image definition above (ContinuumIO/miniconda) has a great example of cleanup for conda and apt-get (
https://github.com/ContinuumIO/docker-images/blob/master/miniconda3/debian/Dockerfile).
- Conda tips: https://jcristharif.com/conda-docker-tips.html
- General python tips: https://www.aboutwayfair.com/case-study-how-we-decreased-the-size-of-our-python-docker-images-by-over-50

**Comment by gchang** [comment]
We're already incorporating the changes above into our new builds.
