### ISSUE TITLE
EDSC not working on DIT environment

### ISSUE THREAD

**Issue by marjo-luc** [MAAP-Project/ZenHub#508]
The EDSC jupyter extension does not seem to be working as expected on DIT. When users try to open it, they see the following:
![extension_404.png](https://images.zenhubusercontent.com/5eea86b79801f3519458f31d/120c5b85-0040-4f0c-9349-2a8743cb4e91)

Accessing the server directly through https://ade.dit.maap-project.org:30052/ shows:
![proxy_error.png](https://images.zenhubusercontent.com/5eea86b79801f3519458f31d/e16560ff-54ba-44aa-80ac-9e761cc73285)

**Comment by gchang** [comment]
#notabug!

@abarciauskas-bgse is going to deploy search.dit.maap-project.org later today so this proxy will work then. I did a quick test with having it proxy search.maap-project.org and it worked as expected.
