### ISSUE TITLE
Introduce more types of inputs during algorithm registration

### ISSUE THREAD

**Issue by NamrataM** [MAAP-Project/ZenHub#512]
Currently during algorithm registration, users specify the type of parameter as
`download: true/false`
Where, 
if true - it means the input is expected to be a URL or list of URLs which will be download on algorithm execution
if false - the input will become a positional argument to the script they wish to run

In order to make the types more intuitive and extend the features, we have a new way of defining the parameter types.

- positional - the input will become a positional argument to the script in the order they are listed in the algorithm registration params list

-  file - the input (expected to be URL or list of URLs) will be downloaded and available as files in the directory the script is run from

-  config - the input can be a JSON object or any value that the user wants to utilize in their algorithm but doesn't fit into the above 2 types. To access this parameter, the current solution is to use a helper script available in the work directory called `get_from_context.py` and pass in the parameter name as an input. This script reads a file `_context.json` and parses out the value of the parameter. It will return a dictionary if the value is a JSON otherwise a string.

In the algorithm registration, the parameter definition will change to:
{
"field": "param_name",
"type": “file / positional / config”,
"default" : "value" #this is optional
}

Note: This change is being brought in from the ImgSPEC API, which has been tested.

Action Items:
- [x] Update the API to read the updated algorithm registration parameters list & correctly generate the spec files for HySDS

- [x] Add the helper script get_from_context.py` to the register job repository

**Comment by NamrataM** [comment]
Script `get_param.py` already existst which does the job of getting values from the context file given a parameter name

**Comment by gchang** [comment]
@sujen1412 to add a test in the DPS unit test

**Comment by anilnatha** [comment]
Review Algorithm Registration UI @anilnatha

**Comment by gchang** [comment]
Next step is to push to DIT

**Comment by gchang** [comment]
New containerized API has new format already.
