### ISSUE TITLE
Error pop up in bottom right does not go away and is annoying when using terminal

### ISSUE THREAD

**Issue by lauraduncanson** [MAAP-Project/ZenHub#514]
**Describe the bug**
When there's an error e.g. from not having a fully committed repo when trying to register an algorithm the error message stays up for a long time - maybe until workspace restart? Blocks visibility of terminal, is annoying.

**To Reproduce**
Try to register an algo that isn't fully committed

**Expected behavior**
The error popping up is fine (although redundant) but it should go away after maybe 5 seconds. Or have an 'x' option like the error messages that pop up when you first open a workspace (which are also a mystery and make users think something is wrong but that's another topic)

**Screenshots**
<img width="996" alt="Screen Shot 2022-02-09 at 12 56 27 PM" src="https://user-images.githubusercontent.com/62670136/153261039-17a44c40-4f0c-4d96-99fe-88d7773a273c.png">

**Comment by marjo-luc** [comment]
Resolved. 

Text with white space will wrap:
![whitespace.png](https://images.zenhubusercontent.com/5eea86b79801f3519458f31d/82b06800-5c11-47d4-ae4a-06818bad39a1)

Text with no white space will overflow:
![no_whitespace.png](https://images.zenhubusercontent.com/5eea86b79801f3519458f31d/d08f15b5-0d30-406a-93c3-7f929d63db7b)
