### ISSUE TITLE
UpgradeCAS to v6.4.5

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#516]
Perform a CAS upgrade in the MAAP auth service to bring our SSO libraries up-to-date and protect against security vulnerabilities in recent log4j versions. As part of this upgrade, address the following:

1. Upgrade CAS to v6.4.5.
2. Create a CI project for simplifying future CAS upgrades and deployments.
3. Streamline the source code in the CAS Overlay project to minimize code refactoring in future upgrades.
4. Alter the login process flow for new users so that only active accounts are granted a MAAP GitLab account.

**Comment by oddes** [comment]
completed.
