### ISSUE TITLE
Add Build Command option to Algorithm Registration

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#524]
In addition to the `run_command` setting in the MAAP algorithm_config.yaml file, allow for a new `build_command` setting that gets executed at algorithm registration time.

This feature has been applied to the Ops DPS wrapper to mitigate DoS-like errors being encountered by UWG users. For this story, the following tasks are needed to add formal `build_command` support to MAAP:

1. Deploy ADE workspace images with the [new register_url.json schema](https://github.com/MAAP-Project/maap-jupyter-ide/blob/develop/submit_jobs/submit_jobs/register_url.json)
2. Synchronize the register-repo updates on Ops to ensure that the `build_command` feature is available to the DPS wrapper across UAT and DIT (see https://github.com/MAAP-Project/ZenHub/issues/518 ).

Testing notes:

1. User should be able to register and run algorithms with OR without the `build_command` setting in the config file.
2. Ensure that the build_command is being executed at registration-time in all MAAP environments

**Comment by gchang** [comment]
Workspaces still being built.

**Comment by bsatoriu** [comment]
The workspaces are now built and verified in ops:

[mas.dit.maap-project.org/root/maap-workspaces/jupyterlab3/vanilla:dit](http://mas.dit.maap-project.org/root/maap-workspaces/jupyterlab3/vanilla:dit)
[mas.dit.maap-project.org/root/maap-workspaces/jupyterlab3/r:dit](http://mas.dit.maap-project.org/root/maap-workspaces/jupyterlab3/r:dit)

**Comment by anilnatha** [comment]
Ready for testing @oddes

**Comment by oddes** [comment]
'mas.ops.maap-project.org/root/jupyter-image/vanilla:develop' registration is broken for the image:

**Comment by oddes** [comment]
Works as expected.
