### ISSUE TITLE
See hidden files in JupyterLab interface

### ISSUE THREAD

**Issue by ashiklom** [MAAP-Project/ZenHub#526]
**Is your feature request related to a problem? Please describe.**

It would be nice to be able to edit hidden files in the JupyterLab interface. Lots of useful stuff lives in hidden files and folders, such as SSH configurations, environment variables, advanced git customizations (e.g., GitHub Actions, git hooks), or other configuration files.

**Describe the solution you'd like**

Best solution is to enable hidden files in JupyterLab. This seems to require a [server-side setting](https://jupyterlab.readthedocs.io/en/stable/user/files.html#displaying-hidden-files) and/or launching Jupyter as:

```
jupyter lab --ContentsManager.allow_hidden=True
```

As a workaround (and, useful in general, though technically a separate issue...), it would be nice to add a basic text editor like vi(m) or nano to the base image, so people can at least edit these files in the terminal.

**Comment by gchang** [comment]
Will probably be available with the Jupyter 3.x update

**Comment by marjo-luc** [comment]
Confirming this is available in Jupyter 3 on DIT. Users must select `View->Show Hidden Files` to make hidden files viewable. This update will be propagated to UAT and OPS after they have been updated to Jupyter 3.

![hidden_files.png](https://images.zenhubusercontent.com/5eea86b79801f3519458f31d/4538b746-01a5-409e-9b91-fabd4f9f982chis)
