### ISSUE TITLE
Convert custom extensions into npm package

### ISSUE THREAD

**Issue by marjo-luc** [MAAP-Project/ZenHub#530]
Extensions that need to be converted:
- [x] ~dps_info~
- [x]  ~dps_magic~
- [x]  edsc_extension
- [x]  insert_defaults_to_notebook
- [x]  ipycmc
- [x]  maapsec
- [x]  show_ssh_info
- [ ]  ~submit_jobs~
- [x]  user_meta_form

**Comment by marjo-luc** [comment]
Created an npm package for the frontend component of the edsc jupyter extension. It may be found here: https://www.npmjs.com/package/@maap-jupyterlab/edsc-jupyter-extension

Updates made to the extension to make it jupyter v3 env compatible:
1. Bumped up react & typescript version.
2. Modified tsconfig.json and package.json to resolve typescript conflicts.
3. Refactored how global variables are used.
4. Resolved 'object possibly null or undefined' errors
5. Addressed 'implicit type none' warnings

Backend to be integrated into existing our custom, jupyter server extension.

**Comment by marjo-luc** [comment]
Created an npm package for the user metadata form extension.
npm package: https://www.npmjs.com/package/@maap-jupyterlab/umf-jupyter-extension
MAAP-Project git repo: https://github.com/MAAP-Project/umf-jupyter-extension

No updates to the extension needed to be made beyond bumping the Jupyter packages up to v3. This extension does not have a backend that needs to be integrated into the custom server extension.

Updates made to the extension to make it jupyter v3 env compatible:

**Comment by marjo-luc** [comment]
Created an npm package for the frontend component of the maapsec extension.
npm package: https://www.npmjs.com/package/@maap-jupyterlab/maapsec-jupyter-extension
MAAP-Project git repo: https://github.com/MAAP-Project/maapsec-jupyter-extension

Updates made to the extension to make it jupyter v3 env compatible:

1. Bumped up react & typescript version.
2. Modified tsconfig.json and package.json to resolve typescript conflicts.
3. Resolved 'object possibly null or undefined' errors

Backend to be integrated into existing our custom server extension.

**Comment by marjo-luc** [comment]
Is the dps_magics extension used? It looks like it serves the same purpose as the maap-py library. If this extension does not support any use cases the maap-py library does not already support, we may want to consider archiving this extension.

**Comment by marjo-luc** [comment]
The `show_ssh_info` extension has been renamed to `user-management-jupyter-extension`. I'm running into some keycloak issues preventing me from building this extension. I will wait until I have the backend for this extension implemented, and these issues resolved, before publishing the frontend portion to npm.

MAAP-Project git repo: https://github.com/MAAP-Project/user-management-jupyter-extension

Updates made to the extension to make it jupyter v3 env compatible:
1. Bumped up react & typescript version
2. Minor type updates

**Comment by marjo-luc** [comment]
The dps_magics extension will be archived since it serves a similar use case as the MAAP-py library. All magics the dps_magics extension provided are available to users through MAAP-py.

**Comment by marjo-luc** [comment]
Created the dps jupyter server extension and tested endpoints locally using a trivial jupyter frontend extension.

npm package: https://www.npmjs.com/package/@maap-jupyterlab/dps-jupyter-server-extension
MAAP-Project git repo: https://github.com/MAAP-Project/dps-jupyter-server-extension

**Comment by gchang** [comment]
Waiting on ipycmc

**Comment by marjo-luc** [comment]
Assessing ipycmc use case and determining whether alternative tools already deployed satisfy those use cases. Closing this ticket as all extensions we want to convert have been converted.
