### ISSUE TITLE
[Data]: GEDI L4B Gridded Aboveground Biomass Density, Version 2

### ISSUE THREAD

**Issue by spa0002** [MAAP-Project/ZenHub#533]
**Dataset Name**
Name: GEDI L4B Gridded Aboveground Biomass Density, Version 2
Short Name: GEDI_L4B_Gridded_Biomass_2017

**Dataset Description**
This Global Ecosystem Dynamics Investigation (GEDI) L4B product provides 1 km x 1 km (1 km, hereafter) estimates of mean aboveground biomass density (AGBD) based on observations from mission week 19 starting on 2019-04-18 to mission week 138 ending on 2021-08-04. The GEDI L4A Footprint Biomass product converts each high-quality waveform to an AGBD prediction, and the L4B product uses the sample present within the borders of each 1 km cell to statistically infer mean AGBD. The gridding procedure is described in the GEDI L4B Algorithm Theoretical Basis Document (ATBD). Patterson et al. (2019) describes the hybrid model-based mode of inference used in the L4B product. Corresponding 1 km estimates of the standard error of the mean are also provided in the L4B product. Uncertainty is due to both GEDI's sampling of the 1 km area (as opposed to making wall-to-wall observations) and the fact that L4A biomass values are modeled in a process subject to error instead of measured in a process that may be assumed to be error-free.

**Requestor name/affiliation**
Samuel Ayers/NASA-IMPACT, MAAP Data team

**Platform/Instrument/Method**
International Space Station/Global Ecosystem Dynamics Investigation

**URL or DOI to dataset description**
https://doi.org/10.3334/ORNLDAAC/2017

**URL to download or access data**
https://daac.ornl.gov/cgi-bin/dsviewer.pl?ds_id=2017

**Data License**
This dataset is openly shared, without restriction, in accordance with the [EOSDIS Data Use Policy](https://earthdata.nasa.gov/earth-observation-data/data-use-policy).

**Intended science use case**
GEDI L4B Gridded Aboveground Biomass Density, core MAAP dataset

## Optional

**Approximate size of data**
2.58219

**Additional information**
N/A

**Comment by TonHai1111** [comment]
Collection metadata published: https://github.com/NASA-IMPACT/active-maap-sprint/issues/137
ingest and publish data: https://github.com/NASA-IMPACT/active-maap-sprint/issues/128
