### ISSUE TITLE
Update Welcome to MAAP emails

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#536]
I've updated the "Welcome to MAAP!" email notifications in UAT. This is a first stab at improving our email notifications, a more thorough update will be done when we remove syncopy console and implement a custom email solution.

In this update..

* I updated the "Welcome to MAAP!" notification that uses the template `UserStatusUpdate`, where it is only sent when a user creates an account and their status is automatically set to "active" or when their status is changed to "active". I also updated the text in this email to reflect this scenario.
* I created a new "Welcome to MAAP!" notfication using a new template named `UserSuspendedStatusUpdate`, where it is only sent to users when a new account is created and their status is set to "suspended". The text in this email reflects this scenario as well.

Both emails are only sent to the user.

@oddes I will forward you samples of the two notifications listed above for your reference.

Let me know if you have any questions.

**Comment by oddes** [comment]
it works as expected. Minor issues will be communicated in other ticket.
