### ISSUE TITLE
Upgrade to Wordpress 6 w/extensions

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#545]

**Comment by anilnatha** [comment]
I've upgraded WP to 6.0.2 in the `maap-api-portal` repo which uses docker images with successful results.

I've also upgraded WP in DIT and UAT to version 6.0.2 and ensured all plugins are upgraded to their latest versions with successful results.

@oddes We're ready for you to test the portal general functionalities (are all wordpress pages accessible, are they loading/rendering correctly, etc.)  If your tests pass, we can schedule a date/time to upgrade OPS.

**Comment by oddes** [comment]
1. metadata page from Tool section, https://mmt.maap-project.org/ throwing 503 error.
2. EDSC on ADE also throwing error, need to be configured correct.

**Comment by anilnatha** [comment]
> 1. metadata page from Tool section, https://mmt.maap-project.org/ throwing 503 error.
> 
>     2. EDSC on ADE also throwing error, need to be configured correct.

@oddes Thank you for testing the platform.  To my knowledge, these issues are unrelated to the upgrade to WordPress 6.  Unless @gchang or @bsatoriu knows of a dependency that I'm unaware of, I would treat these as separate issues and open new tickets.

For the time being, unless something objects, I'll proceed with promoting WordPress 6 to OPS this week.

**Comment by anilnatha** [comment]
WordPress has been upgraded in OPS and is ready for testing @oddes

**Comment by oddes** [comment]
Looks good.
