### ISSUE TITLE
New MAAP users are ACTIVE by default; should be SUSPENDED

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#546]
When signing into MAAP initially, MAAP accounts on Ops are currently set to status "active". New users should be suspended pending admin approval.

**Comment by bsatoriu** [comment]
@oddes please test this fix on UAT. Test criteria:

1. A newly created URS account should have a "suspended" status upon logging into MAAP initially, as shown here:
![Screen Shot 2022-06-01 at 5 45 40 PM](https://user-images.githubusercontent.com/27687558/171524538-e97f896c-219e-4f05-a078-ce3bce3c1efb.png)
NOTE: the emails on UAT are not configured correctly at the moment, so please use the CAS status page to verify.
2. Change the user's status in Syncope from "suspended" to "active" and try logging in again. Make sure the new status is "active".
3. ESA users should have a status of "active" by default. Please use my ESA account to verify on UAT.

**Comment by anilnatha** [comment]
Hey @bsatoriu,

I tested this on UAT using a new test account and after initial login:

* The test account's profile page shows "pending activation" which would only happen if my user status was set to `pending`.
* Also, this test user's account status is listed as "suspended" in our Syncope Console.

**Comment by oddes** [comment]
verified, looks good.
