### ISSUE TITLE
Create WP admin 'users' page

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#547]
Create a simple page in the MAAP portal that allows MAAP admins to view all users and manage their accounts. This page is intended to replace the Syncope console.

**Comment by bsatoriu** [comment]
@anilnatha @gchang @oddes here is the users page I put together for your review: https://dit.maap-project.org/maap-admin/ (login required)

This page uses a jquery datatable, so the data is fetched once and can be sorted/filtered/paged on the client. Clicking the status link lets you toggle the user's status.

**Comment by anilnatha** [comment]
Thanks @bsatoriu I'll take a look.  This will come in very handy to test my email functionality as I'm still trying to resolve the issue with text based emails.

**Comment by bsatoriu** [comment]
The admin users page and pre-approved list manager have been moved to the WordPress
 admin area as part of the consolidation of our WordPress customizations into our new WordPress plugin. For more info and screenshots, please see https://github.com/MAAP-Project/maap-wp-plugin

**Comment by bsatoriu** [comment]
@oddes this feature is ready to test in UAT: https://uat.maap-project.org/wp-admin/admin.php?page=maap-admin

Features to test include:
- Register a new URS account in MAAP, and verify the new user appears in this admin list with a status of "suspended"
- Verify you receive an email notification indicating you have a "SUSPENDED" MAAP account
- Change the user's status to "active". 
- Verify you receive an email notification indicating you have an "ACTIVE" MAAP account.

**Comment by oddes** [comment]
Created a new user and it is triggering as expected for a new user: Please see attached screens for the emails triggered for admin and user:

<img width="878" alt="Screen Shot 2022-07-05 at 9 50 41 AM" src="https://user-images.githubusercontent.com/34038615/177389851-10182064-c156-4fa3-a4b5-dc6b71e7804e.png">
<img width="1370" alt="Screen Shot 2022-07-05 at 11 05 29 AM" src="https://user-images.githubusercontent.com/34038615/177389866-f4bfeadd-845c-40a6-b596-2c8d84bff0c3.png">
