### ISSUE TITLE
Create an email utility

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#548]
We need to port the email functionality that exists in Syncope Console to our API codebase so that we can retire Syncope Console.

The email utility should provide the ability to

- [x] Send html and plain text emails
- [x] Inform the recipient (in some cases) which environment the email was triggered from

Emails that cover the following conditions need to be created
- [x] A new user signs up with a status of 'active'
  - [x] A Welcome to MAAP email sent to the recipient
  - [x] A new user alert sent to MAAP JPL Admins
- [x] A new user signs up with a status of 'suspended'
  - [x] A Welcome to MAAP email sent to the recipient
  - [x] A new user alert sent to MAAP JPL Admins
- [x] A user's status has been changed from _suspended_ to _active_ sent to the user
- [x] A user's status has been changed from _active_ to _suspended_ sent to the user

**Comment by anilnatha** [comment]
@bsatoriu There are two emails that need to be wired up that are awaiting a change to the members endpoint for when a user's email passes our whitelist and the user is auto approved that we spoke of last week.

**Comment by bsatoriu** [comment]
@anilnatha the new pre-approved functionality is ready in the develop branch.

https://github.com/maap-project/zenhub/issues/549

**Comment by anilnatha** [comment]
Thanks for making this update @bsatoriu 

I've modified the `members` endpoint to account for this change. We now send the proper email notification based on the user's status upon registration.

**Comment by anilnatha** [comment]
@oddes This ticket is ready to be tested as well. It was included in the code push that @bsatoriu made to UAT. You may have already verified some of this via other tickets, but I wanted to list out the emails a user would receive during their onboarding experience and other activities on the site so you're aware of them:

## New User Registration

### Suspended Users

When a new user registers using an email address that _does not_ match an email in the pre-approved email list (#549). Two emails will be sent out by the system:

* An email will be sent to a MAAP Admin informing them that a new user has registered with a status of suspended and that an action on their part is needed.
* An email will be sent to the user welcoming them to MAAP and providing links to helpful information. This email also informs them that their account is pending activation by a MAAP Admin.

### Active Users

When a new user registers using an email address that matches an email in the pre-approved email list (#549). Two emails will be sent out by the system:

* An email will be sent to a MAAP Admin informing them that a new user has registered with a status of Active.
* An email will be sent to the user welcoming them to MAAP and providing links to helpful information.

## User Status Change

When an admin updates a user's status on MAAP, _one_ of following emails will be sent to the user

* If their status is changed to 'Active', an email will be sent to the user letting them know their account has been activated.
* If their status is changed to 'Suspended', an email will be sent to the user letting them know their account has been deactivated.


Please let me know if you have any questions about this functionality.

**Comment by oddes** [comment]
Works as expected.
