### ISSUE TITLE
Create pre-approved email tool

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#549]
Add API support and UI tool for managing pre-approved MAAP emails. Wildcards are should be allowed for "ends-with" email values. Examples:

```
        Sample 1. Any email ending in "@maap-project.org" is pre-approved
        {
            "email": "*@maap-project.org"
        }

        Sample 2. Any email matching "jane.doe@maap-project.org" is pre-approved
        {
            "email": "jane.doe@maap-project.org"
        }
```

- [x] Create API create/read/delete endpoints
- [x] Create Pre-Approved manager in Wordpress to allow for listing, adding, and removing entries

**Comment by bsatoriu** [comment]
This tool has been deployed to DIT. Please see the [maap-wp-plugin](https://github.com/MAAP-Project/maap-wp-plugin) project for more info.

**Comment by bsatoriu** [comment]
@oddes this is ready to test in UAT: https://uat.maap-project.org/wp-admin/admin.php?page=maap-pre-approved

Features to test include:

- Add a new pre-approved email
- Create a new URS account using a new pre-approved email, and verify that the MAAP account status is active upon first login
- Delete a pre-approved email

**Comment by oddes** [comment]
Looks good, as expected.

![Screen Shot 2022-07-08 at 7.47.48 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/ac4dd600-8d1a-4483-89fa-173fcb438e78)
