### ISSUE TITLE
Setup scheduled API EC2 snapshots

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#550]
Setup daily EC2 snapshots for the Ops API EC2 instance to backup API data.

**Comment by bsatoriu** [comment]
Daily snapshots are configured for the Ops API EC2 instance

**Comment by bsatoriu** [comment]
To test, check the API volume snapshots to ensure daily entries are being generated.

**Comment by gchang** [comment]
Kicking back as the automated snapshot seems to have failed.

**Comment by bsatoriu** [comment]
## Testing Requirements

Check the snapshots in the Ops AWS account to verify that a snapshot exists for each of the last seven days.

**Comment by bsatoriu** [comment]
@oddes here is a screenshot of the API EC2 snapshots. I will go ahead and close this since this image verifies the snapshots are correctly being generated and retained for seven days.

<img width="1114" alt="Screen Shot 2022-11-16 at 2 54 22 PM" src="https://user-images.githubusercontent.com/27687558/202312070-d7f2c68b-d40e-4f0f-b1a7-405729bc869e.png">
