### ISSUE TITLE
Update MAAP Admin URLs linked in emails

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#556]
The new user signup alerts sent to admins need to be updated so they link to the MAAP Admin Interface that is part of the Wordpress dashboard.

**Comment by anilnatha** [comment]
- [ ] Update the email templates
- [ ] Add new Gitlab CI Variable to store the path to the admin dashboard
- [ ] Update the `deploy.sh` script to add the new variable to `settings.py`

**Comment by anilnatha** [comment]
@oddes This issue is ready to be tested. There is a link to the new User Dashboard (#547) that is included in the new user email alert sent to Admin's for suspended users.

**Comment by oddes** [comment]
@anilnatha @bsatoriu 
we are still getting the syncope url in the admin email, we need to disable, right?

**Comment by bsatoriu** [comment]
@oddes no, this user in your screenshot was registered in the Ops environment. The new emails are only deployed to UAT currently.

**Comment by oddes** [comment]
Looks good.
