### ISSUE TITLE
Fix "Account Service" information on profile page

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#560]
Account service (aka auth client) information is no longer being displayed on a user's profile. In addition, the link a user visit's to update their profile which is dependent on the auth client information.

**Comment by anilnatha** [comment]
@oddes We have fixed this issue and a user's Account Service should be properly displayed once again when viewing their profile for users that rely on EarthData or Gluu (ESA) for authentication.

**Comment by oddes** [comment]
works as expected.
