### ISSUE TITLE
WP User Manager Deployment

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#561]
This issue relates to the WP Manager deployment to the Ops environment.

**Comment by bsatoriu** [comment]
# UAT Deployment steps

## GitLab Auth Service 
- Remove extraneous CI workflow variables
- Change .gitlab-ci.yml to point to master branch
- Build image

## GitLab maap-api-nasa-ci 
- Synchronize maap-auth-ci variables
- Synchronize settings.py (GIT settings in particular)
- Build image

## Host EC2 instance

### MAAP API
in /var/www/maap-api-nasa: `pip install -r requirements.txt`
- Synchronize member table schema
- Migrate user status values from syncope
- Update member created date using member_session:
  ```sql
  update member m
  SET creation_date = (select min(creation_date) from member_session where member_id = m.id );
  ```
 
### WordPress
- From wp-plugins folder:
  ```
  git clone https://github.com/MAAP-Project/maap-wp-plugin.git
  sudo mv maap-wp-plugin maap
  ```
- Check permissions on maap folder
- Delete old profile page
- Add new profile page link to WP menu

**Comment by anilnatha** [comment]
Hey @bsatoriu, if you and @oddes are able to verify that issue #562 is good, we should add the following task to your Wordpress task list as the first task:

* Modify `functions.php`: comment (and later delete) code that was migrated to plugin. See #562 for code that needs to be commented/deleted.
