### ISSUE TITLE
Migrate code to maap-wp-plugin

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#562]
The following code needs to be migrated to maap-wp-plugin:

At the top of the file:
```php
################################################################################
// Define Session Duration (WP session duration default is 48 hrs/2 days)
define( 'MAX_SESSION_DURATION', 24*60*60); // value should be in seconds
```

At the bottom of the file:
```php
/**
 * Update WordPress session duration
 */
add_filter('auth_cookie_expiration', 'my_expiration_filter', 99, 3);
function my_expiration_filter($seconds, $user_id, $remember){

    //http://en.wikipedia.org/wiki/Year_2038_problem
    if ( PHP_INT_MAX - time() < constant("MAX_SESSION_DURATION") ) {
        //Fix to a little bit earlier!
        return(PHP_INT_MAX - time() - 5);
    }
	
    return constant("MAX_SESSION_DURATION");
}
```

In addition, the following code is needed by CAS but I'm unsure if it will fire when the site is loaded if we move it into our plugin. Need to do some testing/research on this.

```php
################################################################################
/**
 * Create a session so that when authn/authz occurs, it can be used to store CAS information
 */

if (!session_id()) {
	session_start();
}
```

**Comment by anilnatha** [comment]
@oddes @bsatoriu 

I've migrated this to UAT for testing.  If everything works as intended, this should be included in the push to OPS.

Things to test for:

- [ ] URS users are able to login and view their profile info. Also check that EarthData is named in the "Updating your account information" section.
- [ ] ESA (Gluu) users are able to login and view their profile info. Also check that ESA is named in the "Updating your account information" section.

**Comment by bsatoriu** [comment]
My ESA user profile page. Note the missing account info for ESA users is a known issue that we're addressing next sprint.

<img width="1095" alt="Screen Shot 2022-07-07 at 6 28 02 PM" src="https://user-images.githubusercontent.com/27687558/177898338-756bd750-c099-4088-a6a8-942ec9300f46.png">

**Comment by anilnatha** [comment]
@bsatoriu How about I hide all the user metadata fields except "Account Service" for ESA members until we update our platform to save ESA member account?

**Comment by bsatoriu** [comment]
@anilnatha my plan is deploy the new plugin next Friday. So, I'd say if it's a quick change that can be done today, go for it. Otherwise, we can do it next sprint when we have time to do another round of tests.

**Comment by anilnatha** [comment]
@bsatoriu @oddes  I've make the quick change and deployed it to UAT for both of you to test. Now for ESA members you should only see the "Account Service" field, and the accordion block that informs you how to update your account information.

**Comment by oddes** [comment]
works as expected.
