### ISSUE TITLE
Unable to send email from WordPress

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#564]
Our WordPress installation is reporting an error when trying to send emails because we don't have sendmail set up on our server.

`error.log` was reporting:

```
sh: 1: /usr/sbin/sendmail: not found
```

**Comment by gchang** [comment]
Please verify the use of the wordpress smtp plugin.

**Comment by anilnatha** [comment]
Sendmail is installed on DIT and UAT.

WordPress's forgot password feature is working again with one caveat.  After successfully submitting the form, the user is redirected to the CAS login page instead of being sent back to the WordPress's login which can be used to login to WordPress in the even of issues with CAS/URS.  I've already reported this issue in another ticket (#591) because its unrelated to the install of Sendmail. 

@oddes I'll send the link where you can access the "Forgot Password" feature for testing via Slack.

**Comment by oddes** [comment]
works as expected.

**Comment by anilnatha** [comment]
@oddes Sendmail has been installed on OPS, please follow the same testing procedure and feel free to close this ticket if everything is working.

**Comment by oddes** [comment]
This Looks good.
