### ISSUE TITLE
List jobs MAAP API endpoint on DIT does not work as expected

### ISSUE THREAD

**Issue by marjo-luc** [MAAP-Project/ZenHub#573]
**Describe the bug**
The list jobs MAAP API endpoint on DIT returns a server error.

**To Reproduce**
1. Execute this command:
```
curl -X 'GET' \
  'https://api.dit.maap-project.org/api/dps/job/anonymous/list' \
  -H 'accept: application/json'
```
2. Response is a 500:
`<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/2.0" xmlns:schemaLocation="http://schemas.opengis.net/wps/2.0/wps.xsd" xmlns:wps="http://www.opengis.net/wps/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ows:Exception exceptionCode="FailedGetJobs" locator="GetJobs">
    <ows:ExceptionText>Failed to get jobs for user anonymous.  please contact administrator of DPS</ows:ExceptionText>
  </ows:Exception>
</ows:ExceptionReport>`

**Expected behavior**
Response should contain list of jobs for the given user if such jobs exist or a response indicating the user has no jobs. I confirmed there were jobs for this specific user. Neither of these responses should be categorized as 5XX response codes regardless.

**Comment by marjo-luc** [comment]
Fixed. Here's the pull request: https://github.com/MAAP-Project/maap-api-nasa/pull/47

**Comment by oddes** [comment]
![Screen Shot 2022-08-22 at 8.52.38 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/5ab74fdf-641b-4b8c-a5f6-5045a07cb004)
