### ISSUE TITLE
Get metrics MAAP API endpoint on DIT does not work as expected

### ISSUE THREAD

**Issue by marjo-luc** [MAAP-Project/ZenHub#574]
**Describe the bug**
The get metrics MAAP API endpoint returns a 500.

**To Reproduce**
1.  Execute this command:
```
curl -X 'GET' \
  'https://api.dit.maap-project.org/api/dps/job/8c3f7bf1-7d89-472b-9933-dcf502b54b5b/metrics' \
  -H 'accept: application/json'
```

2. Response:
`<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/2.0" xmlns:schemaLocation="http://schemas.opengis.net/wps/2.0/wps.xsd" xmlns:wps="http://www.opengis.net/wps/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ows:Exception exceptionCode="FailedGetMetrics" locator="GetMetrics">
    <ows:ExceptionText>Failed to get job metrics. list index out of range. Please contact administrator of DPS for clarification if needed</ows:ExceptionText>
  </ows:Exception>
</ows:ExceptionReport>`

**Expected behavior**
The response should contain the job metrics if the job exists or a message to the user indicating there are no metrics available for the given job id.

**Comment by marjo-luc** [comment]
Created pull request resolving this issue.
https://github.com/MAAP-Project/maap-api-nasa/pull/46

**Comment by marjo-luc** [comment]
@oddes 

Here is the test plan for this ticket:

1. Navigate to https://api.dit.maap-project.org/api/
2. Expand the `dps/job/{job_id}/metrics tab`
3. Submit the GET request using a valid job id (e.g. d421e25b-4520-40f1-a5d9-0aba53eb57f8)
4. Confirm the response code is 200 and the response body is similar to this:
```
<metrics>
  <machine_type>t3a.xlarge</machine_type>
  <architecture />
  <machine_memory_size>None</machine_memory_size>
  <directory_size>7306</directory_size>
  <operating_system />
  <job_start_time />
  <job_end_time />
  <job_duration_seconds>None</job_duration_seconds>
</metrics>
```

**Comment by oddes** [comment]
![Screen Shot 2022-08-22 at 8.43.19 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/a5ca6ff7-e231-4220-80ab-dab005036473)
