### ISSUE TITLE
AWS S3 Auth Fails (Forbidden)

### ISSUE THREAD

**Issue by jjfrench** [MAAP-Project/ZenHub#576]
**Describe the bug**
Call to maap-py AWS earthdata_s3_credentials returns...
`requests.exceptions.HTTPError: 403 Client Error: FORBIDDEN for url: https://api.ops.maap-project.org/api/members/self/awsAccess/edcCredentials/https%253A%252F%252Fdata.ornldaac.earthdata.nasa.gov%252Fs3credentials`

**To Reproduce**
1. Create a jupyter notebook inside of ADE
2. Use maap-py's maap.submitJob

Example code snippet:
```
import uuid
from maap.maap import MAAP

maap = MAAP(maap_host='api.ops.maap-project.org')
aoi = "https://maap-ops-workspace.s3.amazonaws.com/shared/jjfrench/AKANDA_NATIONAL_PARK.geojson"
earthdata_username = "{earthdata_username}" # Insert earthdata username
columns = "-"
query = "-"
limit = 2

# Submitting a DPS job
result = maap.submitJob(
    identifier="Simple Subset",
    algo_id="gedi-subset_ubuntu",
    version="gedi-subset-0.2.4", # Most recent version of GEDI subset code
    queue="maap-dps-worker-8gb",
    username=earthdata_username,
    aoi=aoi,
    columns=columns,
    query=query,
    limit=limit,
)
print(result)
```
- example notebook can be found in ADE under /shared-buckets/jjfrench/GEDI_L4A_Subsetting.ipynb

**Expected behavior**
Expecting to successfully download granules from s3, then subset, and then return urls to resulting gpkg.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: chrome
 - Version: 103.0.5060.114 (Official Build) (arm64)

**Additional context**
Running the same subsetting code in the ADE terminal successfully downloads granules and subsets, returning expected results.

**Comment by chuckwondo** [comment]
@bsatoriu, sorry to bug you immediately upon your return from vacation, but this issue has been blocking us for quite some time now (and I suspect perhaps blocking others as well), so I just want to see if I can persuade you to put this at or near the top of your priority list.

**Comment by bsatoriu** [comment]
@chuckwondo no problem -- I am working on this and expect to have a fix in the next day or two. There were changes made to all the JupyterLab extensions recently and a couple extensions, including the one this function relies on, were omitted from the latest workspace image. I'll follow up ASAP.

**Comment by chuckwondo** [comment]
Awesome! Thanks so much!

**Comment by bsatoriu** [comment]
@jjfrench @chuckwondo this is resolved. I verified the AWS functions are all working now in DPS. Sorry for the long wait!

**Comment by jjfrench** [comment]
@bsatoriu, nice! I can confirm that I'm getting expected results now. Thanks!
