### ISSUE TITLE
MAAP API needs to be updated to accommodate recent Mozart API changes

### ISSUE THREAD

**Issue by marjo-luc** [MAAP-Project/ZenHub#577]
MAAP API config was recently updated to reflect HySDS v4 install. (See here for details: https://repo.dit.maap-project.org/root/maap-api-nasa-ci/-/merge_requests/1). This update has revealed inconsistencies between the MAAP API and the Mozart API interfaces.

Request MAAP API makes:
`/mozart/api/v0.2/job/info?id={'id': 'c4b1d811-a03a-45f2-99d0-4db4bffeb0bf', 'tags': ['test', 'test']}`

Request Mozart API is expecting:
`/mozart/api/v0.2/job/info?id=c4b1d811-a03a-45f2-99d0-4db4bffeb0bf`

MAAP API request needs to be updated so it submits a valid request.

**Comment by marjo-luc** [comment]
Fixed. Test plan outlined in #573 will be sufficient to test these changes.
https://github.com/MAAP-Project/maap-api-nasa/commit/b87ae49091b15f99c2c900673e6dc837eff9036e

**Comment by oddes** [comment]
Tested in 573.
