### ISSUE TITLE
Cleanly deploy maap api from the CI

### ISSUE THREAD

**Issue by sujen1412** [MAAP-Project/ZenHub#579]
Currently the deploy script in the maap-api ci does not clear out the existing files before uploading the new ones. Which causes some deprecated / git removed files to persist. 

Suggestion is to rm the existing api folder before uploading the new one. 

Blocker: The existing api directory contains a python venv which is not created by the CI. 
Potential Solution: Create the venv each time we deploy.

**Comment by gchang** [comment]
Predates dockerization, this tix obsolete.
