### ISSUE TITLE
Integrate papermill into JupyterLab in ADE

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#58]
Papermill allows the execution of a notebook as a script, this could allow the DPS to run notebooks instead of needing a python script.

**Comment by gchang** [comment]
Please commit an example notebook to test this functionality.

**Comment by echyam** [comment]
notebook repo is at https://repo.nasa.maap.xyz/maap-devs/papermill_example/tree/master
example notebook is `sine.ipynb`
