### ISSUE TITLE
Gitlab Security Update

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#581]
https://about.gitlab.com/releases/2022/07/28/security-release-gitlab-15-2-1-released/

**Comment by gchang** [comment]
There's a particular upgrade path from 14.x to 15.x too (https://docs.gitlab.com/ee/update/index.html#upgrade-paths). I'm not sure if what we're running is vulnerable, but would be good to evaluate what version to upgrade to.

**Comment by bsatoriu** [comment]
I ran the GitLab upgrade to v15.3.1 on DIT, UAT and Pilot Ops.
