### ISSUE TITLE
Fix CAS SSO special character errors

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#587]
When signing in through CAS using a Norwegian character like "ø", the CAS overlay fails to encode the string correctly, preventing the profile data from being entered into the MAAP API.

**Comment by bsatoriu** [comment]
## Testing requirements

Use this special character (or any non-Latin character) in the first or last name for the URS account when registering: ø

**Comment by oddes** [comment]
works as expected. Please see attached.

![Screen Shot 2022-09-14 at 8.45.59 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/2e6dbb98-f941-49bf-abdf-5977fbb2f99b)
