### ISSUE TITLE
Profile page rendering incorrectly

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#589]
There is a minor rendering issue in OPS on the user profile page shown in the screenshots below. I do not believe this is related to the recent upgrade to WordPress 6 (#545), but I'm not completely ruling it out. Need to compare the profile page code between UAT and OPS to verify.

### UAT

<img width="1680" alt="Screen Shot 2022-09-14 at 10 10 47" src="https://user-images.githubusercontent.com/931107/190219533-b679152d-28ed-4ce4-a33d-839af8bb6a02.png">

### OPS

<img width="1680" alt="Screen Shot 2022-09-14 at 10 10 53" src="https://user-images.githubusercontent.com/931107/190219572-7a1fc1f6-3772-4c3a-8294-204b8a83f5f0.png">

**Comment by anilnatha** [comment]
I've resolved this issue. A block of CSS code was removed from our `custom.css` file in WordPress so I added it back after comparing the CSS file across our three environments.

@oddes This is ready for you in OPS to verify if everything is working as intended.

**Comment by oddes** [comment]
Looks good.
