### ISSUE TITLE
Authorizer redirects to CAS when using forget password feature

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#591]
When the forget password form is successfully submitted, Wordpress should be redirecting to https://dit.maap-project.org/wp-login.php?checkemail=confirm&external=wordpress

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/931107/190520660-c5cca3f1-a4b6-4df0-acd5-e56ca8870b27.png">

However, the Authorizer plugin kicks in and attempts to send the user to https://dit.maap-project.org/wp-login.php?checkemail=confirm&external=cas

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/931107/190520692-d0f0a99b-641e-400d-a7d2-a3900c58ee43.png">

Note: This is a low-priority issue as it only affects admins if they need to reset their password WordPress account password.

**Comment by anilnatha** [comment]
I reported the issue to the maintainers of Authorizer to get guidance on a fix and they reported back:

> Hi, thanks for this report! This is definitely a workflow issue that should be redirecting to the WordPress login page if you are using `external=wordpress` to access the base WordPress login page. We'll work on implementing a solution for this!

https://github.com/uhm-coe/authorizer/issues/121

**Comment by anilnatha** [comment]
The maintainers of the Authorizer plugin have addressed the bug report I submitted and released an updated version of the plugin.

I updated DIT and UAT and both are redirecting properly when the lost password form is submitted.

## Testing Information

To test on UAT:

1. Visit https://uat.maap-project.org/wp-login.php?external=wordpress
2. Click the "Lost your password?" link
3. Enter the email address for your account and submit the form
4. Upon successful submission, the site should redirect you to page that informs you to "Check your email for the confirmation link...".
5. Verify that you receive an email to reset your ***WordPress*** password for MAAP. You may delete the email that was sent to your inbox.

**Comment by anilnatha** [comment]
@oddes I'll schedule a time for us to do a screen share so I can see your process to ensure there isn't something I overlooked.

**Comment by oddes** [comment]
Working as expected. We need to open a new ticket for user not able to login with user id.

**Comment by anilnatha** [comment]
@oddes 

> Working as expected. 

Thanks! I'll promote this to OPS so that you can test one last time. I'll report back when this is done.

> We need to open a new ticket for user not able to login with user id.

I looked into this. I've verified that our WordPress usernames are our email addresses.  This is shown in the WP "Users" Dashboard.  Where this is confusing is the new MAAP WP Plugin lists our _URS_ usernames.  To avoid confusion in the future, I'm tentatively considering relabeling the username field in the MAAP WP Plugin "User" view to "URS Username".  So all is good with when it comes to the lost password form.
