### ISSUE TITLE
Allow AWS Lambda Invocation

### ISSUE THREAD

**Issue by chuckwondo** [MAAP-Project/ZenHub#593]
**Is your feature request related to a problem? Please describe.**

I'd like to use the Cumulus CLI from an ADE terminal window, but it doesn't work because it invokes an AWS Lambda function and invoking Lambda functions is not permitted.

Here's an error from https://ade.ops.maap-project.org/ from running the Cumulus CLI from an ADE Terminal window:

```plain
ERROR: User: arn:aws:sts::********7067:assumed-role/MAAP-ADE-K8S/i-0a2a724f83d2024e4 is not authorized to perform:
lambda:InvokeFunction on resource: arn:aws:lambda:us-west-2:********7067:function:maap-cumulus-ops-PrivateApiLambda
because no identity-based policy allows the lambda:InvokeFunction action
```

**Describe the solution you'd like**

Allow `lambda:InvokeFunction` so that we can use the Cumulus CLI to perform Cumulus management operations for allowing users to ingest granule files generated by DPS jobs into Cumulus.

cc: @abarciauskas-bgse

**Comment by abarciauskas-bgse** [comment]
Right now we're working in 2 environments
1. DIT which is split AWS accounts for JPL and UAH/IMPACT
2. Ops - one MCP environment

For the DIT environment, and for testing purposes, I have added a "Resource-based policy document" to the "maap-dit-uw2-sqs2sf" lambda which looks like:

```json
{
  "Version": "2012-10-17",
  "Id": "default",
  "Statement": [
    {
      "Sid": "allow-maap-ade-invoke",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::304XXX:root"
      },
      "Action": "lambda:InvokeFunction",
      "Resource": "arn:aws:lambda:us-west-2:532XXX:function:maap-dit-uw2-sqs2sf"
    }
  ]
}
```

The role in the ADE is of the form:

```json
arn:aws:sts::304XXX:assumed-role/maap-dev-ec2/i-0d4a9a406dcf4f417
```

I then tried to invoke the function from ade.dit and got the same error (with different identifiers) as Chuck:

```
ClientError: An error occurred (AccessDeniedException) when calling the Invoke operation: User: arn:aws:sts::304XXX:assumed-role/maap-dev-ec2/i-0d4a9a406dcf4f417 is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:us-west-2:532XXX:function:maap-dit-uw2-sqs2sf because no identity-based policy allows the lambda:InvokeFunction action
```

So I think we still need to have the `lambda:InvokeFunction` permission added to the role associated with the EC2 instances of the ADE and the DIT.

@gchang @bsatoriu can you help identify:

1. What is the role ARN (for the ADE EC2 and DPS EC2s) we should configure with the resource-based policy document we attach to our cumulus lambdas?
2. Can you add the `lambda:invokeFuntion` permission to that role?

I think we should continue to try this out in DIT before applying the same changes to Ops.

I will add a ticket to our board to include the ADE and DPS role ARNs to our Cumulus Lambdas via the terraform deployment.

**Comment by gchang** [comment]
I've made the request to update the `maap-dev-ec2` with the AWSLambdaRole role (which includes the InvokeFunction)

**Comment by gchang** [comment]
It's been updated.

**Comment by chuckwondo** [comment]
@gchang, this doesn't address the issue in the environment that I mentioned in the initial message for this issue. Can you do the same fix to address my original error?

**Comment by gchang** [comment]
I added that to the UAT and OPS environment too now.

**Comment by chuckwondo** [comment]
Thanks @gchang! That did the trick for me, so I'm closing this issue.
