### ISSUE TITLE
Shared Documents shouldn't be visible without logging in

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#598]
https://ops.maap-project.org/shared-documents/

**Comment by anilnatha** [comment]
If everything is working satisfactory, I can publish the changes to OPS.

**Comment by oddes** [comment]
@anilnatha it looks good. ready to move to OPS.

**Comment by anilnatha** [comment]
@oddes This change has been rolled out to OPS and is ready for you to test once again.

**Comment by oddes** [comment]
works as expected. Closing.
