### ISSUE TITLE
Earthdata Search iframe in new Jupyterlab (in DIT) doesn't work

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#599]
It appears to be loading the iframe incorrectly.

**Comment by gchang** [comment]
![Screen Shot 2022-10-05 at 3.22.25 PM.png](https://images.zenhubusercontent.com/5ee7da582a6c07a5f569db2e/1c094fb8-96c2-4177-9f58-e838b501bf5a)

**Comment by marjo-luc** [comment]
Hmm. Which image is being used? Looks good to me:![Screen Shot 2022-10-05 at 3.32.38 PM.png](https://images.zenhubusercontent.com/5eea86b79801f3519458f31d/e5f2c86f-e126-4d40-bc74-e34193dc922d)

**Comment by gchang** [comment]
I was using the same basic workspace that I launched yesterday. But I just tried with a new workspace and it worked so I'll chalk it up to error between keyboard and chair. Thanks for looking.
