### ISSUE TITLE
Automatic Deployment of Updates to DPS Job API (Mozart API)

### ISSUE THREAD

**Issue by NamrataM** [MAAP-Project/ZenHub#60]
Update the HySDS terraform script for cluster setup to modify the Mozart API code as: https://repo.nasa.maap.xyz/maap-devs/maap-mozart/tree/HC-67

This is needed to support the GetStatus endpoint on the MAAP API.

**Comment by NamrataM** [comment]
There are 2 core HySDS tickets to address this:
For v3.0 - https://hysds-core.atlassian.net/browse/HC-67
For v4.0 - https://hysds-core.atlassian.net/browse/HC-247

**Comment by NamrataM** [comment]
Finished making updates to HySDS core code. PR - https://github.com/hysds/mozart/pull/23

**Comment by NamrataM** [comment]
PR for v3.0 of HySDS core update has been processed. Working with Gerald to cut a new release of HySDS.

**Comment by sujen1412** [comment]
The new version v3.0.5 is now deployed.
