### ISSUE TITLE
Write test procedures for ADE extensions

### ISSUE THREAD

**Issue by marjo-luc** [MAAP-Project/ZenHub#602]
Write TestRail test procedures for the jl3 ADE extensions.

**Comment by gchang** [comment]
Test procedures are in Test Rails.

**Comment by marjo-luc** [comment]
@oddes -- here are all the test procedures @grallewellyn and I wrote for the Jupyter extensions. Would you review them and let us know if you have any general feedback?

https://testrail.maap-project.org/index.php?/suites/view/5&group_by=cases:section_id&group_order=asc&display_deleted_cases=0

**Comment by oddes** [comment]
This looks great.
