### ISSUE TITLE
Typing in the Algorithm dropdown in Jobs UI does not filter

### ISSUE THREAD

**Issue by rtapella** [MAAP-Project/ZenHub#603]
![Screen Shot 2022-10-12 at 2.51.36 PM.png](https://images.zenhubusercontent.com/61dc908470b3029fc627fcbb/8dd69e16-c0fa-4fba-a480-a5fa87db2962)

**Comment by marjo-luc** [comment]
Fixed and deployed on DIT.![text-filter.png](https://images.zenhubusercontent.com/5eea86b79801f3519458f31d/2272468a-e1c1-458c-8ef4-c2c1bb43bcfb)
