### ISSUE TITLE
Algorithm dropdown is cut off when the list gets long

### ISSUE THREAD

**Issue by rtapella** [MAAP-Project/ZenHub#604]
The bottom half of the Jobs UI "Submit" tab seems to be a blank panel. This gives little space to the Algorithm dropdown at the top of the page, so it will get chopped off when you pull it down.
Generally speaking we'll need to work out how to handle a very long list of applications without the UI getting cut off.

![Screen Shot 2022-10-12 at 2.49.53 PM.png](https://images.zenhubusercontent.com/61dc908470b3029fc627fcbb/330d4b7d-6a50-4d06-be6c-b9ece1d3d600)

**Comment by marjo-luc** [comment]
Fixed and deployed on DIT.
![dropdown.png](https://images.zenhubusercontent.com/5eea86b79801f3519458f31d/783b082d-71e5-4373-8470-3f8640cf16fc)
