### ISSUE TITLE
Some of the base images fail to build

### ISSUE THREAD

**Issue by marjo-luc** [MAAP-Project/ZenHub#617]
The r, vanilla, and isce2 base images have been failing to build for ~1 week. All fail with an error message similar to this:
`  File "/opt/conda/lib/python3.9/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/opt/conda/lib/python3.9/site-packages/OpenSSL/crypto.py", line 1556, in <module>
    class X509StoreFlags(object):
  File "/opt/conda/lib/python3.9/site-packages/OpenSSL/crypto.py", line 1577, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'`

**Comment by gchang** [comment]
`r` image still fails

**Comment by marjo-luc** [comment]
@bsatoriu @anilnatha

**Comment by gchang** [comment]
Migrating this to #684 since we have to rebuild the r image anyway.
