### ISSUE TITLE
Button hit area exceeds boundary of button

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#629]
While testing UI changes for destructive buttons (#408), I found the hit area associated with some of these buttons is larger than the button itself. This allows the user to trigger the action associated with the button by clicking in the whitespace around the button.  The screenshots below show an example of the hit area around the button that can be targeted and one example of an error that can be generated.

### Invisible Hit Areas:

<img width="1305" alt="Screen Shot 2022-12-06 at 1 37 59 PM" src="https://user-images.githubusercontent.com/931107/206252945-4d308a41-6858-4692-8091-b3e6419fecb5.png">

<img width="1305" alt="Screen Shot 2022-12-07 at 7 56 10 AM" src="https://user-images.githubusercontent.com/931107/206253100-ed2f4505-5479-4fde-afcd-fccc916c97f2.png">

### Example error triggered clicking in one of them

<img width="1305" alt="Screen Shot 2022-12-06 at 1 38 06 PM" src="https://user-images.githubusercontent.com/931107/206253246-785697db-16ac-486a-ac53-5ce6343d11ab.png">

**Comment by anilnatha** [comment]
Hit areas around these particular buttons can no longer be targeted.

<img width="1305" alt="Screen Shot 2022-12-07 at 9 45 16 AM" src="https://user-images.githubusercontent.com/931107/206263979-e196d06f-f97c-469a-b698-027e3d522c5a.png">

<img width="1305" alt="Screen Shot 2022-12-07 at 9 45 31 AM" src="https://user-images.githubusercontent.com/931107/206263987-65da7672-757e-461e-aa3d-49a50090c194.png">

<img width="1305" alt="Screen Shot 2022-12-07 at 9 45 44 AM" src="https://user-images.githubusercontent.com/931107/206263988-8b46315c-4ac1-4d33-89b7-e85ff91bb5bd.png">

**Comment by anilnatha** [comment]
Brian has pushed this fix to DIT earlier this week and I've tested it. Awaiting push to UAT for additional testing.

**Comment by anilnatha** [comment]
This was pushed to UAT and OPS so is ready for testing.

**Comment by oddes** [comment]
@anilnatha 
are we allow to delete running workspaces?
![Screenshot 2023-02-18 at 9.54.28 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/e596746a-a600-43c3-b5af-bd65fd9bc537)

**Comment by anilnatha** [comment]
@oddes I'll need to investigate this further as I recall that this was allowed before my change, but I'll need to verify.

**Comment by anilnatha** [comment]
@oddes I checked out an older copy of the Eclipse Che codebase that predates the changes I made to the delete buttons. I've verified that the dashboard _did_ allow for the deletion of workspaces, regardless of their running status as evidenced in the screenshot below.

<img width="1792" alt="Screen Shot 2023-03-08 at 13 31 34" src="https://user-images.githubusercontent.com/931107/223855364-27ef42cc-69ab-4a37-b151-179a317d48d4.png">

If there are no additional changes needed at this time, please feel free to close this ticket.

**Comment by anilnatha** [comment]
@oddes I'm closing this ticket. If any additional changes are need, please feel free to reopen or create a new ticket.
