### ISSUE TITLE
Update footer links in Eclipse Che

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#630]
We need to make the following updates to the list of links shown in the bottom right corner of the Eclipse Che Dashboard.

1. Remove all existing links.
2. Add the following Links
  - Link titled "Report an Issue" that links to https://github.com/MAAP-Project/ZenHub/issues
  - Links to portal that take into account the environment the user is accessing:
    - Titled ~"MAAP Portal"~ "MAAP Homepage", links to portal homepage
    - Titled "User Guides", https://dit.maap-project.org/user-guides/
    - Titled "TOS", https://dit.maap-project.org/terms-of-service/
    - Titled "Open Policies", https://dit.maap-project.org/open-policies/

**Comment by anilnatha** [comment]
@gchang (fyi) the current links in the eclipse che dashboard footer don't work. Verified this in DIT, UAT, and OPS. A non-existent variable is being referenced to populate the `href` tag which is why they aren't working.

**Comment by anilnatha** [comment]
Brian merged my PR and deployed this to DIT.  @gchang Please let me know if there are any additional changes you would like to the footer before we promote it to UAT.

<img width="960" alt="Screen Shot 2022-12-20 at 14 14 23 copy" src="https://user-images.githubusercontent.com/931107/208785096-05feec77-88de-422e-bc64-194503f9fc0e.png">

**Comment by anilnatha** [comment]
This was pushed to UAT and OPS so is ready for testing.

**Comment by oddes** [comment]
All the footer links works as expected.
