### ISSUE TITLE
Workspace tooltip goes off screen

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#633]
Workspace tooltips are going off screen when viewing workspace details but work properly on the workspace listing page.

**Comment by anilnatha** [comment]
The fix is to hide the workspace tooltip on the workspace details page because there is a label that is shown next to the workspace indicator.

**Comment by anilnatha** [comment]
The [PR](https://github.com/MAAP-Project/eclipse-che-dashboard/pull/5) for this issue has been merged and code deployed to DIT. The fix works as intended.

Awaiting push to UAT to hand off testing to Sri.

**Comment by anilnatha** [comment]
Looks like this has already been pushed to UAT and OPS so is ready for testing.

**Comment by oddes** [comment]
@anilnatha 
What is the purpose of "Lear more" hyperlink, it is pointed to the same page, and as result, re-opening the same page again.![Screenshot 2023-02-20 at 12.04.10 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/74ec0a8b-e983-4681-839c-b00418978404)

**Comment by anilnatha** [comment]
@oddes The default Eclipse Che Dashboard link is supposed to go to a page that explains workspaces, but is broken. I believe you intended to post this comment as part of ticket #634.

**Comment by oddes** [comment]
issue will be covered part of #634
