### ISSUE TITLE
"Learn more" link in Eclipse Che Dashboard doesn't work

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#634]
**Describe the bug**

Clicking the "Learn More" link on the workspaces view opens a new browser tab and redirects to the workspaces view.

**To Reproduce**
1. Go to the MAAP portal, e.g. dit.maap-project.org
2. Login
3. Go to Tools -> Development to visit ADE
4. You're automatically taken to the workspaces view where the "learn more" button is available.

**Expected behavior**

Expected to see a document explaining what a workspace is.

**Screenshots**

<img width="1280" alt="Screen Shot 2022-12-20 at 14 14 23" src="https://user-images.githubusercontent.com/931107/208778119-499ab293-483c-4184-b2aa-7367f7da9bd0.png">

**Comment by anilnatha** [comment]
[PR](https://github.com/MAAP-Project/eclipse-che-dashboard/pull/8) submitted, as soon as this is deployed to DIT, I will test again.

**Comment by anilnatha** [comment]
Merged PR, need to test in DIT.

**Comment by anilnatha** [comment]
I tested my fix in DIT this past Thursday, but the new link isn't showing up in the dashboard. Need to investigate why the link isn't showing.

**Comment by anilnatha** [comment]
Hey @bsatoriu, I've tested my local code and verified that the updated "learn more" URL is being rendered when I hover over the link when this code is run locally (see bottom left corner):

<img width="1280" alt="Screenshot 2023-02-21 at 10 46 25 AM" src="https://user-images.githubusercontent.com/931107/220433988-b65713ac-777d-49d2-b2ec-50d212fcb7b2.png">

This change was successfully merged in as I see the [correct URL](
https://github.com/MAAP-Project/eclipse-che-dashboard/blob/d497684d5374fdd81dcdadc51661666ca45bc7ba/src/assets/branding/product.json#L23) in `product.json` file, but this link isn't rendered in DIT:

<img width="1280" alt="Screenshot 2023-02-21 at 10 45 47 AM" src="https://user-images.githubusercontent.com/931107/220434082-764edc2d-d14c-4c11-bdf0-35465bcda649.png">

I didn't see a repo for the `eclipse-che-dashboard` in GitLab that would take care of the CI pipeline associated with this codebase. This goes back to a conversation we had on slack about this repo as well.

**Comment by anilnatha** [comment]
I've verified that the product.json that is currently deployed (see screenshot below) doesn't match what is [committed](https://github.com/MAAP-Project/eclipse-che-dashboard/blob/d497684d5374fdd81dcdadc51661666ca45bc7ba/src/assets/branding/product.json#L22) to our repository. Once we deploy an updated build I anticipate that the issue with the 'learn more' link will be resolved.

<img width="866" alt="Screen Shot 2023-03-08 at 13 44 24" src="https://user-images.githubusercontent.com/931107/223857416-ac1f443f-3bc2-4c08-a88e-1e738c403723.png">

**Comment by anilnatha** [comment]
Awaiting redployment of eclipse che environment to test updated codebase.

**Comment by bsatoriu** [comment]
@anilnatha I set up a DIT version of the Dashboard UI here: https://repo.dit.maap-project.org/root/eclipse-che-dashboard

I also updated the GitHub action secret for the [eclipse-che-dashboard repo](https://github.com/MAAP-Project/eclipse-che-dashboard) to auto-trigger builds in this new GitLab project upon any merges or commits to the `7.25.2-maap` GitHub branch. In the event you need to manually build the GitLab project. just start a new pipeline manually as shown in this example:

<img width="1646" alt="Screen Shot 2023-03-16 at 2 50 08 PM" src="https://user-images.githubusercontent.com/27687558/225761042-91022ef2-d65f-4a40-9fa9-96c60bc330f0.png">

**Comment by anilnatha** [comment]
Updated: @bsatoriu  is resolving an issue with the eclipse che build pipeline.

**Comment by bsatoriu** [comment]
The eclipse che project has been setup and confirmed working in DIT GitLab. ADE DIT is now running the most recent code changes by @anilnatha

**Comment by anilnatha** [comment]
Verified updated is working in both OPS environments.
