### ISSUE TITLE
Change link associated with "Create Workspace" in Eclipse Che dashboard

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#635]
The "Create Workspace" link that is shown in the "Recent Workspaces" section of the Eclipse Che Dashboard" needs to be updated so that it links to the "Get Started" view instead of the "Custom Workspace" tab of the creating a workspace view.

**Comment by anilnatha** [comment]
The requirement has changed, the "create workspace" button under "Recent Workspaces" should be hidden. In addition, the "Add Workspace" button at the top of the Workspaces view should target the "Get Started" tab of the new workspace view.

**Comment by anilnatha** [comment]
[PR opened](https://github.com/MAAP-Project/eclipse-che-dashboard/pull/6), once pushed to DIT, will test.

**Comment by anilnatha** [comment]
PR merged by Brian, need to test in DIT.

**Comment by anilnatha** [comment]
Work in DIT. This was also pushed to UAT and OPS so is ready for testing.

**Comment by oddes** [comment]
Verified both UAT and OPS. looks good.
