### ISSUE TITLE
Dockerize MAAP API

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#638]
Create a docker-compose file for running and deploying the MAAP API and accompanying database. 

- [x] Define a Flask service for the REST API and Postgres service.
- [x] Configure the Postgres service to persist data on the host upon subsequent deployments
- [x] Ensure that database schema changes are applied with no data loss upon subsequent deployments
- [x] Update the CI scripts for DIT, UAT, and Ops v2 to use this new docker configuration

**Comment by gchang** [comment]
Deployed on DIT, and Ops v2, maybe not deployed in UAT
