### ISSUE TITLE
Add ipyleaflet to workspaces

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#668]
During a meeting with Aimee and Alex, they requested that ipyleaflet be added to our workspaces.

My Initial tests trying to install the package using `pip install` and `conda install` were unsuccessful. Will need to add it to our docker config instead.

We've agreed to test this in UAT.

**Comment by anilnatha** [comment]
The build for the image failed with the error:

> Encountered problems while solving:
>   - nothing provides requested ipyleaflet@0.17.2

The [`ipyleaflet`](https://anaconda.org/conda-forge/ipyleaflet) package shows as available using the channel conda-forge. I will investigate the issue.

**Comment by gchang** [comment]
Above error has been resolved, but other errors exist.

**Comment by anilnatha** [comment]
I've verified that the addition of `ipyleaflet` works using the `vanilla` and `rgedi` workspaces; 

`vanilla`

<img width="1792" alt="Screen Shot 2023-03-08 at 14 32 05" src="https://user-images.githubusercontent.com/931107/223866399-ea166623-b1c6-405f-8fca-cd52e3f1365e.png">

`rgedi`

<img width="1792" alt="Screen Shot 2023-03-08 at 14 29 45" src="https://user-images.githubusercontent.com/931107/223866259-3f1dcd70-ba22-484d-8ae9-4e1db8e52c26.png">

However, I'm unable to test this using our `isce`, `r`, and `rsgis` workspaces because the build process for those workspaces is failing.

**Comment by anilnatha** [comment]
Note: Alex has successfully tested this in DIT using the Basic Stable workspace.

Still need to test in isce, r, and rsgis workspaces.
