### ISSUE TITLE
Regression Testing - *.maap-project.org

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#672]
Perform full regression testing on the following services:

- ade.maap-project.org
- www.maap-project.org
- repo.maap-project.org

**Comment by bsatoriu** [comment]
@oddes this is ready to test. I verified that all DPS functions are working.

**Comment by oddes** [comment]
@bsatoriu 
can we fix this UI error pop-up, does not have a close button.
![Screenshot 2023-02-26 at 4.21.18 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/bf6994cc-82d8-489e-bc28-79c87b451a8b)

**Comment by bsatoriu** [comment]
I believe the 'x' in the upper right of the bottom popup message is being obscured by the long job id. @oddes I would suggest creating a separate ticket for this issue since it's common across all environments. 

The fix would likely involve truncating any long, un-hyphenated job ids within the Jupyter lab extension.

cc @grallewellyn

**Comment by grallewellyn** [comment]
Noted as something to include in the notification space plan (something that should hopefully roll out in the next couple months). Right now with the way we are doing INotifications, there isn't a central filtering that could fix a problem like this. It would need to be the individual calls to INotification that may include a job UI should be checking for this themselves.

**Comment by gchang** [comment]
Notification issue captured in #681, so we can close this tix.
