### ISSUE TITLE
Create pangeo based workspace

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#674]
Alex has requested the addition of a workspace that includes [Pangeo](https://pangeo.io/).

The Pangeo team has a [repo](https://github.com/pangeo-data/pangeo-docker-images) that details how they build their docker images that will be helpful in determining how we could build images on our platform.

**Comment by anilnatha** [comment]
@bsatoriu I've submitted a [PR](https://github.com/MAAP-Project/maap-workspaces/pull/3) to test an initial version of a pangeo based workspace.

**Comment by gchang** [comment]
Still troubleshooting build
