### ISSUE TITLE
Identify orphaned accounts (users not in the maap-users organization)

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#68]
Tried to share a workspace with Sujen (beebee8) but he didn't show up in the maap-users organization.

**Comment by bsatoriu** [comment]
@gchang I have added the following orphaned users to the maap-users org, but Che has essentially hard coded a maximum count of 30 users in the 'share workspace' screen, as well as any other member or org views featuring lists of records. For reference, see: https://github.com/eclipse/che/blob/57c43ac8cdd7111649414545a6ee9d156392d249/multiuser/api/che-multiuser-api-organization/src/main/java/org/eclipse/che/multiuser/organization/api/OrganizationService.java#L175

De-orphaned users:

- beebee8
- chuckwondo
- dooku
- esamaap
- jinn
- kaulfusa
- kbugbee
- kvirts

I will need to update the Che UI to add a max count argument to the Che org api calls. (we're at about 37 non-test users right now). I created a new ticket to track this: https://github.com/maap-project/zenhub/issues/99

**Comment by oddes** [comment]
I have Impersonate your account and successfully shared with beebee8. Please see the attached screen shot

![Screen Shot 2020-07-06 at 10.19.04 AM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/b6075ebe-7dee-4a70-8760-617e722a4c75)
