### ISSUE TITLE
A banner in new ops, Che and Wordpress, to inform users not to use them yet.

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#689]

**Comment by gchang** [comment]
Probably Gitlab too

**Comment by anilnatha** [comment]
@gchang I suppose this ticket could be repurposed to address the need to inform users that they are using the new ops, a link to report issues with new ops, and a link to switch back to the old version.

**Comment by anilnatha** [comment]
Add banner to dos for new OPS:

- [x] Update WordPress portal
- [x] Update ADE
- [ ] Update GitLab

@bsatoriu If you can bump my access to be an admin in new (and old) OPS, I can add the banner message to GitLab.
