### ISSUE TITLE
better handle differences between ops/dev env 

### ISSUE THREAD

**Issue by mayadebellis** [MAAP-Project/ZenHub#69]
currently we use an env var - things on the develop branch get built to point to DEV endpoints and everything else gets OPS. This is not great for development practices bc you need things to be merged into develop in order to run them in che. Instead we could use the url of the site (or something similar) the to determine the env and not have to hard code env variables at build

**Comment by gchang** [comment]
@mayadebellis Is this already done? I'm cleaning out some old tix.

**Comment by mayadebellis** [comment]
yep this can be closed!
