### ISSUE TITLE
Add support for s3credentials 401 redirects

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#694]
A MAAP user encountered an error trying to obtain s3 temporary credentials for the ORNL DAAC using the earthdata_s3_credentials method: `maap.aws.earthdata_s3_credentials('https://data.ornldaac.earthdata.nasa.gov/s3credentials')`

This endpoint in the MAAP API only supports 307 responses for authorization, not 401 responses. The s3 endpoint for LP DAAC uses a 307 response for authentication, hence this call returns a successful result: `maap.aws.earthdata_s3_credentials('https://data.lpdaac.earthdatacloud.nasa.gov/s3credentials')`

Modify the MAAP API `edcCredentials` endpoint to support both 401 and 307 responses during the authorization process.

**Comment by bsatoriu** [comment]
The [s3credentials endpoint](https://api.dit.maap-project.org/api/members/self/awsAccess/edcCredentials) is now updated to support both 401 and 307 redirects.

**Comment by bsatoriu** [comment]
### Testing instructions:

On Ops ADE, both of these calls should return valid s3 credentials:

```python
print(maap.aws.earthdata_s3_credentials('https://data.ornldaac.earthdata.nasa.gov/s3credentials'))

print(maap.aws.earthdata_s3_credentials('https://data.lpdaac.earthdatacloud.nasa.gov/s3credentials'))
```

**Comment by gchang** [comment]
chuck d. reviewed
