### ISSUE TITLE
parse url for EDSC parameters

### ISSUE THREAD

**Issue by mayadebellis** [MAAP-Project/ZenHub#71]

**Comment by gchang** [comment]
Completed JS implementation, need to update MAAP py

**Comment by mayadebellis** [comment]
Waiting to delpoy to dev until I make updates to maap-py, the 2 need to be changed together for things to work properly.

**Comment by mayadebellis** [comment]
Testing instructions:
These changes have been deployed to dev. In order to test start a new workspace on https://che-k8s.maap.xyz/ with the `MAAP Dev Basic Latest` stack. 
- Open the earthdata search tab
- Select a bunch of search filters. Click `view selected search parameters` from the drop down and see that the search facets you selected will appear here. There will be 2 objects shown, one for granule search and the other for collection search. They may look different from each other as the 2 styles of searches allow different inputs.
- Select the `set results limit` dropdown and set 10 as the value.
- Open a jupyter notebook. click the `MAAP` icon in the toolbar to insert the `maap-py` library. select the `paste collection search query` and the `paste granule search query`. Run the notebook to see that the queries execute.

**Comment by oddes** [comment]
As shown in the attached screenshots, Search and Query functionality is working as expected.

![Screen Shot 2020-08-13 at 1.50.36 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/2a709002-f2db-481a-8754-99811d0bef64)![Screen Shot 2020-08-13 at 1.56.37 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/cc296dbb-16f8-43b1-a15f-eb628cd0dcc5)![Screen Shot 2020-08-13 at 1.57.07 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/56fd7d97-057a-4f51-ba47-22bcd7a128f4)
