### ISSUE TITLE
Update Portal to perform the MAAP API security to get proxy tokens

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#79]

**Comment by bsatoriu** [comment]
@gchang we are currently using MAAP API's secure proxying via a modification to the Authorizer Wordpress plugin. Here is the relevant commit: https://github.com/MAAP-Project/authorizer/commit/cb2b643ab0afdee6c6e15d0b679b9744909121e1

If we are using the proxy token for other parts of the portal, my suggestion would be to modularize the token retrieval method further to make it more easily reusable to the other portal pages, but we may want to address that as part of any future portal changes that require API interfacing.

**Comment by oddes** [comment]
User can successfully upload the ssh and token works on che, as expected.
