### ISSUE TITLE
Investigate workflow for showing error logs to user, accessing user's S3 bucket from portal

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#81]

**Comment by gchang** [comment]
Need to enable Job Triage in HySDS, but there's possibly that it's buggy. @sujen1412 hasn't seen it working in an operational project.

**Comment by sujen1412** [comment]
We can start with https://hysds-core.atlassian.net/wiki/spaces/HYS/pages/199885846/Preprocessor+and+Postprocessor+Functions. 

Which is the Hysds Triage functionality and use the DPS wrapper script to redirect all output from user into the output directory and triage the entire directory. 

We would then need to update the datasets.json to upload the triage dataset into the correct location on s3 (i.e under the /username path)

**Comment by gchang** [comment]
@NamrataM to publish logs to output directory and include it in the API

**Comment by NamrataM** [comment]
Current solution:
For completed jobs:
Update `dps_wrapper` script to move files `*.log` and `_stderr.txt` from work directory into output dataset directory. This way they'll be available on S3.

For failed jobs:
Users need to pipe output of their scripts to stdout and stderr as follows:
`[script run command] > run.log 2>&1
STATUS=$?
if [ $STATUS -ne 0 ]; then
  echo "Failed to run algorithm" 1>&2
  cat run.log 1>&2
  echo "{}"
  exit $STATUS
fi`

This will allow the error and traceback to be stored in job metadata in DPS ES (Mozart ES)
We can grab that and return to user in GetResult's API Response
