### ISSUE TITLE
Add 'listContainer' support to MAAP API and maap-py

### ISSUE THREAD

**Issue by marjo-luc** [MAAP-Project/ZenHub#818]
Users want the Algorithms UI to show a list of containers available for use when registering algorithms. The MAAP API does not currently have an endpoint that returns this information, so we would need to create one. We should also consider updating `maap-py` to support this as well. The Algorithms UI would be updated to include a dropdown listing all available containers for that venue that users can choose from for registration. The default selection should be the workspace container.

We would likely need to leverage the gitlab api to get the list of containers in the registry and wrap this call within the new MAAP API endpoint. This endpoint should be protected. 

MAAP API:
`GET /mas/listContainers `

maap-py:
`maap.listContainers()`

**Comment by marjo-luc** [comment]
The base image is available as an environment parameter. This can be pulled into the UI to auto-populate the container field. There is currently no use case for the listContainers feature, but we may revisit this if that changes.

**Comment by oddes** [comment]
@marjo-luc Currently, its throwing an error. is this fixed?

AttributeError: 'MAAP' object has no attribute 'listContainers'

**Comment by oddes** [comment]
Just discussed with @bsatoriu this is fixed see below:

<img width="1792" alt="Screenshot 2023-11-02 at 6 51 26 PM" src="https://github.com/MAAP-Project/Community/assets/34038615/9158cdec-8b6e-46b2-848a-754e83ca1a03">
