### ISSUE TITLE
DPS data access via MAAP API

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#825]
For interoperability with ESA, define an endpoint that allows users to access their S3 bucket from the MAAP API, without needing to be in a workspace. Maybe also look at providing access to EFS too.

**Comment by bsatoriu** [comment]
### Testing Notes

The following python code should return a list of the folders in your MAAP workspace bucket when ran outside of the ADE environment:

```python
import boto3
import os
import json
from maap.maap import MAAP

maap_username='???'
os.environ["MAAP_PGT"] = "PGT-...." # insert valid token value

maap = MAAP(maap_host='api.uat.maap-project.org')

creds = maap.aws.workspace_bucket_credentials()
print(json.dumps(creds, indent=4))

s3 = boto3.client(
    's3',
    aws_access_key_id=creds['aws_access_key_id'],
    aws_secret_access_key=creds['aws_secret_access_key'],
    aws_session_token=creds['aws_session_token']
)
response =  s3.list_objects(Bucket=creds['aws_bucket_name'], Prefix=maap_username + '/', Delimiter='/') 

for o in response.get('CommonPrefixes'):
     print('sub folder : ', o.get('Prefix'))
```

**Comment by oddes** [comment]
<img width="1790" alt="Screenshot 2023-11-02 at 7 16 21 PM" src="https://github.com/MAAP-Project/Community/assets/34038615/f51c5755-8ef8-40d6-9f17-4797f10418bf">
