### ISSUE TITLE
ADE cleanup for extensions

### ISSUE THREAD

**Issue by marjo-luc** [MAAP-Project/ZenHub#833]
- [ ]  update MAAP extension launcher cards
- [x]  update menu items for jobs/algorithms
- [x]  persist extensions on refresh

**Comment by marjo-luc** [comment]
launcher card icons are limited to the collection of icons jupyter provides -- none of which are more suitable than the current icons. There is more work involved in creating custom icons which for which a separate ticket will be created.

**Comment by oddes** [comment]
Looks good
