### ISSUE TITLE
Parameterize maap-py granule.getDownloadUrl()

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#848]
maap-py's `granule.getDownloadUrl()` method retrieves the s3 uri for the granule. In many cases, the http url for the granule is preferred for security reasons. Add a parameter to this method to specifiy the data source, and default to https.

**Comment by bsatoriu** [comment]
### Testing notes

```
results = maap.searchGranule(page_num="1", concept_id="C1214470488-ASF", sort_key="-start_date", limit=1)

url = results[0].getHttpUrl()
# url should start with "http"

url = results[0].getS3Url()
# url should start with "s3"
```

**Comment by marjo-luc** [comment]
Tested successfully in OPS.
