### ISSUE TITLE
SSH key uploads not working 

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#850]
**Describe the bug**

The SSH upload feature in the portal doesn't work as expected. After submitting your public ssh key, no status of the upload process or of the ssh key info is saved to your profile.

**To Reproduce**
1. Go to the MAAP OPS Portal
2. Login
3. Visit your profile page
4. Scroll down to 'Public SSH Key' section
5. Try uploading your SSH public key

**Expected behavior**

After submitting your SSH public key, a user should be informed that the process was successful and the UI should list the name of the SSH public key file that was uploaded and added to the user's account.

**Screenshots**

<img width="815" alt="Screen Shot 2023-10-26 at 13 07 27" src="https://github.com/MAAP-Project/Community/assets/931107/0fddbb14-0bed-446c-82c2-346e6c11ae61">

**Comment by anilnatha** [comment]
This issue was reported by @rtapella

**Comment by marjo-luc** [comment]
I don't think there are issues with the upload. I was able to upload a public key and retrieve it from my workspace using this snippet:

'''
from maap.maap import MAAP
maap = MAAP(maap_host='api.dit.maap-project.org')

r = maap.profile.account_info()
print(r)
'''

We should probably provide users with feedback on the upload, though, and also list available keys.

**Comment by anilnatha** [comment]
Investigated the issue, looks like we are no longer returning the fields needed to display ssh key information when making a call to the `/members/:key` endpoint.

Will add the fields back to this endpoint and test.

**Comment by anilnatha** [comment]
The fixes we applied to maap-api addressed the issue and the resolution was verified to be working in DIT.

We need to promote the change to UAT for testing.
