### ISSUE TITLE
[Data]: Update GEDI L4B to v2.1 on the Biomass Harmonization Dashboard

### ISSUE THREAD

**Issue by nehahunka** [MAAP-Project/ZenHub#859]
### Dataset Name

GEDI L4B Gridded Aboveground Biomass Density, Version 2.1

### Dataset Description

See here the new GEDI L4B product: https://daac.ornl.gov/GEDI/guides/GEDI_L4B_Gridded_Biomass_V2_1.html

We would like to replace the GEDI product currently on the dashboard with the new version 2.1

The dashboard's old version 2.0 is accessible here: https://www.earthdata.nasa.gov/maap-biomass/products/gedi_l4b?map=0%2C0%2C1&lState=

### Requestor Name/Affiliation

Neha Hunka, UMD

### Platform/Method/Sensor

GEDI

### URL or DOI to Dataset Description

https://doi.org/10.3334/ORNLDAAC/2299

### URL to Download or Access the Data

https://daac.ornl.gov/GEDI/guides/GEDI_L4B_Gridded_Biomass_V2_1.html

### Data License

These data are available through the Oak Ridge National Laboratory (ORNL) Distributed Active Archive Center (DAAC)

### Intended Science Use Case

Biomass Harmonization 

### Date Needed By

11/20/2023

**Comment by nehahunka** [comment]
@wildintellect @abarciauskas-bgse

**Comment by wildintellect** [comment]
@nehahunka @lauraduncanson are we still waiting on a matching update to https://ceos.org/gst/GEDI-biomass.html?
@jjfrench can you link the relevant dashboard update PRs here for documentation and review?

**Comment by jjfrench** [comment]
- https://github.com/MAAP-Project/biomass-dashboard-datasets/pull/118
- https://github.com/MAAP-Project/biomass-earthdata-dashboard/pull/115

**Comment by freitagb** [comment]
@nehahunka - do we need to wait for the CEOS page to be updated to reference v2.1 or should we just update the dashboard?

**Comment by nehahunka** [comment]
@freitagb @lauraduncanson , still haven't asked anyone in CEOS to make the updates. I will get in touch with them, but I actually think it's better to first update the Biomass Harmonization Dashboard with the GEDI L4B v2.1 description and reference first. Is coming up with a new description my task?

**Comment by jjfrench** [comment]
@nehahunka , only if you want something different than or additions to https://raw.githubusercontent.com/MAAP-Project/biomass-dashboard-datasets/docs/GEDI_L4B_V2_1_summary/products/GEDI_L4B/summary.html based off of https://daac.ornl.gov/GEDI/guides/GEDI_L4B_Gridded_Biomass_V2_1.html

**Comment by nehahunka** [comment]
@jjfrench - many apologies for the delay on this. I see you've suggested using the same description of the dataset as on ORNL DAAC, which I think is actually fine. Please go ahead and merge, thank you!
