### ISSUE TITLE
Set conda forge as default channel

### ISSUE THREAD

**Issue by grallewellyn** [MAAP-Project/ZenHub#862]
Add this to dockerfile: `conda config --add channels conda-forge`
Should work now because .condarc file is being created
If this works, remove from documentation that always need to run with `-c conda-forge` tag
@wildintellect Is this okay with you?

**Comment by wildintellect** [comment]
@grallewellyn I'd leave it in the docs for now, it's still best practices and doesn't break anything. This fix will just mean that if people forget it, or don't know about it yet they won't accidentally installed mixed packages and get their env stuck, or fail to install.

**Comment by grallewellyn** [comment]
Make sure there is `.condarc` file saying conda-forge when doing this

**Comment by anilnatha** [comment]
@grallewellyn (fyi) moved this ticket into Review/QA
