### ISSUE TITLE
Default auto-generated base image incorrect in OPS

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#869]
The default base image in the algorithm registration form in the ADE is a DIT image.

**Comment by marjo-luc** [comment]
The field in the form is populated with whatever the value of the `DOCKERIMAGE_PATH` environment variable in the OPS environment is. This is what I see it assigned as in OPS -- is this not correct?

`DOCKERIMAGE_PATH=mas.dit.maap-project.org/root/maap-workspaces/base_images/vanilla:main`

**Comment by bsatoriu** [comment]
Each environment and workspace should be pointing to its respective base image. So, in the case of the latest OPS/vanilla image, it should be `mas.maap-project.org/root/maap-workspaces/base_images/vanilla:v3.1.3`

**Comment by sujen1412** [comment]
Can the `DOCKERIMAGE_PATH` be set in the devfile as an ENV var ?

**Comment by rtapella** [comment]
IMO this should be a hotfix because the registration UI is effectively broken until this is fixed.

**Comment by grallewellyn** [comment]
^ I agree with Rob: https://repo.maap-project.org/root/register-job-hysds-v4/-/jobs/14142

**Comment by bsatoriu** [comment]
@rtapella this issue has been fixed in OPS. To get the update you will need to create a new workspace of type Basic, ISCE3, Pangeo or R.
