### ISSUE TITLE
Set up EC2 for Gitlab runner

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#87]
We have a terraform script

**Comment by sujen1412** [comment]
As we move forward with keeping the infrastructure scripts on github, do you want me to move the terraform script on github.com from our private repo ? @gchang

**Comment by gchang** [comment]
Yes, that would be great! You can create a new repo for it if appropriate.

**Comment by sujen1412** [comment]
https://github.com/MAAP-Project/maap-terraform/tree/master/gitlab/gitlab-runner

**Comment by gchang** [comment]
@gchang to deploy after getting necessary permissions.
