### ISSUE TITLE
Issue Downloading GEDI 1/2 Data with Maap-py

### ISSUE THREAD

**Issue by wildintellect** [MAAP-Project/ZenHub#874]
**Describe the bug**
@arojas314 reported intermittent errors with downloading GEDI data from LPDAAC

**To Reproduce**
1. Run this algorithm 100 times (does it happen with a small queue?) https://repo.maap-project.org/arojearthdata/download-gedi-test.git

Or loop this code
```
def download_gedi(url,shortname):

    maap = MAAP(maap_host='api.maap-project.org')
    granule_name = os.path.basename(url)

    # Search for granule data using CMR host name and download
    results = maap.searchGranule(
        cmr_host='cmr.earthdata.nasa.gov',
        short_name=shortname,
        readable_granule_name = granule_name)
    # set output data directory
    CWD = os.path.dirname(os.path.abspath(__file__))
    outdir = os.path.join(CWD,"output")

    # check if directory exists -> if directory doesn't exist, directory is created
    if not os.path.exists(outdir):
        os.mkdir(outdir)
    try:
        # Download file!
        filename = results[0].getData(outdir)
    except Exception as e:
        print(f"Cant get data for granule {granule_name}")
        print(e)
        return 1
```

**Expected behavior**
Every job should succeed

**Additional context**
Succeeded
c5e3837f-b52b-41d4-b2f7-50422266ef01

Failed
0cdf9d22-71b9-4ef6-8fd7-f57f42e74a89

[GEDI-L1B-test-urls.txt](https://github.com/MAAP-Project/Community/files/13504032/GEDI-L1B-test-urls.txt)

**Comment by wildintellect** [comment]
There are several options:
1. using the maap-py library https://docs.maap-project.org/en/latest/science/GEDI/GEDI_L2A.html
2. with EarthDataCloud S3 temporary credentials https://docs.maap-project.org/en/latest/technical_tutorials/access/lpdaac_gedi_access.html
3. direct S3 access with AssumeRole https://docs.maap-project.org/en/latest/technical_tutorials/access/direct_access.html

For this I would suggest option 3, or maybe 2 but that might hit an issue if too many jobs at the same time are trying.

We also have a pre-built algorithm depending on what you need from the granules. Our GEDI subsetter works with L1/2/4 point data
https://docs.maap-project.org/en/latest/science/GEDI/GEDI_L4A.html
https://github.com/MAAP-Project/gedi-subsetter/

If you are launching these all at the same time you might be hitting a login throttle on the USGS side. Moving to an S3 access method may solve. Also longer running jobs or delay between job queuing may increase the chance of success. 
We have had similar issues previously and I think @bsatoriu might have implemented an authentication caching solution for this.
In [GEDI Subsetter](https://github.com/MAAP-Project/gedi-subsetter/) we download 100 granules in a single job using a cached credential so the authentication only happens 1x per hour.

**Comment by wildintellect** [comment]
@arojas314 can you post a description or code that demonstrates how you use the L1B and L2A matching granules once downloaded? This sounds related to https://github.com/MAAP-Project/gedi-subsetter/issues/11

**Comment by arojas314** [comment]
@wildintellect I need to use the RH values from L2A for each waveform in conjunctoin with the full waveform from L1B. I will test all these options and let you know which works best.
Thanks for the help!

**Comment by arojas314** [comment]
Option 3 is the solution since I am accessing many GEDI files (roughly 600 jobs where each job uses an L1B and L2A file pair, which equates to 1200 files). However, since my algorithm takes time to process, I needed to download the files first then open them (otherwise, the aws access times out?). I used this code below for future reference. Thanks again @wildintellect 
```python

import sys
import h5py
import boto3
import botocore
import fsspec
import requests
from maap.maap import MAAP
maap = MAAP(maap_host="api.maap-project.org")
import os


def assume_role_credentials(ssm_parameter_name):
    # Create a session using your current credentials
    session = boto3.Session()

    # Retrieve the SSM parameter
    ssm = session.client('ssm', "us-west-2")
    parameter = ssm.get_parameter(
        Name=ssm_parameter_name,
        WithDecryption=True
    )
    parameter_value = parameter['Parameter']['Value']

    # Assume the DAAC access role
    sts = session.client('sts')
    assumed_role_object = sts.assume_role(
        RoleArn=parameter_value,
        RoleSessionName='TutorialSession'
    )

    # From the response that contains the assumed role, get the temporary
    # credentials that can be used to make subsequent API calls
    credentials = assumed_role_object['Credentials']

    return credentials

# We can pass assumed role credentials into fsspec
def fsspec_access(credentials):
    return fsspec.filesystem(
        "s3",
        key=credentials['AccessKeyId'],
        secret=credentials['SecretAccessKey'],
        token=credentials['SessionToken']
    )

def lpdaac_gedi_https_to_s3(url):
    dir_comps = url.split("/")
    return f"s3://lp-prod-protected/{dir_comps[6]}/{dir_comps[8].strip('.h5')}/{dir_comps[8]}"

def get_gedi_data(url):
    s3_fsspec = fsspec_access(assume_role_credentials("/iam/maap-data-reader"))
    basename = os.path.basename(url)
    outfp = f"output/{basename}"
    gedi_ds = h5py.File(s3_fsspec.open(lpdaac_gedi_https_to_s3(url)), "r")
    with h5py.File(outfp, 'w') as dst:
        for obj in gedi_ds.keys():        
            gedi_ds.copy(obj, dst)   
    gedi_ds.close()
    # Return filepath!
    return outfp
```

**Comment by wildintellect** [comment]
@arojas314 glad it's working for you. Until you provide your actual algorithm code, we can't advise if there's a better way aside from downloading the granule pairs.

**Comment by jjfrench** [comment]
Done for now
