### ISSUE TITLE
Enable automated backups of home directory and bucket directories for ADE workspaces

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#881]

**Comment by gchang** [comment]
Enabled for /projects EFS mount using default AWS backup (35 day retention).
Enabled for maap-ops-registry and maap-ops-workspace using versioning and expiring non-current versions after 35 days.

@bsatoriu Could you try doing a restore on both EFS and S3? Also triple check that I set the S3 lifecycle correctly.

**Comment by gchang** [comment]
Possibly update the ADE IAM permissions to remove DeleteObject so that accidental deletes to S3 can't happen from workspaces.

**Comment by bsatoriu** [comment]
@gchang I performed a full restore and verification of our ops file system. The restored EFS is still available if you want to take a look. If not, I will go ahead and delete it.

**Comment by gchang** [comment]
Looks good @bsatoriu, I mounted it on one of the machines and was able to read data. It restores it to a subdirectory `/efs/aws-backup-restore_2024-02-08T15-17-28-879745831Z` so we'll need to rearrange if we actually restore. Please delete it now, all the data is in standard storage so it's pricey.

**Comment by bsatoriu** [comment]
@gchang the temporary EFS restore is deleted.
