### ISSUE TITLE
Add `stac_ipyleaflet` to all ADE images

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#884]
The package, `stac_ipyleaflet` should be available in all of our ADE workspaces, not just Pangeo.

**Comment by wildintellect** [comment]
BugFix release 0.3.6 https://github.com/MAAP-Project/stac_ipyleaflet/pull/127 should work for all the workspaces now.

**Comment by anilnatha** [comment]
Add to:

- [x] vanilla
- [x] r
- [x] isce3

(rgedi and isce2 are depcreated so no changed needed for those workspaces)
