### ISSUE TITLE
Dependency errors for `maap-py`

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#885]
During installation of `maap-py` using `pip install -e /path/to/maap-py/folder` command, our vanilla and pangeo workspaces are generating an error:

```
Cloning into '/maap-py'...
Note: switching to 'ceb74265ec3e8b5a9580a1a7414fadefa749adf8'.
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:
  git switch -c <new-branch-name>
Or undo this operation with:
  git switch -
Turn off this advice by setting config variable advice.detachedHead to false
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
awscli 2.14.1 requires cryptography<40.0.2,>=3.3.2, but you have cryptography 40.0.2 which is incompatible.
awscli 2.14.1 requires prompt-toolkit<3.0.39,>=3.0.24, but you have prompt-toolkit 3.0.43 which is incompatible.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

Here are links to the respective logs for a build that produced this error for [vanilla](https://repo.dit.maap-project.org/root/maap-workspaces/-/jobs/9468#L102) and [pangeo](https://repo.dit.maap-project.org/root/maap-workspaces/-/jobs/9467#L238)

It's worth noting that when testing the installation of `maap-py` by adding it to our `envrionment.yml` files I did not observe any errors (conda may be suppressing them) and @grallewellyn also observed no errors doing this while also using the verbosity flag (`-vvv`).

**Comment by grallewellyn** [comment]
So I think for this we have these options:
1. Assume or somehow prove that installing maap-py via the environment.yml with `git+` is actually fixing these dependency issues. If that is the case, then we need to make maap-py updates so that it fetches the variables/settings it needs from maap API instead
2. Continue installing via git clone and find a way to avoid these warning messages. This might include making changes to maap-py
3. Run a couple tests that Sujen suggests and if things for maap-py still seem to be working fine, just ignore this until maap-py is deployed as a pip package

Note that we are only seeing that exact error message for pangeo, vanilla, and isce3, but R is only seeing this error message
```
aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.34.3 which is incompatible.
```

I can start looking into option 2

**Comment by anilnatha** [comment]
Grace patched this issue, need final testing of workspace builds after new version of maap-py has been published and pins for maap-py are updated in our workspaces.

**Comment by grallewellyn** [comment]
Getting this error again for vanilla workspace 
```
#11 20.31 aiobotocore 2.12.1 requires botocore<1.34.52,>=1.34.41, but you have botocore 1.33.13 which is incompatible.
#11 20.31 awscli 2.14.1 requires cryptography<40.0.2,>=3.3.2, but you have cryptography 40.0.2 which is incompatible.
#11 20.31 awscli 2.14.1 requires prompt-toolkit<3.0.39,>=3.0.24, but you have prompt-toolkit 3.0.43 which is incompatible.
```

**Comment by chuckwondo** [comment]
@grallewellyn, let's book some time together on this so we can see how to avoid having this crop up repeatedly.

**Comment by grallewellyn** [comment]
I resolved this by:
- in maap-py pinning ipython==8.11.0 and _boto3_version = "1.34.41"
- adding boto3=1.34.41 to all base image environment.ymls 
Hopefully deploying maap-py as a pip package will resolve this in the future so we don't need to keep worrying about this?

**Comment by chuckwondo** [comment]
We might be trying to be overly restrictive with pinning, but I don't know exactly the specific steps you're following that lead to the resolution failures you're seeing. I'd really like to get on a call and walk through this with you. While getting maap-py published as a pip package _might_ help, I'm _not_ confident that it will _definitely_ make a difference.

**Comment by grallewellyn** [comment]
Building the images and installing maap-py like 
```
RUN mkdir /maap-py \
    && git clone --single-branch --branch v3.1.5 https://github.com/MAAP-Project/maap-py.git /maap-py/ \
    && pip install -e /maap-py/
```
Leads to us seeing 
```
#11 20.31 aiobotocore 2.12.1 requires botocore<1.34.52,>=1.34.41, but you have botocore 1.33.13 which is incompatible.
#11 20.31 awscli 2.14.1 requires cryptography<40.0.2,>=3.3.2, but you have cryptography 40.0.2 which is incompatible.
#11 20.31 awscli 2.14.1 requires prompt-toolkit<3.0.39,>=3.0.24, but you have prompt-toolkit 3.0.43 which is incompatible.
```
in the log files 
It didn't seem to affect the functionality of maap-py, but I resolved these errors just in case 

I just reached out to you on slack to set up a meeting time
