### ISSUE TITLE
Set up cluster for ADE

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#89]

**Comment by bsatoriu** [comment]
@gchang it seems I do not have permissions to attach an IAM role to an EC2 instance. The available roles provided by GCC only cover CloudWatch and S3 reading. To fully setup the cluster, I'll need a new role with the following permissions:

- AmazonEC2FullAccess
- AmazonRoute53FullAccess
- AmazonS3FullAccess
- IAMFullAccess
- AmazonVPCFullAccess

Alternatively, if you have access credentials for an IAM user with these permissions, we could configure the K8S master to use those.

**Comment by gchang** [comment]
Thanks, that's the info I was looking for. From the looks of it though, I'd say the GCC folks may be hesitant to give full access to all of those. Is there any way to make it more fine-grained?

**Comment by bsatoriu** [comment]
Yes, Kops has released a set of minimum required permissions that is more fine-grained than the list AWS recommends:

- Master Nodes: https://github.com/kubernetes/kops/blob/master/pkg/model/iam/tests/iam_builder_master_strict.json
- Compute Nodes: https://github.com/kubernetes/kops/blob/master/pkg/model/iam/tests/iam_builder_node_strict.json

More info is available here: https://github.com/kubernetes/kops/blob/master/docs/iam_roles.md (note the additional ECR permissions, which we should try to obtain as part of this request). This implies that two roles should be created as options for our EC2 instances: one for master and another for compute.

**Comment by gchang** [comment]
Possible heartburn with the ec2:CreateRoute permission. Is this something that's always needed or only once in creating the various subnets?

**Comment by bsatoriu** [comment]
It's used by kops during the initial networking setup, so it's a one-time need. Without it, I can workaround it by manually configuring the VPC, which would likely add an additional 3-5 points to the story.

**Comment by gchang** [comment]
For VPC, we may just ask the GCC people to configure it based on what we need. They seem to want to keep network configs close to their chest.

**Comment by bsatoriu** [comment]
@gchang below is a cluster setup script using kops with a manually-configured network, to get around the CreateRoute restriction. This script assumes carte blanche access, so I'm assuming we'll need to tailor this to GCC policies. To this end, let me know about the following:

- Are we required to run the ADE cluster on a shared VPC?
- If so, are we also required to run it on a shared subnet?

Based on the answers to those questions, I will be able verify a working setup script and give GCC a request that can get us going on the cluster.

1. Create VPC
$ aws ec2 create-vpc --cidr-block 10.0.0.0/16 --region us-west-2

2. Allow DNS hostnames
$ aws ec2 modify-vpc-attribute --vpc-id ${VPC_ID} --enable-dns-hostnames "{\"Value\":true}" --region ${REGION}

3. Create internet gateway

$ aws ec2 create-internet-gateway --region ${REGION}

4. Attach internet gateway to VPC

5. $ aws ec2 attach-internet-gateway --internet-gateway-id ${INTERNET_GATEWAY_ID} --vpc-id ${VPC_ID} --region ${REGION}

6. Create public zone & subnet 

$ aws ec2 create-subnet --vpc-id ${VPC_ID} --cidr-block 10.0.0.0/20 --availability-zone ${AVAILABILITY_ZONE_1} --region ${REGION}

7. Set public subnets to auto-assign public ip to instances 

$ aws ec2 modify-subnet-attribute --subnet-id ${PUBLIC_SUBNET_1} --map-public-ip-on-launch --region ${REGION}

8. Create private zone & subnet

$ aws ec2 create-subnet --vpc-id ${VPC_ID} --cidr-block 10.0.48.0/20 --availability-zone ${AVAILABILITY_ZONE_1} --region ${REGION}

9. Allocate address 

$ aws ec2 allocate-address --domain vpc --region ${REGION}

10. Create NAT gateway for public zone

$ aws ec2 create-nat-gateway --subnet-id ${PUBLIC_SUBNET_1} --allocation-id ${EIP_ALLOCATION_ID_1} --region ${REGION}

11. Create route table

$ aws ec2 create-route-table --vpc-id ${VPC_ID} --region ${REGION}

12. Create route for internet gateway

$ aws ec2 create-route --route-table-id ${RTB_PUBLIC_1} --destination-cidr-block 0.0.0.0/0 --gateway-id ${INTERNET_GATEWAY_ID} --region ${REGION}

13. Associate public subnets with route table

$ aws ec2 associate-route-table --route-table-id ${RTB_PUBLIC_1} --subnet-id ${PUBLIC_SUBNET_1} --region ${REGION}

14. [Create route table for private zone 

$ aws ec2 create-route-table --vpc-id ${VPC_ID} --region ${REGION}

15. Create route to NAT Gateway 

$ aws ec2 create-route --route-table-id ${RTB_PRIVATE_1} --destination-cidr-block 0.0.0.0/0 --nat-gateway-id ${NAT_GW_1} --region ${REGION}

16. Associate subnet

$ aws ec2 associate-route-table --route-table-id ${RTB_PRIVATE_1} --subnet-id ${PRIVATE_SUBNET_1} --region ${REGION}

17. Set up S3 Bucket as Kops state store

$ aws s3api create-bucket --bucket my-state-store --region ${REGION} --create-bucket-configuration LocationConstraint=us-west-2

18. Create cluster

$ kops create cluster --node-count 1 --zones ${AVAILABILITY_ZONE_1} --master-zones ${AVAILABILITY_ZONE_1} --state ${KOPS_STATE_STORE} --dns-zone=${DNS_ZONE_PRIVATE_ID} --dns private --node-size m5.large --master-size m5.large --topology private --networking weave --vpc=${VPC_ID} --bastion ${NAME}

19. Edit cluster to config subnets

$ kops edit cluster ${NAME}

20. Update subnets to correspond with created public/private subnet

$ kops update cluster ${NAME} --yes

**Comment by bsatoriu** [comment]
@gchang I've written a number of  scripts for deploying a Che cluster, but I wasn't able to get MAAP-Che 6 to work on a K8s AWS multi-node cluster. 

I had initially thought I had a working v6.19.6 cluster, but its workspaces do not fully launch in a K8s AWS multi-node cluster configuration. There is a networking problem after the workspaces start up that prevent them from loading within the Che host. [Example error](https://user-images.githubusercontent.com/1461122/54386604-a1342300-4699-11e9-94e1-c82e81c6c853.png)

Looking at the release notes for Che 7, the system became "Kubernetes-native" with the 7.0 release. There were [extensive code changes](https://github.com/eclipse/che/commit/154d668505cc86763f16ad8868e0a1fcf4bccc28) to fix the kinds of networking issues we're facing on v6.  I have found no evidence of a successful Che 6 deployment to a multi-node K8s cluster on AWS. Che 7, on the other hand, can be deployed fine using this configuration in either single or multi-host mode. Here are the scripts I have completed:

Che 6.19.6
- [Single-node microk8s](https://github.com/MAAP-Project/maap-eclipseche-ops/blob/master/setup-commands-v6.md) - works on a single EC2 instance
- [Multi-node K8s cluster, single-host](https://github.com/MAAP-Project/maap-eclipseche-ops/blob/master/cluster-setup-commands-v6.md) - NOT WORKING - network error when starting new workspaces.
- [Multi-node K8s cluster, multi-host](https://github.com/MAAP-Project/maap-eclipseche-ops/blob/master/cluster-setup-commands-v6-multihost.md) - NOT WORKING - network error when starting new workspaces.

Che 7.16.2
- [Multi-node K8s cluster, multi-host](https://github.com/MAAP-Project/maap-eclipseche-ops/blob/master/cluster-setup-commands-v7.md) - works using a single host name across multiple nodes.

To have a working cluster by end of the month on GCC, I see our options as the following:

1. Deploy v7.16.2 and migrate our stacks over to the new version
2. Try with a v6.19.6 cluster and work to find a solution to the workspace startup error. 
3. Deploy v6.19.6 single-node microk8s as a stop gap while we migrate to v7.

**Comment by gchang** [comment]
We've decided on #3
