### ISSUE TITLE
Upgrade Gitlab to latest

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#891]
https://about.gitlab.com/releases/2024/01/11/critical-security-release-gitlab-16-7-2-released/

**Comment by bsatoriu** [comment]
@gchang we're running GitLab version 15 due to breaking auth changes: https://github.com/MAAP-Project/Community/issues/852. We have another year of support for v15, but there is a high (not critical) bug pending for our v15 installations. I'll schedule an upgrade to `15.11.13` for this week.
