### ISSUE TITLE
EBS encryption on all instances in MCP

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#892]
This is a biggie. I created the spreadsheet that was given to me last month. Let's work through it together.

https://docs.google.com/spreadsheets/d/11b8LWu-T8jt4aBbibJTIStDLEgMWQO-SOlpB7qZEY3o/edit#gid=0

**Comment by bsatoriu** [comment]
@gchang I queried the MCP OPS EC2 instances and joined the result with the volumes sheet in this spreadsheet to identify the non-DPS machine volumes that need to be encrypted (see additional columns in the spreadsheet). 37 of the volumes are associated to non-DPS machines. The remaining 40 are presumably from DPS workers which will require updating the ASG templates.

**Comment by bsatoriu** [comment]
All of our EBS volumes are now encrypted.
