### ISSUE TITLE
Get & set up AWS IAM policies for HySDS

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#91]

**Comment by gchang** [comment]
Can export AWS policies, but for the complete terraform script, will need to discuss more.

Or we can just roll our own from the open source deployment.

**Comment by gchang** [comment]
@sujen1412 to get the policy json and send it to Shawn at MSFC

**Comment by sujen1412** [comment]
https://github.com/MAAP-Project/maap-terraform/commit/f3b43ed2c5a894298284f64fd8b19a764de81ee7

**Comment by gchang** [comment]
@gchang to submit policy for implementation to GCC for review once we have access to the machine.

**Comment by gchang** [comment]
@sujen1412 to verify that we can deploy DPS. I looked at the list of permissions that GCC users have (`gccTenantOperator`) and it seems like we have enough permissions.
