### ISSUE TITLE
Content on maap-project.org is outdated

### ISSUE THREAD

**Issue by freitagb** [MAAP-Project/ZenHub#916]
**Describe the bug**
News on [maap-project.org](maap-project.org) is from September 2019, the catalog search does not work, the visualization shows no available layers.

**Expected behavior**

- More recent news on MAAP achievements (e.g. [NASA-Funded Research Works to Harmonize Biomass Maps](https://www.earthdata.nasa.gov/learn/articles/maap-biomass-map-research))
- Integrate MAAP STAC catalog with catalog search
- Data layers should be able to be visualized in the web map from the data catalog.

**Comment by jjfrench** [comment]
Recently addressed, can close? @wildintellect

**Comment by wildintellect** [comment]
:laughing: yes

**Comment by rtapella** [comment]
The data visualization thing should probably be revisited at some point, or maybe cross-linked to VEDA?
