### ISSUE TITLE
sfarrow failing to install for R image

### ISSUE THREAD

**Issue by grallewellyn** [MAAP-Project/ZenHub#917]
R image in develop branch is now failing to build even though the same code was previously building. Image successfully builds if I just take out sfarrow

**Comment by wildintellect** [comment]
I'll look into this with @kylebarron

**Comment by wildintellect** [comment]
@grallewellyn can you provide a build log?

**Comment by grallewellyn** [comment]
I figured it out, `r-arrow` just needed to be installed in the environment.yml. Now the build is successful and I can `library('sfarrow')` in a notebook
Just weird that it was building before even when `r-arrow` wasn't explicitly installed in the environment.yml, but a r v3.1.4 image had `r-arrow` in conda list 
Now, nlraa, Fgmutils and sfarrow all have their dependencies in the r environment.yml
