### ISSUE TITLE
Earthdata not working from the portal page 

### ISSUE THREAD

**Issue by grallewellyn** [MAAP-Project/ZenHub#924]
In ops

**Comment by anilnatha** [comment]
CMR isn't accessible in the portal.  If this isn't supposed to be accessible here, should we remove it from the portal?

https://maap-project.org/search/

<img width="1616" alt="image" src="https://github.com/MAAP-Project/Community/assets/931107/29210283-b03c-4fc8-ad45-9eb2f1f6b09a">

**Comment by anilnatha** [comment]
@grallewellyn I've probably conflated CMR and EarthData. 🤷🏽

**Comment by grallewellyn** [comment]
@gchang Do we want to continue support for Explore -> Search Catalog in the MAAP portal? From an old ticket, this is what it looked like before:
<img width="809" alt="Screenshot 2024-02-15 at 5 26 07 PM" src="https://github.com/MAAP-Project/Community/assets/114033465/94f64006-7ba9-43f7-9488-da87aaa8f36e">

**Comment by gchang** [comment]
Remove the link from the portal. Create new tix to discuss with data team on whether we can directly link to MAAP datasets in EDSC.

**Comment by grallewellyn** [comment]
Created new tix here: https://github.com/MAAP-Project/Community/issues/944

**Comment by anilnatha** [comment]
I've removed the ability to navigate to "/search" on the portal from our menu and updated the /search page so that it redirects to the environment's respective homepage. With this page removed, it renders the tickets previously referenced moot, will close those tickets momentarily..
