### ISSUE TITLE
Algorithm Registration Input form-field layout makes it hard to read (horizontal scroll)

### ISSUE THREAD

**Issue by rtapella** [MAAP-Project/ZenHub#936]
The Algorithm Registration form section on Inputs runs off to the right of the page. This makes it more difficult to keep track of what you're doing while scrolling and makes it less obvious that you're missing some text-input boxes. 

Suggested fix:
Could be re-oriented into a vertical form as long as the distinction between fields is clear (not just split by rows, but more visually with spacing etc.).

@rtapella to update Figma mock-up
@someone else to code (Marjorie?)

**Comment by rtapella** [comment]
I'd like to prioritize this one

**Comment by rtapella** [comment]
this is all busted but a placeholder: https://www.figma.com/file/7yf3qkld60PuLRer06Sahl/Algorithm-Registration?type=design&node-id=2225%3A5601&mode=design&t=CLIYWbSOOSEKxmK9-1

**Comment by rtapella** [comment]
"Card" styling:
https://www.figma.com/file/7yf3qkld60PuLRer06Sahl/Algorithm-Registration?type=design&node-id=2238%3A3421&mode=design&t=nR8Kafr1iJcZXBhb-1

**Comment by rtapella** [comment]
"consistent" styling:
https://www.figma.com/design/7yf3qkld60PuLRer06Sahl/Algorithm-Registration?node-id=2294%3A3986&t=zQs2drfjfPQKrSL7-1

**Comment by marjo-luc** [comment]
@rtapella I can shrink down the inputs tables and make sure everything is within view. Would that work? I'm thinking the card approach might get clunky if registering an algorithm with more than a few inputs.

**Comment by rtapella** [comment]
Yeah there is a tradeoff on vertical-space vs. readability and a clear communication of which fields are filled in for each input.

I am not sure how you make sure everything is in view. Many scientists I observe are at 1024x resolution...

**Comment by rtapella** [comment]
We will look at this together as Marjorie starts to alter the layout and tweak as we go with some testing/examples

**Comment by marjo-luc** [comment]
[Implementation ticket](https://app.zenhub.com/workspaces/maap-platform-5ee7f0d1f440de0024cd359b/issues/gh/maap-project/community/1009)
