### ISSUE TITLE
aws cli help unusable missing dependency

### ISSUE THREAD

**Issue by wildintellect** [MAAP-Project/ZenHub#938]
**Describe the bug**
AWS command-line help is unavailable in ADE images.

**To Reproduce**
1. Boot up any ADE image (3.1.4)
2. In a terminal `aws s3 help`
```Could not find executable named "groff or mandoc"```

**Expected behavior**
The help page opens up.

**Additional context**
This probably only needs to be fixed on the jupyter images in https://github.com/MAAP-Project/maap-workspaces/tree/main/jupyterlab3

**Comment by marjo-luc** [comment]
@wildintellect I'm reassigning this to @grallewellyn

**Comment by chuckwondo** [comment]
@wildintellect, thanks for creating this issue. I noticed this today well.

@grallewellyn, this can be resolved simply by adding `groff` to the core list of linux packages installed in the images where the `awscli` is also installed.
