### ISSUE TITLE
Developer install documentation for jupyter extensions

### ISSUE THREAD

**Issue by grallewellyn** [MAAP-Project/ZenHub#954]
- add to developer docs markdown: 
    - node version
    - jupyterlab version
    - python version
    - pip install information/ how to publish 
- remove package-lock.json from .gitignore then commit it (for packages that have been giving us a lot of trouble) 
- .nvmrc file
-  review .gitignore
-  remove unused config files
- add branch protection on PR to main for maap-help extension
- update README

**Comment by marjo-luc** [comment]
adding to the list:

- review .gitignore
- remove unused config files

**Comment by marjo-luc** [comment]
add branch protection on PR to main for maap-help extension

**Comment by marjo-luc** [comment]
Let's coordinate on this. I may have to address some of these items in the jlab4 upgrade.

**Comment by marjo-luc** [comment]
I think I've covered most of the items listed above, if not all. PR's are open and ready for review for all extensions.

**Comment by grallewellyn** [comment]
Approved all the PRs for the extensions except for user workspace management jupyter extension because of get presigned s3 url bug we discussed. I also verified that the `main` branch for maap help required an approved PR 
I see all of the items listed above for each PR except 
- an `.nvmrc` file which I don't think we need because we say the nodejs version in the README 
- a committed package-lock.json. Do we not want to do this anymore? I see that algorithms, user workspace management, and maap libs don't have package-lock.json in their .gitignore, but it wasn't removed in the jlab4 PR. edsc, maap libs, che sidebar visibility removed package-lock.json from the .gitignore in the jlab4 PR 

Also, note that the dps README is missing the version of jupyter server extension and I commented that on the PR

**Comment by marjo-luc** [comment]
Yes. We should be using jlpm where we can, which uses yarn, so we'll have a yarn.lock and should no longer need the package-lock.json. I found dangling references to the package-lock.json file in the jupyter-server extension and maap-help, for which I've created new PR's with updates to address this.
