### ISSUE TITLE
Python paths wrong in pangeo 

### ISSUE THREAD

**Issue by grallewellyn** [MAAP-Project/ZenHub#956]
From Alex: 
"FYI something is wrong with the Python Paths in pangeo
the version of boto3 that imports is not what conda installed, in the terminal you can test this.

```
conda list | grep boto3
boto3                     1.34.51            pyhd8ed1ab_0    conda-forge
botocore                  1.34.51         pyge310_1234567_0    conda-forge

python
>>> botocore.__version__
'1.24.32'
```
"

I tested this for v3.1.4 vanilla, r, pangeo, and isce3 and they all say:
```
(pangeo) root@workspacevsstoit18l3xgvef:~# conda list | grep boto3
boto3                     1.33.13            pyhd8ed1ab_0    conda-forge
mypy-boto3-s3             1.34.14                  pypi_0    pypi
(pangeo) root@workspacevsstoit18l3xgvef:~# conda list | grep boto
aiobotocore               2.9.0              pyhd8ed1ab_0    conda-forge
boto3                     1.33.13            pyhd8ed1ab_0    conda-forge
botocore                  1.33.13            pyhd8ed1ab_0    conda-forge
mypy-boto3-s3             1.34.14                  pypi_0    pypi
(pangeo) root@workspacevsstoit18l3xgvef:~# python
Python 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> botocore.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'botocore' is not defined
>>> import botocore
>>> botocore.__version__
'1.33.13'
>>> 
```
@wildintellect Were you seeing this in a fresh pangeo v3.1.4 environment?

**Comment by anilnatha** [comment]
This may be an issue with the installation of `nb_conda_kernels`. Need to investigate further. This is also in relation to the  [issue mentioned](https://github.com/MAAP-Project/Community/issues/898#issuecomment-2000595860) in ticket #858 as I think they are the same underlying issue.

**Comment by chuckwondo** [comment]
FYI, as a minor convenience, you can replace `conda list | grep X` with simply `conda list X`

**Comment by wildintellect** [comment]
So the issue was user specific, I had a local python site-packages folder from 2022 that seemed to be in my path.
```
>>> botocore.__file__
'/projects/.local/lib/python3.10/site-packages/botocore/__init__.py'
```
Removing the folder resolved my issue.
