### ISSUE TITLE
Create a base DPS image for users

### ISSUE THREAD

**Issue by sujen1412** [MAAP-Project/ZenHub#966]
Currently, users are using (as base image) a pre-built base_image from https://github.com/MAAP-Project/maap-workspaces/tree/main/base_images. 
When an algorithm is submitted from registration we are including additional steps for creating a user ops and re-doing all permissions which takes up a lot of time during registration. 

TODO: Move up the work required at minimum by DPS to base images to save time during registration. 

Future (not covered in this ticket) : How to optimize space taken by these images.

**Comment by rtapella** [comment]
how does this relate to Stacks?

**Comment by sujen1412** [comment]
First pass, we will have a basic conda image as base image with no other packages installed.

**Comment by sujen1412** [comment]
@chuckwondo @wildintellect  Please try `mas.dit.maap-project.org/root/maap-workspaces/base_images/dps:dit`. Built from https://github.com/MAAP-Project/maap-workspaces/blob/dps_base_image/dps_base_image/Dockerfile

**Comment by chuckwondo** [comment]
@sujen1412 and I wrangled things in DIT and saw the GEDI Subsetter image go from 10.4GB using the python:v4.0.0 base image down to 4.31GB using the pared down dps image, so we saw ~60% reduction in size.

**Comment by chuckwondo** [comment]
@sujen1412, is there more you need to do before you can push the stripped down DPS base image to OPS?

**Comment by sujen1412** [comment]
Yes, there are a few more tests I need to run to ensure that jobs run successfully on the workers. This is done to test user permissions on directories that are mounted within a container when the job runs.
