### ISSUE TITLE
Finishing DEV documentation

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#97]

**Comment by echyam** [comment]
7/7: updated all README files for each extension to unify format and provide build/install/uninstall instructions.  Still need to provide documentation on Che-specific configurations

**Comment by echyam** [comment]
docs are under `dev-docs` branch for `develop` branch version of extensions' READMEs:
https://github.com/MAAP-Project/maap-jupyter-ide/tree/dev-docs
https://github.com/MAAP-Project/maap-jupyter-ide/tree/develop

**Comment by oddes** [comment]
eyam to update documentation: Order of extension installations

**Comment by echyam** [comment]
updated README to suggest order of extension installation from Dockerfile

**Comment by oddes** [comment]
Submit_jobs extension throwing bunch of errors with npm install. Looks like the issue with external jupyter_toastify extension: eyam is looking into this:

(base) MT-108842:submit_jobs sodde$ npm install

> submit_jobs@0.0.1 prepare /Users/sodde/maap_project/maap-jupyter-ide/submit_jobs
> npm run clean && npm run build


> submit_jobs@0.0.1 clean /Users/sodde/maap_project/maap-jupyter-ide/submit_jobs
> rimraf lib


> submit_jobs@0.0.1 build /Users/sodde/maap_project/maap-jupyter-ide/submit_jobs
> tsc

node_modules/@blueprintjs/core/lib/esm/components/divider/divider.d.ts:258:28 - error TS2707: Generic type 'UIEvent<T>' requires between 0 and 1 type arguments.

258         onScroll?: (event: React.UIEvent<HTMLElement, UIEvent>) => void;
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@blueprintjs/core/lib/esm/components/divider/divider.d.ts:259:35 - error TS2707: Generic type 'UIEvent<T>' requires between 0 and 1 type arguments.

259         onScrollCapture?: (event: React.UIEvent<HTMLElement, UIEvent>) => void;
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/activate.ts:8:1 - error TS6133: 'INotification' is declared but its value is never read.

8 import { INotification } from 'jupyterlab_toastify';
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/widgets.ts:327:15 - error TS2552: Cannot find name 'INotification'. Did you mean 'Notification'?

327               INotification.error(me._responseText);
                  ~~~~~~~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:11080:13
    11080 declare var Notification: {
                      ~~~~~~~~~~~~
    'Notification' is declared here.

src/widgets.ts:333:13 - error TS2552: Cannot find name 'INotification'. Did you mean 'Notification'?

333             INotification.error(me._responseText);
                ~~~~~~~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:11080:13
    11080 declare var Notification: {
                      ~~~~~~~~~~~~
    'Notification' is declared here.


Found 5 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! submit_jobs@0.0.1 build: `tsc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the submit_jobs@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sodde/.npm/_logs/2020-07-30T16_59_26_909Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! submit_jobs@0.0.1 prepare: `npm run clean && npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the submit_jobs@0.0.1 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by oddes** [comment]
@echyam @mayadebellis 

I see lot of people reported without setup env if u install its taking over 6 hours in resolving environment so needs to set env before run jupyter lab installations.
   **conda create --name myenv
       conda activate myenv**

1.  jupyterlab_toastify@2.3.0 did not worked, it worked version 3.0. Please see below error:

(myenv) MT-108842:maap-jupyter-ide sodde$ jupyter labextension install jupyterlab_toastify@2.3.0 --no-build
An error occured.
ValueError: 
**“jupyterlab_toastify@2.3.0” is not compatible with the current JupyterLab**
Conflicting Dependencies:
JupyterLab       Extension   Package
>=2.1.2 <2.2.0     >=1.0.0 <2.0.0 @jupyterlab/application
See the log file for details: /var/folders/5v/7gfg6c6s0f114f81wwj4n56hqcxxsw/T/jupyterlab-debug-5g34uyjv.log

2. jupyterlab-manager@1.0 did not worked, version 2.0 worked. Please see below error:
(myenv) MT-108842:maap-jupyter-ide sodde$ jupyter labextension install @jupyterlab/plotly-extension@1.0.0
An error occured.
ValueError: 
**"@jupyterlab/plotly-extension@1.0.0" is not compatible with the current JupyterLab**
Conflicting Dependencies:
JupyterLab                        Extension      Package
>=2.1.0 <2.2.0                    >=1.3.0 <2.0.0 @jupyterlab/rendermime-interfaces
See the log file for details:  /var/folders/5v/7gfg6c6s0f114f81wwj4n56hqcxxsw/T/jupyterlab-debug-8x9x4iar.log
(myenv) MT-108842:maap-jupyter-ide sodde$ jupyter labextension install @jupyter-widgets/jupyterlab-manager@1.0
An error occured.
ValueError: 

3. Finally, for the edsc extension, I am getting the following error with maap.py library not found but I have installed:

(myenv) MT-108842:edsc_extension sodde$ jupyter serverextension enable --py edsc_extension --sys-prefix
b'/Users/sodde/maap_project/maap-jupyter-ide/edsc_extension\n'
Traceback (most recent call last):
  File "/opt/anaconda3/envs/myenv/bin/jupyter-serverextension", line 11, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/myenv/lib/python3.8/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/anaconda3/envs/myenv/lib/python3.8/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/opt/anaconda3/envs/myenv/lib/python3.8/site-packages/notebook/serverextensions.py", line 294, in start
    super(ServerExtensionApp, self).start()
  File "/opt/anaconda3/envs/myenv/lib/python3.8/site-packages/jupyter_core/application.py", line 259, in start
    self.subapp.start()
  File "/opt/anaconda3/envs/myenv/lib/python3.8/site-packages/notebook/serverextensions.py", line 211, in start
    self.toggle_server_extension_python(arg)
  File "/opt/anaconda3/envs/myenv/lib/python3.8/site-packages/notebook/serverextensions.py", line 200, in toggle_server_extension_python
    m, server_exts = _get_server_extension_metadata(package)
  File "/opt/anaconda3/envs/myenv/lib/python3.8/site-packages/notebook/serverextensions.py", line 328, in _get_server_extension_metadata
    m = import_item(module)
  File "/opt/anaconda3/envs/myenv/lib/python3.8/site-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
  File "/Users/sodde/maap_project/maap-jupyter-ide/edsc_extension/edsc_extension/__init__.py", line 5, in <module>
    from .handlers import GetGranulesHandler, GetQueryHandler
  File "/Users/sodde/maap_project/maap-jupyter-ide/edsc_extension/edsc_extension/handlers.py", line 9, in <module>
    import maap
ModuleNotFoundError: No module named 'maap'

**Comment by oddes** [comment]
@echyam 
everything working good for me except the EDSC issue mentioned above. Please update the document as mentioned in my comments [commented on Aug 5, 2020] so we can close the issue

**Comment by echyam** [comment]
@oddes Done - please review and move to done if it looks good.

**Comment by oddes** [comment]
@echyam 
Thanks for the update. Looks good.
