### ISSUE TITLE
Registering an algorithm uses dit container url as default 

### ISSUE THREAD

**Issue by grallewellyn** [MAAP-Project/ZenHub#972]
<img width="1044" alt="Screenshot 2024-04-05 at 11 53 22 AM" src="https://github.com/MAAP-Project/Community/assets/114033465/ed26bdb9-5b03-43d7-bd94-c067178bf226">

Instead, this should be mas.maap-project.org/root/maap-workspaces/base_images/ like the dps tutorial 
![Screenshot 2024-04-05 at 11 53 30 AM](https://github.com/MAAP-Project/Community/assets/114033465/340ad4f2-ed48-433e-b0a9-0f3b2dc031ce)

**Comment by marjo-luc** [comment]
@grallewellyn this is a duplicate issue. The problem is an env variable being set incorrectly. See [here](https://app.zenhub.com/workspaces/maap-platform-5ee7f0d1f440de0024cd359b/issues/gh/maap-project/community/869).

**Comment by grallewellyn** [comment]
Sorry, I didn't see that ticket when searching before making this ticket
