### ISSUE TITLE
Migrate existing documentation

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#98]

**Comment by marjo-luc** [comment]
Documentation has been migrated to the dev server. I'm going to clean it up a little more then it will be ready for review and push to the production server.

**Comment by marjo-luc** [comment]
I'm trying to separate the content in the readme's in the maap-jupyter-ide repo so the documentation integration on the MAAP servers is cleaner, but it doesn't look like I have permissions to merge changes into master -- could I get permissions to do so?
