### ISSUE TITLE
Sharing of Notebook with Visualization to non MAAP users.

### ISSUE THREAD

**Issue by wildintellect** [MAAP-Project/ZenHub#987]
**Is your feature request related to a problem? Please describe.**
User @pahbs has requested the ability to share a visualization with colleagues. The initial visualization is an interactive plot within a jupyter notebook (usually python). The data embedded in the visualization comes from MAAP S3 buckets and is typically accessed via Titiler endpoints. It could be written with `folium`, `ipyleaflet`, `lonboard` or similar visualization widget.

**Describe the solution you'd like**
A method for sharing notebooks with interactive visualizations to users on or off the MAAP platform.

**Describe alternatives you've considered**

- [x] 1. Self published a rendered notebook to the web. This could be possible through executing the notebook, saving it will cell output and publishing it to a website, e.g. via github-pages. Just pushing to github is insufficient as the html/js of the cell output is likely blocked.
- [ ] 2. Publish a notebook that can be opened in the open-access tier of VEDA Hub. This would be a Binder type link to open the notebook in a limited compute instance.
- [ ] 3. Users could push a story to a Dashboard, possibly an unlisted page and reference a STAC query (if STAC records are published), or a self registered mosaic.

**Additional context**
In some cases the user might want a secret link, as the data is not ready for publication yet, and that is in some ways the whole intent of sharing the visualization.
The users would want full control over the styling of the layers, and the visualization could contain multiple layers.
Options 1 and 2 would support visualizations beyond just a map.
Since the data is in a protected bucket, option 1 relies on data accessible via an API. Option 2 could allow more direct access of data (this may not be desired)

**Comment by wildintellect** [comment]
@pahbs gave us a notebook to test with https://github.com/lauraduncanson/icesat2_boreal/blob/master/notebooks/Review_maps_test.ipynb

cc: @batpad

**Comment by wildintellect** [comment]
@omshinde please put the geotrees examples here, and explain the nbconvert flags required to ensure a properly executed notebook is used.

**Comment by omshinde** [comment]
In the GeoTREES example, we used the [notebook.sharing](notebook.sharing) space for sharing executed notebooks. 

1. [Biomass Reference Map Production](https://notebooksharing.space/view/d6a5b475c5c4f9700153bc83d0ac984ed410f1aefd69e74b155e4f2939eff9f5#displayOptions=)
2. [Visualization of Cloud-Optimized Earth Observation Data using Lonboard](https://notebooksharing.space/view/1d29aedacbc625447e9c3fc94b534f4ba79ac52554921d40d6043df607b3e12c#displayOptions=)
3. [Validation of Meta canopy height over Barro Colorado Island, Panama](https://notebooksharing.space/view/f965981a251729dd58c7d747d752913f791577c6bf29b91f4cf7923405e21683#displayOptions=)

### Note
Before using Notebook sharing, make sure to execute following commands for creating an executed notebook from your working notebook. 

1. Getting kernel name by for the relevant environment -
i/p - 

`jupyter kernelspec list`

o/p - 
```
Available kernels:
  python3    /opt/conda/envs/pangeo/share/jupyter/kernels/python3
  myenv      /projects/.local/share/jupyter/kernels/myenv
  pdal24     /projects/.local/share/jupyter/kernels/pdal24
  py37       /projects/.local/share/jupyter/kernels/py37
  py38       /projects/.local/share/jupyter/kernels/py38
  py39       /projects/.local/share/jupyter/kernels/py39
  vanilla    /projects/.local/share/jupyter/kernels/vanilla
```

2. Creating executed notebook. This command runs entire notebook and creates a version ready to be shared for reference.
```
python -m nbconvert file.ipynb --to ipynb --stdout --execute > file-executed.ipynb -ExecutePreprocessor.kernel_name=python3
```

**Comment by wildintellect** [comment]
Thanks @omshinde your example demonstrates the 1 option for a solution.
