### ISSUE TITLE
Add Accessbility Link

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#988]
The NASA accessibility link (https://www.nasa.gov/accessibility/) needs to be added to:

- [x] The Portal
- [x] scimaap.net

**Comment by anilnatha** [comment]
Accessibility link has been added to all three portal environments.

PR is awaiting review to add link to scimaap.net

**Comment by gchang** [comment]
Will put in review as it's already on the landing page, close out once we talk to ESA about policy.
