### ISSUE TITLE
Increase 30-record limit for Che organizations

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#99]
In Che, the default limit for querying user and organization records is 30. Since MAAP has a user count > 30, this is causing some MAAP users and sub-organizations to be unavailable as collaborators on user workspaces. 

To fix this problem, add an additional max count argument to any Che user/org REST query with a value of 500.

**Comment by bsatoriu** [comment]
For details on the maxItem count, see: https://github.com/eclipse/che/blob/57c43ac8cdd7111649414545a6ee9d156392d249/multiuser/api/che-multiuser-api-organization/src/main/java/org/eclipse/che/multiuser/organization/api/OrganizationService.java#L175

**Comment by bsatoriu** [comment]
I have fixed this by increasing the max count in the `permissions` endpoint response, but the deployment is pending resolution of story #112

**Comment by oddes** [comment]
@gchang @bsatoriu 

**DEV Environment:** [We may need a ticket to track this issue]
1. Need 30 users count on DEV environment [May be we can Copy the OPS users to DEV]
2. When I try to share the users on DEV:  "Add Developer" feature is not working. Users are not populating to add.

**OPS Environment:**
I see over 30 users and able to share the users on Che with no issues.

**Comment by oddes** [comment]
I have opened a new ticket to track the failed scenarios.
MAAP-Project/ZenHub#121
