### ISSUE TITLE
Review Jobs List UI

### ISSUE THREAD

**Issue by rtapella** [MAAP-Project/ZenHub#994]
The View Jobs UI has had a bunch of new features added (which is great).

The UI changes did not get an extensive design review ahead of time, so we should go back and make sure things are consistent, clear, grouped well, discoverable, etc.

**Comment by rtapella** [comment]
**UI issues**
- the “no filters” button for hide/show filters is non-obvious iconography. It looks like you’re eliminating the filters. Also if you toggle it on/off the visible status of the filters will reset but the actual state will not (e.g. the job status checkboxes get into a weird state if you’ve checked some off)
- “X” to clear filters could be okay if it was clear that it related to filters
- refresh-list (reload) button is connected to the filter options; this grouping implies that the function is related but it is not (list refresh vs. change the filters)

**Bugs**
- when you mouseover a row, the height expands a bit, maybe due to the red-box/cancel button
- the cancel button is hard to notice because it’s not near the point of “action” and its meaning is hard to distinguish because it appears even on completed jobs. 

**Actions**
- Mock up the buttons in a new way; new icons/labels and grouping
- maybe split refresh and the timestamp off?
- push “cancel”/action buttons down to the detail panel? And be context-dependent (e.g. disable cancel on completed jobs)
   - or: put cancel in the status column only on jobs that are cancel-able
   - or: make a new "Actions" column like airflow (https://airflow.apache.org/docs/apache-airflow/stable/ui.html)
- hide/show detail panel has weird controls. You can move it to the bottom and it’s gone, and then you can only (?) press the up-arrow to expand details to the whole view. Then how do you get the list back?
  - the fully-contracted/expanded drag-zones are unintuitive

**Comment by rtapella** [comment]
https://www.figma.com/design/e21NktxK3BH4ZLmbxh4qQm/Jobs?node-id=2029-7763&t=rEV22qcqzca3x2zx-1

**Comment by rtapella** [comment]
@anilnatha @marjo-luc rework of some of the jobs ui buttons. please review. what do you think?

**Comment by marjo-luc** [comment]
@rtapella This looks fine to me. I'll tackle this in the next milestone. Keep in mind, though, that some of the fields you have listed for the selected job in your figma are not available.

**Comment by rtapella** [comment]
The specific metadata fields should just be what's available in the ADES and the same as what we've got. It's really the button layouts that I was focused on here

**Comment by marjo-luc** [comment]
I figured. Just wanted to be clear.

**Comment by marjo-luc** [comment]
[Implementation ticket](https://app.zenhub.com/workspaces/maap-platform-5ee7f0d1f440de0024cd359b/issues/gh/maap-project/community/1007)
