### ISSUE TITLE
[Data]: Build spatial index of Meta global canopy height data

### ISSUE THREAD

**Issue by pahbs** [MAAP-Project/ZenHub#999]
### Dataset Name

High Resolution Canopy Height Maps by WRI and Meta

### Dataset Description

A spatial index for the tiles on AWS Open Registry associated with this dataset could support forest structure work ongoing on MAAP.

### Requestor Name/Affiliation

Paul Montesano

### Platform/Method/Sensor

MAXAR

### URL or DOI to Dataset Description

https://registry.opendata.aws/dataforgood-fb-forests/

### URL to Download or Access the Data

https://registry.opendata.aws/dataforgood-fb-forests/

### Data License

https://creativecommons.org/licenses/by/4.0/

### Intended Science Use Case

comparison with MAAP-produced boreal height estimates

### Format of the Data

geotiff

**Comment by pahbs** [comment]
this folder has global data: 
s3://dataforgood-fb-data/forests/v1/alsgedi_global_v6_float/ 
The chm subfolder has geotiffs and there is a tiles.geojson in that folder:
![image](https://github.com/MAAP-Project/Community/assets/8293229/9ef79852-0567-4912-a202-2e667a410256)

**Comment by wildintellect** [comment]
@pahbs can you post the full bucket S3 path to the geojson file?

**Comment by wildintellect** [comment]
For future reference if you need the tile index download this file, and query it in WGS84 Lat/Lon.
```s3://dataforgood-fb-data/forests/v1/alsgedi_global_v6_float/tiles.geojson```
